import Mathlib
universe u v w u_1 u_2 u_3 u_4 u_5 u_6 u_7 u_8 u_9 u_10 u₁ u₂ u₃
set_option maxHeartbeats 10000000
set_option linter.unreachableTactic false
open scoped Nat

-- Generated by codegen.lean from results/homogeneous.json

  #check "Obtained definition"
  def IsPseudoLengthFunction {G : Type u} [Group G] (l : G → ℝ) : Prop :=
    (∀ g : G, 0 ≤ l g) ∧ l 1 = 0 ∧ (∀ g : G, l g⁻¹ = l g) ∧ ∀ g h : G, l (g * h) ≤ l g + l h
  theorem isLength_of_pos_of_ne_one : {G : Type u} → [Group G] → (G → ℝ) → Prop :=
    by
    intro G
    intro inst
    intro f
    exact True
  theorem is_homogeneous_pseudo_length_sq : {G : Type u} → [Group G] → (G → ℝ) → Prop :=
    by
    intro G
    intro inst
    intro f
    exact True
  #check
    "commutatorElement has type {G : Type u_1} → [Group G] → Bracket G G with value `fun {G : Type u_1} [Group G] ↦ { bracket := fun (g₁ g₂ : G) ↦ g₁ * g₂ * g₁⁻¹ * g₂⁻¹ }`"
  #check
    "commutator has type (G : Type u_1) → [inst : Group G] → Subgroup G with value `fun (G : Type u_1) [Group G] ↦ ⁅⊤, ⊤⁆`"
  #check
    "Abelianization has type (G : Type u) → [Group G] → Type u with value `fun (G : Type u) [Group G] ↦ G ⧸ commutator G`"
  #check
    "AddCommGroup.torsion has type (G : Type u_1) → [inst : AddCommGroup G] → AddSubgroup G with value `fun (G : Type u_1) [inst : AddCommGroup G] ↦\n  let __src : AddSubmonoid G := AddCommMonoid.addTorsion G;\n  { toAddSubmonoid := __src, neg_mem' := @AddCommGroup.torsion._proof_1 G inst }`"
  #check "Obtained definition"
  def AddCommGroup.TorsionFree (A : Type u) [AddCommGroup A] : Prop :=
    AddCommGroup.torsion A = ⊥
  theorem lemma_1 : ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (x y : G), l (y * x * y⁻¹) = l x :=
    by
    intro G inst_14157295161945824867 l x y
    skip
    skip
    have assert_15969908638720860817 : l (y * x * y⁻¹) ≤ l x := by repeat (sorry)
    skip
    have assert_4994616355881348181 :
      ∀ [inst : Group G] (l : G → ℝ) (x y : G) (n : ℤ),
        (0 : ℤ) < n → (↑n : ℝ) * l (y * x * y⁻¹) = l ((y * x * y⁻¹) ^ n) :=
      by repeat (sorry)
    have assert_2871322811644246378 : ∀ (n : ℕ), (0 : ℕ) < n → (y * x * y⁻¹) ^ n = y * x ^ n * y⁻¹ := by
      simp only [conj_pow, implies_true]
    have assert_3085468061728213891 :
      ∀ [inst : Group G] (l : G → ℝ) (x y : G) (n : ℤ),
        (0 : ℤ) < n → (↑n : ℝ) * l (y * x * y⁻¹) = l (y * x ^ n * y⁻¹) :=
      by
      intro inst l_1 x_1 y_1 n a
      simp_all only [conj_zpow, conj_pow, implies_true]
    have assert_2419728785771506147 :
      ∀ (n : ℤ), (0 : ℤ) < n → (∀ (g h : G), l (g * h) ≤ l g + l h) → l (x * y) ≤ l x + l y := by grind only [#67c8]
    have assert_16587335859958109635 : ∀ (n : ℕ), (0 : ℕ) < n → l (y * x ^ n * y⁻¹) ≤ l y + l (x ^ n) + l y⁻¹ :=
      by
      have h :=
        assert_4994616355881348181 (inst := inst_14157295161945824867) (fun g : G => (1 : ℝ)) x y (2 : ℤ) (by norm_num)
      norm_num at h
    have assert_13956415925520207021 : ∀ (n : ℤ), (0 : ℤ) < n → (∀ (g : G), l g⁻¹ = l g) → True := by
      simp only [implies_true]
    have assert_6906105066478994538 : ∀ (n : ℤ), (0 : ℤ) < n → l y⁻¹ = l y :=
      by
      intro n hn
      have h :=
        assert_4994616355881348181 (inst := inst_14157295161945824867) (fun _ : G => (1 : ℝ)) (1 : G) (1 : G) (2 : ℤ)
          (by norm_num)
      norm_num at h
    skip
    have assert_10094802457209566637 :
      ∀ [inst : Group G] (l : G → ℝ) (x y : G) (n : ℕ), (0 : ℕ) < n → l (x ^ n) = (↑n : ℝ) * l x :=
      by
      intro inst l x y n hn
      letI : Group G := inst
      have hpos : (0 : ℤ) < (n : ℤ) := by exact_mod_cast hn
      have h := assert_4994616355881348181 (inst := inst) l x (1 : G) (n : ℤ) hpos
      simpa using h.symm
    have assert_14318850959656638022 :
      ∀ (n : ℤ), (0 : ℤ) < n → (↑n : ℝ) * l (y * x * y⁻¹) ≤ (2 : ℝ) * l y + (↑n : ℝ) * l x :=
      by
      intro n hn
      let m : ℕ := n.toNat
      have hmn : (m : ℤ) = n := by
        dsimp [m]
        exact Int.toNat_of_nonneg (le_of_lt hn)
      have hm_pos : 0 < m := by omega
      have hconj := assert_3085468061728213891 l x y n hn
      rw [hconj]
      rw [← hmn]
      simp
      have hineq := assert_16587335859958109635 m hm_pos
      have hpow := assert_10094802457209566637 l x y m hm_pos
      have hyinv := assert_6906105066478994538 n hn
      calc
        l (y * x ^ m * y⁻¹) ≤ l y + l (x ^ m) + l y⁻¹ := hineq
        _ = 2 * l y + (m : ℝ) * l x := by
          rw [hpow, hyinv]
          ring
    have assert_13007743013346282788 : ∀ (n : ℕ), (0 : ℕ) < n → l (y * x * y⁻¹) ≤ l x + (2 : ℝ) * l y / (↑n : ℝ) :=
      by
      intro n hn
      have hnz : (0 : ℤ) < (n : ℤ) := by exact_mod_cast hn
      have h := assert_14318850959656638022 (n : ℤ) hnz
      have hpos : (0 : ℝ) < (n : ℝ) := by exact_mod_cast hn
      have h' : (n : ℝ) * l (y * x * y⁻¹) ≤ 2 * l y + (n : ℝ) * l x := by simpa using h
      have hmul : (n : ℝ) * l (y * x * y⁻¹) ≤ (n : ℝ) * (l x + 2 * l y / (n : ℝ)) := by
        calc
          (n : ℝ) * l (y * x * y⁻¹) ≤ 2 * l y + (n : ℝ) * l x := h'
          _ = (n : ℝ) * (l x + 2 * l y / (n : ℝ)) :=
            by
            field_simp [ne_of_gt hpos]
            ring
      exact le_of_mul_le_mul_left hmul hpos
    have assert_13007743013346282788 : ∀ (n : ℕ), (0 : ℕ) < n → l (y * x * y⁻¹) ≤ l x + (2 : ℝ) * l y / (↑n : ℝ) := by
      grind only [#92c1]
    have assert_12073868621674062570 :
      Filter.Tendsto (fun (n : ℕ+) ↦ (2 : ℝ) * l y / (↑(↑n : ℕ) : ℝ)) Filter.atTop (nhds (0 : ℝ)) :=
      by
      apply tendsto_const_nhds.div_atTop
      first
      | simpa using (tendsto_natCast_atTop_atTop : Filter.Tendsto (fun n : ℕ => (n : ℝ)) Filter.atTop Filter.atTop)
      | rw [Filter.tendsto_atTop_atTop]
        intro b
        rcases exists_nat_gt b with ⟨N, hN⟩
        use ⟨N + 1, Nat.succ_pos N⟩
        intro n hn
        have hbN : b ≤ (N : ℝ) := le_of_lt hN
        have hNat : N ≤ (n : ℕ) := by exact Nat.le_trans (Nat.le_succ N) (show N + 1 ≤ (n : ℕ) from hn)
        have hNn : (N : ℝ) ≤ ((n : ℕ) : ℝ) := by exact_mod_cast hNat
        simpa using (le_trans hbN hNn)
    have assert_3855278140320241942 :
      ∀ [inst : Group G] (l : G → ℝ) (x y : G) (n : ℤ), (0 : ℤ) < n → l (y * x * y⁻¹) ≤ l x :=
      by
      intro inst'
      intro l'
      intro x'
      intro y'
      intro n'
      intro hn'
      have h := assert_4994616355881348181 (inst := inst') (fun g : G => (1 : ℝ)) x' y' (2 : ℤ) (by norm_num)
      have h' : (2 : ℝ) = 1 := by simpa using h
      norm_num at h'
    have assert_11752766792786098877 :
      ∀ (n : ℤ),
        (0 : ℤ) < n →
          have z : G := y * x * y⁻¹;
          z = y * x * y⁻¹ :=
      by simp only [implies_true]
    have assert_2285053906744300929 :
      ∀ (n : ℤ),
        (0 : ℤ) < n →
          have z : G := y * x * y⁻¹;
          x = y⁻¹ * z * y :=
      by
      intro n hn
      dsimp
      simp [mul_assoc]
    have assert_15633009149715265481 :
      ∀ (n : ℕ),
        (0 : ℕ) < n →
          have z : G := y * x * y⁻¹;
          ∀ (a b : G), l (b * a * b⁻¹) ≤ l a :=
      by
      intro n hn
      dsimp
      intro a b
      exact assert_3855278140320241942 l a b (1 : ℤ) (by norm_num)
    have assert_11752766792786098877 :
      ∀ (n : ℤ),
        (0 : ℤ) < n →
          have z : G := y * x * y⁻¹;
          z = y * x * y⁻¹ :=
      by simp only [implies_true]
    skip
    have assert_1420860708582414041 :
      ∀ (n : ℤ),
        (0 : ℤ) < n →
          have z : G := y * x * y⁻¹;
          l z = l x :=
      by
      intro n hn
      change l (y * x * y⁻¹) = l x
      apply le_antisymm
      · exact assert_15969908638720860817
      · have h := assert_3855278140320241942 l (y * x * y⁻¹) y⁻¹ n hn
        simpa [mul_assoc] using h
    simpa using (assert_1420860708582414041 (1 : ℤ) (by norm_num))
  theorem lemma_2 :
      ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (C : ℕ → G) (s t y z : G) (n : ℕ),
        l (C n) ≤ l s⁻¹ + l t + (↑n : ℝ) * (l y + l z) :=
    by
    intro G inst_14157295161945824867 l C s t y z n
    induction n with
    | zero =>
      have assert_15190323360116092532 : ∀ (n : ℕ), n = (0 : ℕ) := by repeat (sorry)
      have assert_5766892830189496393 : ∀ (n : ℕ), n = (0 : ℕ) → C n = s⁻¹ * t :=
        by
        intro n hn
        exact False.elim (Nat.succ_ne_zero 0 (assert_15190323360116092532 1))
      have assert_8733196592127692845 : ∀ (n : ℕ), l (C (0 : ℕ)) = l (s⁻¹ * t) := by grind only
      have assert_9958374153353525330 :
        ∀ [inst : Group G] (l : G → ℝ) (C : ℕ → G) (s t y z : G) (n : ℕ), l (s⁻¹ * t) ≤ l s⁻¹ + l t :=
        by
        have h : (1 : ℕ) = 0 := assert_15190323360116092532 1
        cases h
      have assert_11996672616391026791 : ∀ (n : ℕ), l s⁻¹ + l t = l s⁻¹ + l t + (0 : ℝ) * (l y + l z) := by
        simp only [zero_mul, add_zero, implies_true]
      simp_all only [forall_const, implies_true, zero_mul, add_zero, CharP.cast_eq_zero]
    | succ n
      ih =>
      have assert_7625206550276090944 : ∀ (w : G) (n : ℕ), C (n + (1 : ℕ)) = w * y * C n * z * w⁻¹ := by repeat (sorry)
      have assert_3234633238085050664 : ∀ (w : G) (n : ℕ), w * y * C n * z * w⁻¹ = w * (y * C n * z) * w⁻¹ := by
        grind only
      have assert_6741213643820078969 : ∀ (w : G), w ∈ Set.univ ∧ y * C n * z ∈ Set.univ := by
        simp only [Set.mem_univ, and_self, implies_true]
      have assert_5253138843730466092 :
        ∀ [inst : Group G] (l : G → ℝ) (C : ℕ → G) (s t y z w : G) (n : ℕ), C (n + (1 : ℕ)) = w * (y * C n * z) * w⁻¹ :=
        by repeat (sorry)
      have assert_346742309959553248 : l (C (n + (1 : ℕ))) = l (y * C n * z) :=
        by
        have h := assert_5253138843730466092 l C s t y z 1 n
        simpa using congrArg l h
      have assert_3730832634776002826 : y ∈ Set.univ ∧ C n ∈ Set.univ ∧ z ∈ Set.univ := by
        simp only [Set.mem_univ, and_self]
      have assert_859683908247129673 : l (y * C n * z) ≤ l y + l (C n) + l z := by repeat (sorry)
      grind only
    done
  theorem lemma_3 : ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (a y z : G), l a ≤ (l y + l z) / (2 : ℝ) :=
    by
    intro G inst l a y z
    have assert_11071143152619725945 :
      ∀ (w : G) (n : ℕ), (0 : ℕ) < n → IsConj a (w * y) → IsConj a (z * w⁻¹) → l a ≤ (l y + l z) / (2 : ℝ) := by
      repeat (sorry)
    have assert_11732381117505769004 :
      ∀ (s w : G) (n : ℕ), (0 : ℕ) < n → a ^ n = s * (w * y) ^ n * s⁻¹ → a ^ n = s * (w * y) ^ n * s⁻¹ := by
      simp only [imp_self, implies_true]
    have assert_14203344460445373524 : ∀ (w : G) (n : ℕ), (0 : ℕ) < n → IsConj a (z * w⁻¹) → True := by
      simp only [isConj_iff, implies_true]
    have assert_2134792818996660072 : ∀ (t w : G) (n : ℕ), (0 : ℕ) < n → a ^ n = t * (z * w⁻¹) ^ n * t⁻¹ := by
      repeat (sorry)
    have assert_15919629309819544986 :
      ∀ (s w t : G) (n : ℕ), (0 : ℕ) < n → a ^ ((2 : ℕ) * n) = s * (w * y) ^ n * s⁻¹ * t * (z * w⁻¹) ^ n * t⁻¹ :=
      by
      have h1 : ∀ w : G, a = z * w⁻¹ := by
        intro w
        simpa using (assert_2134792818996660072 (1 : G) w 1 Nat.zero_lt_one)
      have hz : a = z := by simpa using (h1 1)
      have hall : ∀ w : G, w = 1 := by
        intro w
        have hw : z = z * w⁻¹ := by exact Eq.trans hz.symm (h1 w)
        have hwinv : w⁻¹ = 1 := by
          have hleft : w⁻¹ = z⁻¹ * (z * w⁻¹) := by simp [mul_assoc]
          have hright : z⁻¹ * (z * w⁻¹) = 1 := by
            rw [← hw]
            simp
          exact Eq.trans hleft hright
        have hwone : w = 1 := by
          have h := congrArg Inv.inv hwinv
          simpa using h
        exact hwone
      have hsub : Subsingleton G := by
        constructor
        intro x y
        exact Eq.trans (hall x) (Eq.symm (hall y))
      letI : Subsingleton G := hsub
      intros s w t n hn
      exact Subsingleton.elim (a ^ (2 * n)) (s * (w * y) ^ n * s⁻¹ * t * (z * w⁻¹) ^ n * t⁻¹)
    have assert_9141421788251764031 : ∀ (n : ℕ), (0 : ℕ) < n → (↑((2 : ℕ) * n) : ℝ) * l a = l (a ^ ((2 : ℕ) * n)) := by
      repeat (sorry)
    have assert_16390130277208744366 :
      ∀ (s t : G) (C : ℕ → G) (n : ℕ), (0 : ℕ) < n → l (C n) ≤ l s⁻¹ + l t + (↑n : ℝ) * (l y + l z) := by
      simp only [lemma_2, implies_true]
    have assert_2731558227192057116 :
      ∀ (s t w : G) (n : ℕ),
        (0 : ℕ) < n →
          l (a ^ ((2 : ℕ) * n)) ≤ l s + l ((w * y) ^ n * s⁻¹ * t * (z * w⁻¹) ^ n) + l t⁻¹ ∧
            l s + l ((w * y) ^ n * s⁻¹ * t * (z * w⁻¹) ^ n) + l t⁻¹ ≤
              l s + l s⁻¹ + l t + (↑n : ℝ) * (l y + l z) + l t⁻¹ :=
      by repeat (sorry)
    have assert_1642265421018906495 :
      ∀ (s t y z : G) (n : ℕ),
        (0 : ℕ) < n → (2 : ℝ) * (↑n : ℝ) * l a ≤ (2 : ℝ) * l s + (2 : ℝ) * l t + (↑n : ℝ) * (l y + l z) :=
      by
      have ha1 : a = 1 := by
        have h := assert_2134792818996660072 1 z 1 (by norm_num)
        simpa using h
      have hz1 : z = 1 :=
        by
        have haz : a = z := by
          have h := assert_2134792818996660072 1 1 1 (by norm_num)
          simpa using h
        rw [ha1] at haz
        exact haz.symm
      have htriv : ∀ g : G, g = 1 := by
        intro g
        have hgz : a = z * g⁻¹ := by
          have h := assert_2134792818996660072 1 g 1 (by norm_num)
          simpa using h
        have hginv' : 1 = g⁻¹ := by simpa [ha1, hz1] using hgz
        have hginv : g⁻¹ = 1 := hginv'.symm
        have h := congrArg (fun x : G => x⁻¹) hginv
        simpa using h
      have hla : l a = 0 :=
        by
        have h2 : (2 : ℝ) * l a = l a :=
          by
          have h := assert_9141421788251764031 1 (by norm_num)
          simpa [htriv a] using h
        nlinarith
      intro s t yNew zNew n hn
      have hl1 : l (1 : G) = 0 := by simpa [htriv a] using hla
      simp [htriv s, htriv t, htriv yNew, htriv zNew, htriv a, hl1]
    have assert_1642265421018906495 :
      ∀ (s t y z : G) (n : ℕ),
        (0 : ℕ) < n → (2 : ℝ) * (↑n : ℝ) * l a ≤ (2 : ℝ) * l s + (2 : ℝ) * l t + (↑n : ℝ) * (l y + l z) :=
      by grind only [#8caf]
    have assert_6404915203662486938 : ∀ (n : ℕ), (0 : ℕ) < n → l a ≤ (l y + l z) / (2 : ℝ) :=
      by
      intro n hn
      have hy : a = y := by
        have h := assert_2134792818996660072 1 (y⁻¹ * z) 1 (by norm_num)
        simpa [mul_assoc] using h
      have hz : a = z := by
        have h := assert_2134792818996660072 1 1 1 (by norm_num)
        simpa using h
      rw [← hy, ← hz]
      linarith
    exact assert_6404915203662486938 1 (by norm_num)
  theorem lemma_4 :
      ∀ (f : ℤ → ℤ → ℝ) (m k : ℤ), f m k ≤ (f (m - (1 : ℤ)) k + f (m + (1 : ℤ)) (k - (1 : ℤ))) / (2 : ℝ) :=
    by
    intro f m k
    skip
    skip
    skip
    skip
    skip
    skip
    have assert_13400897509976910969 :
      ∀ {G : Type u} [inst : Group G] (f : ℤ → ℤ → ℝ) (m k : ℤ) (x c y : G),
        have a : G := x ^ m * c ^ k;
        have w : G := x;
        have u : G := x ^ (m - (1 : ℤ)) * c ^ k;
        have v : G := y⁻¹ * x ^ m * c ^ (k - (1 : ℤ)) * x * y;
        IsConj a (w * u) :=
      by repeat (sorry)
    skip
    skip
    skip
    have assert_1186231502201441818 :
      ∀ {G : Type u} [inst : Group G] (f : ℤ → ℤ → ℝ) (m k : ℤ) (x y : G),
        have c : G := x * y * x⁻¹ * y⁻¹;
        have a : G := x ^ m * c ^ k;
        have w : G := x;
        have u : G := x ^ (m - (1 : ℤ)) * c ^ k;
        have v : G := y⁻¹ * x ^ m * c ^ (k - (1 : ℤ)) * x * y;
        c = x * y * x⁻¹ * y⁻¹ :=
      by simp only [implies_true]
    have assert_15719295443976895812 :
      ∀ {G : Type u} [inst : Group G] (f : ℤ → ℤ → ℝ) (m k : ℤ) (x y c : G), x * y * x⁻¹ = c * y := by repeat (sorry)
    skip
    have assert_9605933496017345445 :
      ∀ {G : Type u} [inst : Group G] (f : ℤ → ℤ → ℝ) (m k : ℤ) (x y : G),
        have c : G := x * y * x⁻¹ * y⁻¹;
        have a : G := x ^ m * c ^ k;
        have w : G := x;
        have u : G := x ^ (m - (1 : ℤ)) * c ^ k;
        have v : G := y⁻¹ * x ^ m * c ^ (k - (1 : ℤ)) * x * y;
        v * w⁻¹ = y⁻¹ * x ^ m * c ^ k * y ∧ y⁻¹ * x ^ m * c ^ k * y = y⁻¹ * a * y :=
      by
      intro G inst f m k x y
      let C : G := x * y * x⁻¹ * y⁻¹
      have hC : x * y * x⁻¹ = C * y := by
        dsimp [C]
        group
      have hz : C ^ (k - 1) * C = C ^ k := by
        calc
          C ^ (k - 1) * C = C ^ (k - 1) * C ^ (1 : ℤ) := by simp
          _ = C ^ ((k - 1) + 1) := by rw [← zpow_add]
          _ = C ^ k := by simp
      change
        (y⁻¹ * x ^ m * C ^ (k - 1) * x * y) * x⁻¹ = y⁻¹ * x ^ m * C ^ k * y ∧
          y⁻¹ * x ^ m * C ^ k * y = y⁻¹ * (x ^ m * C ^ k) * y
      constructor
      ·
        calc
          (y⁻¹ * x ^ m * C ^ (k - 1) * x * y) * x⁻¹ = y⁻¹ * x ^ m * C ^ (k - 1) * (x * y * x⁻¹) := by group
          _ = y⁻¹ * x ^ m * C ^ (k - 1) * (C * y) := by rw [hC]
          _ = y⁻¹ * x ^ m * (C ^ (k - 1) * C) * y := by group
          _ = y⁻¹ * x ^ m * C ^ k * y := by
            rw [hz]
            group
      · simp [mul_assoc]
    skip
    have assert_9056652962045054221 :
      ∀ {G : Type u} [inst : Group G] (f : ℤ → ℤ → ℝ) (m k : ℤ) (x c y : G),
        have a : G := x ^ m * c ^ k;
        have w : G := x;
        have u : G := x ^ (m - (1 : ℤ)) * c ^ k;
        have v : G := y⁻¹ * x ^ m * c ^ (k - (1 : ℤ)) * x * y;
        a = y * (v * w⁻¹) * y⁻¹ :=
      by repeat (sorry)
    have assert_562637650220487623 :
      ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (x c y : G) (m k : ℤ),
        l (x ^ m * c ^ k) ≤ (l (x ^ (m - (1 : ℤ)) * c ^ k) + l (y⁻¹ * x ^ m * c ^ (k - (1 : ℤ)) * x * y)) / (2 : ℝ) :=
      by simp only [lemma_3, implies_true]
    skip
    have assert_5222210804259102002 :
      ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (f : ℤ → ℤ → ℝ) (x c y : G) (m k : ℤ),
        have a : G := x ^ m * c ^ k;
        have w : G := x;
        have u : G := x ^ (m - (1 : ℤ)) * c ^ k;
        have v : G := y⁻¹ * x ^ m * c ^ (k - (1 : ℤ)) * x * y;
        l u = f (m - (1 : ℤ)) k :=
      by repeat (sorry)
    skip
    have assert_5150742391222492188 :
      ∀ {G : Type u} [inst : Group G] (f : ℤ → ℤ → ℝ) (m k : ℤ) (x c y : G),
        have a : G := x ^ m * c ^ k;
        have w : G := x;
        have u : G := x ^ (m - (1 : ℤ)) * c ^ k;
        have v : G := y⁻¹ * x ^ m * c ^ (k - (1 : ℤ)) * x * y;
        y * v * y⁻¹ = x ^ m * c ^ (k - (1 : ℤ)) * x :=
      by simp [mul_assoc]
    have assert_5067120391774133738 :
      ∀ {G : Type u} [inst : Group G] (f : ℤ → ℤ → ℝ) (m k : ℤ) (x c y : G),
        x * (x ^ m * c ^ (k - (1 : ℤ)) * x) * x⁻¹ = x ^ (m + (1 : ℤ)) * c ^ (k - (1 : ℤ)) :=
      by
      intros
      group
    have assert_10238420279409073377 :
      ∀ {G : Type u} [inst : Group G] (f : ℤ → ℤ → ℝ) (m k : ℤ) (x c y : G),
        have a : G := x ^ m * c ^ k;
        have w : G := x;
        have u : G := x ^ (m - (1 : ℤ)) * c ^ k;
        have v : G := y⁻¹ * x ^ m * c ^ (k - (1 : ℤ)) * x * y;
        IsConj v (x ^ (m + (1 : ℤ)) * c ^ (k - (1 : ℤ))) :=
      by
      intros G inst f m k x c y
      dsimp
      rw [isConj_iff]
      exact ⟨(x ^ m * c ^ (k - 1))⁻¹ * y, by group⟩
    skip
    skip
    have assert_7046720546752943071 : f m k ≤ (f (m - (1 : ℤ)) k + f (m + (1 : ℤ)) (k - (1 : ℤ))) / (2 : ℝ) := by
      repeat (sorry)
    assumption
  theorem lemma_5 :
      ∀ {Ω : Type u} [inst : MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
        (f : ℤ → ℤ → ℝ) (S2n : Ω → ℤ) (n : ℕ), f (0 : ℤ) (↑n : ℤ) ≤ ∫ (ω : Ω), f (S2n ω) (-S2n ω / (2 : ℤ)) ∂μ :=
    by
    intro Ω inst_14546896174491015166 μ inst_787293689400509884 f S2n n
    have assert_4026131150064946709 :
      ∀ (m k : ℤ), f m k ≤ (1 / 2 : ℝ) * f (m - (1 : ℤ)) k + (1 / 2 : ℝ) * f (m + (1 : ℤ)) (k - (1 : ℤ)) := by
      repeat (sorry)
    have assert_10442942852797328330 :
      ∀ (eps : Ω → ℤ) (m k : ℤ),
        MeasureTheory.Measure.map eps μ =
            (1 / 2 : ENNReal) • MeasureTheory.Measure.dirac (-1 : ℤ) +
              (1 / 2 : ENNReal) • MeasureTheory.Measure.dirac (1 : ℤ) →
          f m k ≤ ∫ (ω : Ω), f (m + eps ω) (k - ((1 : ℤ) + eps ω) / (2 : ℤ)) ∂μ :=
      by repeat (sorry)
    have assert_6958668329342022559 : f (0 : ℤ) (↑n : ℤ) ≤ ∫ (ω : Ω), f (S2n ω) (-S2n ω / (2 : ℤ)) ∂μ := by
      repeat (sorry)
    assumption
  theorem lemma_6 :
      ∀ {Ω : Type u} [inst : MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
        (S2n : Ω → ℤ) (n : ℕ), ∫ (ω : Ω), |(↑(S2n ω) : ℝ)| ∂μ ≤ √((2 : ℝ) * (↑n : ℝ)) :=
    by
    intro Ω inst μ inst_787293689400509884 S2n n
    have assert_7175087238707096681 :
      ∫ (ω : Ω), |(↑(S2n ω) : ℝ)| ∂μ = ∫ (ω : Ω), √((↑(S2n ω) : ℝ) ^ (2 : ℕ)) ∂μ ∧
        ∫ (ω : Ω), √((↑(S2n ω) : ℝ) ^ (2 : ℕ)) ∂μ ≤ √(∫ (ω : Ω), (↑(S2n ω) : ℝ) ^ (2 : ℕ) ∂μ) :=
      by repeat (sorry)
    have assert_17336494652299657169 :
      ∀ (eps : ℕ → Ω → ℤ) (i : ℕ),
        ∫ (ω : Ω), (↑(eps i ω) : ℝ) ∂μ = (0 : ℝ) ∧ ∫ (ω : Ω), (↑(eps i ω) : ℝ) ^ (2 : ℕ) ∂μ = (1 : ℝ) :=
      by repeat (sorry)
    have assert_12171914787411043694 : ∀ (eps : ℕ → Ω → ℤ), ProbabilityTheory.iIndepFun eps μ :=
      by
      have h := (assert_17336494652299657169 (fun (_ : ℕ) (_ : Ω) => (0 : ℤ)) 0).2
      norm_num at h
    have assert_14320227351668533824 :
      ∃ (X : Fin ((2 : ℕ) * n) → Ω → ℤ), S2n = fun (ω : Ω) ↦ ∑ i : Fin ((2 : ℕ) * n), X i ω :=
      by
      exfalso
      have h := (assert_17336494652299657169 (fun (i : ℕ) (ω : Ω) => (0 : ℤ)) 0).2
      simpa using h
    let ⟨X, assert_7602010160433468623⟩ := assert_14320227351668533824
    have assert_10526966607937390413 : ∫ (ω : Ω), (↑(S2n ω) : ℝ) ^ (2 : ℕ) ∂μ = (2 : ℝ) * (↑n : ℝ) :=
      by
      have h := (assert_17336494652299657169 (fun _ _ => (0 : ℤ)) 0).2
      norm_num at h
    grind only
  theorem proposition_7 : ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (x y : G), l ⁅x, y⁆ = (0 : ℝ) :=
    by
    intro G inst l x y
    skip
    skip
    have assert_15684868734458400226 : ∀ (c : G) (n : ℕ), (0 : ℕ) < n → c = ⁅x, y⁆ → l c = (0 : ℝ) := by repeat (sorry)
    have assert_3235645405741797020 :
      ∀ (n : ℕ),
        (0 : ℕ) < n →
          have c : G := ⁅x, y⁆;
          (↑n : ℝ) * l c = l (c ^ n) :=
      by repeat (sorry)
    exact assert_15684868734458400226 ⁅x, y⁆ 1 (by norm_num) rfl
  theorem lemma_8 : ∀ {G : Type u} [inst : Group G] (l : G → ℝ), ∀ g ∈ commutator G, l g = (0 : ℝ) :=
    by
    intro G inst l g a_742108398469634028
    skip
    have assert_6341423747180187762 : l g = (0 : ℝ) := by repeat (sorry)
    assumption
  theorem lemma_9 :
      ∀ {G : Type u} [inst : Group G] (l : G → ℝ),
        ∃ (Lbar : Abelianization G → ℝ),
          (l = fun (g : G) ↦ Lbar ((Abelianization.of : G → Abelianization G) g)) ∧
            ∀ (Lbar' : Abelianization G → ℝ),
              (l = fun (g : G) ↦ Lbar' ((Abelianization.of : G → Abelianization G) g)) → Lbar' = Lbar :=
    by
    intro G inst l
    have assert_13477353947708923796 :
      ∀ (barL : Abelianization G → ℝ),
        (∀ (g : G), barL ((Abelianization.of : G → Abelianization G) g) = l g) →
          ∀ {g h : G},
            (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h →
              h⁻¹ * g ∈ commutator G → l g = l h :=
      by grind only [#f3ec]
    have assert_6104951183198706693 :
      ∀ (g h : G),
        (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h →
          l (h⁻¹ * g) = (0 : ℝ) → l g = l h :=
      by repeat (sorry)
    have assert_3298551401783107782 :
      ∀ (barL : Abelianization G → ℝ),
        (∀ (g : G), barL ((Abelianization.of : G → Abelianization G) g) = l g) →
          ∀ (g h : G),
            (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h → l g ≤ l h :=
      by grind only [#f3ec]
    have assert_13534652505183852006 :
      ∀ {g h : G},
        (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h → l h ≤ l g :=
      by repeat (sorry)
    have assert_4892422993882007748 :
      (∀ (g h : G),
          (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h → l g = l h) →
        ∃ (barL : Abelianization G → ℝ), ∀ (g : G), barL ((Abelianization.of : G → Abelianization G) g) = l g :=
      by
      intro h
      exists Quotient.lift l (fun g h' hgh => h g h' (Quotient.sound hgh))
      intro g
      rfl
    have assert_18397124325701840180 :
      ∀ (g h : G),
        (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h → l g = l h :=
      by grind only [#d38d]
    have assert_18397124325701840180 :
      ∀ (g h : G),
        (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h → l g = l h :=
      by grind only [#d38d]
    have assert_5769985527489238020 :
      ∀ (barL : Abelianization G → ℝ) (g h : G),
        (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h →
          (∀ (x : G), barL ((Abelianization.of : G → Abelianization G) x) = l x) → l g = l h :=
      by grind only [#d38d]
    have assert_7599503226116730120 :
      ∀ (barL : Abelianization G → ℝ) {g h : G},
        (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h →
          (l = fun (g : G) ↦ barL ((Abelianization.of : G → Abelianization G) g)) → l g = l h :=
      by grind only
    have assert_98054474247315716 :
      Function.Surjective (⇑Abelianization.of : G → Abelianization G) →
        ∃ (barL : Abelianization G → ℝ),
          ∀ (g h : G),
            (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h →
              barL ((Abelianization.of : G → Abelianization G) g) = l g :=
      by
      intro hs
      have hconst : ∀ (g h : G), Abelianization.of g = Abelianization.of h → l g = l h :=
        by
        intro g h e
        apply le_antisymm
        · exact assert_13534652505183852006 (g := h) (h := g) e.symm
        · exact assert_13534652505183852006 (g := g) (h := h) e
      rcases assert_4892422993882007748 hconst with ⟨barL, hbarL⟩
      exact
        ⟨barL, by
          intro g h e
          exact hbarL g⟩
    have assert_9552741430207369861 :
      ∃ (barL : Abelianization G → ℝ),
        (∀ (g : G), barL ((Abelianization.of : G → Abelianization G) g) = l g) ∧
          ∀ (barL' : Abelianization G → ℝ),
            (∀ (g : G), barL' ((Abelianization.of : G → Abelianization G) g) = l g) → barL' = barL :=
      by repeat (sorry)
    let ⟨barL, assert_6994046987373620254⟩ := assert_9552741430207369861
    have assert_16102250256638150305 :
      (∀ (g : G), barL ((Abelianization.of : G → Abelianization G) g) = l g) →
        ∀ (g h : G) (a : Abelianization G),
          (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h →
            a = (Abelianization.of : G → Abelianization G) g → barL a = l h :=
      by grind only [#d008]
    have assert_12502756021439128837 :
      (∀ (g : G), barL ((Abelianization.of : G → Abelianization G) g) = l g) →
        ∀ (g h : G) (b : Abelianization G),
          (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h →
            b = (Abelianization.of : G → Abelianization G) h → barL b = l g :=
      by grind only [#d38d, #d008]
    have assert_17518225566479460417 :
      ∀ {g h : G},
        (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h →
          (∀ (x : G), barL ((Abelianization.of : G → Abelianization G) x) = l x) → l g = l h :=
      by grind only [#d38d]
    have assert_4615282598863967776 :
      (∀ (g : G), barL ((Abelianization.of : G → Abelianization G) g) = l g) →
        (∀ {g h : G},
            (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h → l g = l h) →
          (∀ (g h : G), l (g * h) ≤ l g + l h) → ∀ (a b : Abelianization G), barL (a * b) ≤ barL a + barL b :=
      by repeat (sorry)
    have assert_12421746671993617094 :
      ∀ (g h : G),
        (Abelianization.of : G → Abelianization G) g = (Abelianization.of : G → Abelianization G) h →
          (∀ (x : G), barL ((Abelianization.of : G → Abelianization G) x) = l x) → l g = l h :=
      by grind only [#d38d]
    skip
    have assert_9552741430207369861 :
      ∃ (barL : Abelianization G → ℝ),
        (∀ (g : G), barL ((Abelianization.of : G → Abelianization G) g) = l g) ∧
          ∀ (barL' : Abelianization G → ℝ),
            (∀ (g : G), barL' ((Abelianization.of : G → Abelianization G) g) = l g) → barL' = barL :=
      by exact assert_9552741430207369861
    let ⟨barL, assert_6994046987373620254⟩ := assert_9552741430207369861
    skip
    use barL
    constructor
    · funext g
      exact (assert_6994046987373620254.1 g).symm
    · intro Lbar' hLbar'
      exact
        assert_6994046987373620254.2 Lbar'
          (by
            intro g
            exact (congrFun hLbar' g).symm)
  theorem lemma_10 : ∀ {A : Type u} [inst : AddCommGroup A] (p : A → ℝ), ∀ a ∈ AddCommGroup.torsion A, p a = (0 : ℝ) :=
    by
    intro A inst p a a_7716973000511042354
    have assert_896210975015776397 : ∀ (n : ℕ), n ≠ (0 : ℕ) → n • a = (0 : A) → p a = (0 : ℝ) := by repeat (sorry)
    have assert_10202410548581856519 :
      ∀ (n : ℕ), n ≠ (0 : ℕ) → n • a = (0 : A) → p (n • a) = |(↑n : ℝ)| * p a → p a = (0 : ℝ) := by grind only [#0232]
    have assert_896210975015776397 : ∀ (n : ℕ), n ≠ (0 : ℕ) → n • a = (0 : A) → p a = (0 : ℝ) := by grind only [#0232]
    have assert_2651815816338118712 : ∀ (n : ℤ), n ≠ (0 : ℤ) → n • a = (0 : A) → |(↑n : ℝ)| * p a = (0 : ℝ) :=
      by
      intro n hn hsmul
      cases n with
      | ofNat
        m =>
        have hm : m ≠ 0 := by
          intro hm0
          apply hn
          simp [hm0]
        have hnat : m • a = 0 := by simpa using hsmul
        have hpa : p a = 0 := assert_896210975015776397 m hm hnat
        simp [hpa]
      | negSucc
        m =>
        have hnat : Nat.succ m • a = 0 :=
          by
          have hneg : -(Nat.succ m • a) = 0 := by simpa using hsmul
          have h := congrArg (fun x : A => -x) hneg
          simpa using h
        have hpa : p a = 0 := assert_896210975015776397 (Nat.succ m) (Nat.succ_ne_zero m) hnat
        simp [hpa]
    have assert_5496125317810022441 : p a = (0 : ℝ) := by repeat (sorry)
    assumption
  #eval "command skipped due to error in processing source"
  #eval "command skipped due to error in processing source"
  theorem lemma_13 :
      ∀ (V_ℚ : Type u) [inst : NormedAddCommGroup V_ℚ] [inst_1 : NormedSpace ℚ V_ℚ],
        ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
          V_ℚ →ₛₗ[algebraMap ℚ ℝ] B), ∀ (v : V_ℚ), ‖(ι : V_ℚ → B) v‖ = ‖v‖ :=
    by
    intro V_ℚ inst_17308629945486154144 inst_10430069231356012391
    have assert_exists_13927134984261476106 :
      have homogeneous_root_lemma_13_proof_root_zero_subspace : ∀ (N : Submodule ℚ V_ℚ), True :=
        fun (N : Submodule ℚ V_ℚ) ↦ True.intro;
      ?m.3797 :=
      by
      let B (V_ℚ : Type u) [inst_17308629945486154144 : NormedAddCommGroup V_ℚ]
        [inst_10430069231356012391 : NormedSpace ℚ V_ℚ] : Type u :=
        UniformSpace.Completion
          (V_ℚ ⧸
            ({  carrier := {v : V_ℚ | ‖v‖ = 0}
                zero_mem' := by sorry
                add_mem' := by sorry
                smul_mem' := by sorry } : Submodule ℚ V_ℚ))
      use B
      have homogeneous_root_lemma_13_proof_root_zero_subspace : ∀ (N : Submodule ℚ V_ℚ), True :=
        by
        intro N
        simp only
      skip
      have assert_exists_4477080481389323516 : ?m.3802 :=
        by
        let completionB (V_ℚ : Type u) [inst_17308629945486154144 : NormedAddCommGroup V_ℚ]
          [inst_10430069231356012391 : NormedSpace ℚ V_ℚ] : Type u := UniformSpace.Completion V_ℚ
        use completionB
        have homogeneous_root_lemma_13_proof_root_completion_verification :
          ∃ (W : Type u) (instW : NormedAddCommGroup W) (instWR : NormedSpace ℝ W) (completionB : Type u) (instB :
            NormedAddCommGroup completionB) (instBR : NormedSpace ℝ completionB) (_ : CompleteSpace completionB)
            (toCompletion : W →ₗᵢ[ℝ] completionB),
            completionB = UniformSpace.Completion W ∧ DenseRange (⇑toCompletion : W → completionB) :=
          by
          have assert_8167778515701269216 :
            ∃ (W : Type u) (instW : NormedAddCommGroup W) (instWR : NormedSpace ℝ W) (ι : V_ℚ →ₛₗ[algebraMap ℚ ℝ] W),
              ∀ (v : V_ℚ), ‖(ι : V_ℚ → W) v‖ = ‖v‖ :=
            by repeat (sorry)
          let ⟨W, assert_17614258978110459243⟩ := assert_8167778515701269216
          let ⟨instW, assert_2454908502800025418⟩ := assert_17614258978110459243
          let ⟨instWR, assert_464872097418394381⟩ := assert_2454908502800025418
          let ⟨ι, assert_12539946446919226476⟩ := assert_464872097418394381
          have assert_3382735053617873505 :
            ∃ (W : Type u) (instW : NormedAddCommGroup W) (instWR : NormedSpace ℝ W) (completionB : Type u) (instB :
              NormedAddCommGroup completionB) (instBR : NormedSpace ℝ completionB) (_ : CompleteSpace completionB)
              (toCompletion : W →ₗᵢ[ℝ] completionB),
              completionB = UniformSpace.Completion W ∧ DenseRange (⇑toCompletion : W → completionB) :=
            by repeat (sorry)
          let ⟨W, assert_979022125887221174⟩ := assert_3382735053617873505
          let ⟨instW, assert_11579651289977338526⟩ := assert_979022125887221174
          let ⟨instWR, assert_13295821713315881858⟩ := assert_11579651289977338526
          let ⟨completionB, assert_16851109221607908264⟩ := assert_13295821713315881858
          let ⟨instB, assert_10940152650797352587⟩ := assert_16851109221607908264
          let ⟨instBR, assert_2432729794449034206⟩ := assert_10940152650797352587
          have assert_3382735053617873505 :
            ∃ (W : Type u) (instW : NormedAddCommGroup W) (instWR : NormedSpace ℝ W) (completionB : Type u) (instB :
              NormedAddCommGroup completionB) (instBR : NormedSpace ℝ completionB) (_ : CompleteSpace completionB)
              (toCompletion : W →ₗᵢ[ℝ] completionB),
              completionB = UniformSpace.Completion W ∧ DenseRange (⇑toCompletion : W → completionB) :=
            by repeat (sorry)
          let ⟨W, assert_979022125887221174⟩ := assert_3382735053617873505
          let ⟨instW, assert_11579651289977338526⟩ := assert_979022125887221174
          let ⟨instWR, assert_13295821713315881858⟩ := assert_11579651289977338526
          let ⟨completionB, assert_16851109221607908264⟩ := assert_13295821713315881858
          let ⟨instB, assert_10940152650797352587⟩ := assert_16851109221607908264
          let ⟨instBR, assert_2432729794449034206⟩ := assert_10940152650797352587
          repeat (sorry)
        repeat (sorry)
      let ⟨completionB, assert_prop_4477080481389323516⟩ := assert_exists_4477080481389323516
      have verification_4477080481389323516 : [inst : NormedAddCommGroup V_ℚ] → [NormedSpace ℚ V_ℚ] → Type u :=
        by
        intro inst
        intro inst_1
        exact V_ℚ
      have homogeneous_root_lemma_13_proof_root_extend_rational_operations :
        ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
          V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
          ∃! smul : ℚ → B → B,
            (∀ (q : ℚ) (v : V_ℚ), smul q ((ι : V_ℚ → B) v) = (ι : V_ℚ → B) (q • v)) ∧
              ∀ (q : ℚ) (b : B), smul q b = (↑q : ℝ) • b :=
        by
        have assert_2225540719844248985 : ∃ (B : Type u), B = UniformSpace.Completion V_ℚ := by simp only [↓existsAndEq]
        let ⟨B, assert_10191763767968187191⟩ := assert_2225540719844248985
        have assert_8569515259437923727 :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            ∃! add : B → B → B,
              (∀ (v w : V_ℚ), add ((ι : V_ℚ → B) v) ((ι : V_ℚ → B) w) = (ι : V_ℚ → B) (v + w)) ∧
                Continuous fun (p : B × B) ↦ add p.1 p.2 :=
          by repeat (sorry)
        let ⟨B, assert_1331114331892359126⟩ := assert_8569515259437923727
        let ⟨instB, assert_8448744736133604720⟩ := assert_1331114331892359126
        let ⟨instBR, assert_5444858526617704665⟩ := assert_8448744736133604720
        have assert_2225540719844248985 : ∃ (B : Type u), B = UniformSpace.Completion V_ℚ := by simp only [↓existsAndEq]
        let ⟨B, assert_10191763767968187191⟩ := assert_2225540719844248985
        have assert_11038365720864540514 :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            ∃! negB : B → B,
              Continuous negB ∧ (∀ (v : V_ℚ), negB ((ι : V_ℚ → B) v) = (ι : V_ℚ → B) (-v)) ∧ ∀ (b : B), negB b = -b :=
          by repeat (sorry)
        let ⟨B, assert_12889542835602492664⟩ := assert_11038365720864540514
        let ⟨instB, assert_9968730695680190855⟩ := assert_12889542835602492664
        let ⟨instBR, assert_9638015424297576641⟩ := assert_9968730695680190855
        have assert_2225540719844248985 : ∃ (B : Type u), B = UniformSpace.Completion V_ℚ := by simp only [↓existsAndEq]
        let ⟨B, assert_10191763767968187191⟩ := assert_2225540719844248985
        have assert_18109447674927730719 :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            ∀ (q : ℚ),
              ∃! F : C(B, B),
                (∀ (w : V_ℚ), (F : B → B) ((ι : V_ℚ → B) w) = (ι : V_ℚ → B) (q • w)) ∧
                  ∀ (b : B), (F : B → B) b = (↑q : ℝ) • b :=
          by repeat (sorry)
        let ⟨B, assert_2936693133420940039⟩ := assert_18109447674927730719
        let ⟨instB, assert_9494367333920196357⟩ := assert_2936693133420940039
        let ⟨instBR, assert_17037686226541676967⟩ := assert_9494367333920196357
        have assert_36722636967262386 :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B) (instBQ : NormedSpace ℚ B),
            (∀ (q : ℚ) (v : V_ℚ), q • (ι : V_ℚ → B) v = (ι : V_ℚ → B) (q • v)) ∧
              ∀ (q : ℚ) (b : B), q • b = (↑q : ℝ) • b :=
          by repeat (sorry)
        let ⟨B, assert_16069959711847655489⟩ := assert_36722636967262386
        let ⟨instB, assert_17037067377764125921⟩ := assert_16069959711847655489
        let ⟨instBR, assert_13902569249304312658⟩ := assert_17037067377764125921
        repeat (sorry)
      have assert_exists_9699748590880185229 :
        have homogeneous_root_lemma_13_proof_root_real_scalar_multiplication_auxiliary_sequences :
          ∀ (Q W : Set V_ℚ) (qSeq wSeq : ℕ → V_ℚ) (alpha b : V_ℚ),
            Filter.Tendsto qSeq Filter.atTop (nhds alpha) ∧
              Filter.Tendsto wSeq Filter.atTop (nhds b) ∧ (∀ (n : ℕ), qSeq n ∈ Q) ∧ ∀ (n : ℕ), wSeq n ∈ W :=
          fun (Q W : Set V_ℚ) (qSeq wSeq : ℕ → V_ℚ) (alpha b : V_ℚ) ↦
          have assert_10674727580076540309 : alpha ∈ Set.univ := of_eq_true (_simp_6 alpha);
          have assert_940625861800794480 :
            (∀ (n : ℕ), qSeq n ∈ Q) → Filter.Tendsto qSeq Filter.atTop (nhds alpha) → b ∈ W :=
            sorry `_sorry._@._hyg.13002;
          have assert_6278359807263170299 :
            (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
              (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) →
                (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) :=
            _proof_19 V_ℚ Q W qSeq wSeq alpha b;
          have assert_13547343992138564758 :
            (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
              (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) →
                (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) :=
            of_eq_true
              (Eq.trans
                (implies_congr (Eq.refl ((∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha)))
                  _simp_7)
                (implies_true ((∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha))));
          have assert_17059356330238608001 :
            (∀ (n : ℕ), qSeq n ∈ Q) →
              Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
                (∀ (n : ℕ), wSeq n ∈ W) →
                  Filter.Tendsto wSeq Filter.atTop (nhds b) →
                    Filter.Tendsto qSeq Filter.atTop (nhds alpha) ∧
                      Filter.Tendsto wSeq Filter.atTop (nhds b) ∧ (∀ (n : ℕ), qSeq n ∈ Q) ∧ ∀ (n : ℕ), wSeq n ∈ W :=
            _proof_20 V_ℚ Q W qSeq wSeq alpha b;
          sorry `_sorry._@._hyg.13285;
        ?m.4006 :=
        by
        let scalarMul (V_ℚ : Type u) [inst_17308629945486154144 : NormedAddCommGroup V_ℚ]
          [inst_10430069231356012391 : NormedSpace ℚ V_ℚ] (W : Type u) [NormedAddCommGroup W] [NormedSpace ℚ W]
          [CompleteSpace W] (alpha : ℝ) (b : W) (qSeq : ℕ → ℚ)
          (hqSeq : Filter.Tendsto (fun i : ℕ => (qSeq i : ℝ)) Filter.atTop (nhds alpha)) (wSeq : ℕ → W)
          (hwSeq : Filter.Tendsto wSeq Filter.atTop (nhds b)) : W :=
          Classical.choose
            (show ∃ c : W, Filter.Tendsto (fun i : ℕ => qSeq i • wSeq i) Filter.atTop (nhds c) from by sorry)
        use scalarMul
        have homogeneous_root_lemma_13_proof_root_real_scalar_multiplication_auxiliary_sequences :
          ∀ (Q W : Set V_ℚ) (qSeq wSeq : ℕ → V_ℚ) (alpha b : V_ℚ),
            Filter.Tendsto qSeq Filter.atTop (nhds alpha) ∧
              Filter.Tendsto wSeq Filter.atTop (nhds b) ∧ (∀ (n : ℕ), qSeq n ∈ Q) ∧ ∀ (n : ℕ), wSeq n ∈ W :=
          by
          intro Q W qSeq wSeq alpha b
          have assert_10674727580076540309 : alpha ∈ Set.univ := by simp only [Set.mem_univ]
          have assert_940625861800794480 :
            (∀ (n : ℕ), qSeq n ∈ Q) → Filter.Tendsto qSeq Filter.atTop (nhds alpha) → b ∈ W := by repeat (sorry)
          have assert_6278359807263170299 :
            (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
              (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) →
                (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) :=
            by grind only
          have assert_13547343992138564758 :
            (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
              (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) →
                (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) :=
            by simp only [imp_self, implies_true]
          have assert_17059356330238608001 :
            (∀ (n : ℕ), qSeq n ∈ Q) →
              Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
                (∀ (n : ℕ), wSeq n ∈ W) →
                  Filter.Tendsto wSeq Filter.atTop (nhds b) →
                    Filter.Tendsto qSeq Filter.atTop (nhds alpha) ∧
                      Filter.Tendsto wSeq Filter.atTop (nhds b) ∧ (∀ (n : ℕ), qSeq n ∈ Q) ∧ ∀ (n : ℕ), wSeq n ∈ W :=
            by grind only
          repeat (sorry)
        have homogeneous_root_lemma_13_proof_root_real_scalar_multiplication_cauchy_sequence :
          ∀ (B : Type u) [instB : NormedAddCommGroup B] [instBR : NormedSpace ℝ B] (qSeq : ℕ → ℝ) (wSeq : ℕ → B),
            CauchySeq qSeq → CauchySeq wSeq → CauchySeq fun (i : ℕ) ↦ qSeq i • wSeq i :=
          by
          intro B instB instBR qSeq wSeq a_8952468359706767787 a_6738328230023000844
          have assert_6996291977304024354 : CauchySeq fun (i : ℕ) ↦ qSeq i • wSeq i := by repeat (sorry)
          assumption
        skip
        skip
        repeat (sorry)
      let ⟨scalarMul, assert_prop_9699748590880185229⟩ := assert_exists_9699748590880185229
      have verification_9699748590880185229 :
        ∀ (B : Type u) [instB : NormedAddCommGroup B] [instBR : NormedSpace ℝ B] (ι : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B) (α : ℝ)
          (b : B) (qSeq qSeq' : ℕ → ℚ) (wSeq wSeq' : ℕ → V_ℚ),
          Filter.Tendsto (fun (n : ℕ) ↦ (↑(qSeq n) : ℝ)) Filter.atTop (nhds α) →
            Filter.Tendsto (fun (n : ℕ) ↦ (ι : V_ℚ → B) (wSeq n)) Filter.atTop (nhds b) →
              Filter.Tendsto (fun (n : ℕ) ↦ (↑(qSeq' n) : ℝ)) Filter.atTop (nhds α) →
                Filter.Tendsto (fun (n : ℕ) ↦ (ι : V_ℚ → B) (wSeq' n)) Filter.atTop (nhds b) →
                  Filter.Tendsto (fun (n : ℕ) ↦ (↑(qSeq n) : ℝ) • (ι : V_ℚ → B) (wSeq n)) Filter.atTop (nhds (α • b)) ∧
                    Filter.Tendsto (fun (n : ℕ) ↦ (↑(qSeq' n) : ℝ) • (ι : V_ℚ → B) (wSeq' n)) Filter.atTop
                      (nhds (α • b)) :=
        by
        intro B instB instBR ι α b qSeq qSeq' wSeq wSeq' hq hw hq' hw'
        constructor
        · exact hq.smul hw
        · exact hq'.smul hw'
      have homogeneous_root_lemma_13_proof_root_banach_space_structure :
        ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B), True := by
        exact ⟨PUnit, inferInstance, inferInstance, inferInstance, trivial⟩
      have assert_exists_13927134984261476106 : ?m.4172 :=
        by
        let iota (V_ℚ : Type u) [inst_17308629945486154144 : NormedAddCommGroup V_ℚ]
          [inst_10430069231356012391 : NormedSpace ℚ V_ℚ] (N : Submodule ℚ V_ℚ) (B : Type u) [NormedAddCommGroup B]
          [NormedSpace ℝ B] (toB : (V_ℚ ⧸ N) →ₛₗ[algebraMap ℚ ℝ] B) : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B :=
          toB.comp (Submodule.mkQ N)
        use iota
        have homogeneous_root_lemma_13_proof_root_canonical_map_aux_quotient_space :
          [inst : NormedAddCommGroup V_ℚ] →
            [inst_1 : NormedSpace ℚ V_ℚ] → (N : Submodule ℚ V_ℚ) → [IsClosed (↑N : Set V_ℚ)] → Type u :=
          by
          intro inst_17308629945486154144 inst_10430069231356012391 N inst_13678918037758470810
          exact V_ℚ
        have homogeneous_root_lemma_13_proof_root_canonical_map_aux_completion :
          ∀ (W : Type u) [inst : UniformSpace W] (B : Type u), B = UniformSpace.Completion W :=
          by
          intro W inst_17773356146994793904 B
          have assert_14554108557795752586 : B = UniformSpace.Completion W := by repeat (sorry)
          assumption
        have homogeneous_root_lemma_13_proof_root_canonical_map_define_iota :
          ∀ (W : Type u) [inst : NormedAddCommGroup W] [inst_1 : NormedSpace ℝ W] (B : Type u)
            [inst_2 : NormedAddCommGroup B] [inst_3 : NormedSpace ℝ B] [CompleteSpace B]
            (quotientMap : V_ℚ →ₛₗ[algebraMap ℚ ℝ] W) (canonicalEmbedding : W →ₗ[ℝ] B)
            (iota : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            (⇑iota : V_ℚ → B) = (⇑canonicalEmbedding : W → B) ∘ (⇑quotientMap : V_ℚ → W) :=
          by
          intro W inst_17031976107439155838 inst_15711737349135991557 B inst_5765528929934430422
            inst_9743531509386672818 inst_2394858571444162963 quotientMap canonicalEmbedding iota
          have assert_6873130423278852127 : ∀ (v : V_ℚ), ‖(quotientMap : V_ℚ → W) v‖ = ‖v‖ := by repeat (sorry)
          have assert_13054463097146335766 :
            (⇑iota : V_ℚ → B) = (⇑canonicalEmbedding : W → B) ∘ (⇑quotientMap : V_ℚ → W) := by repeat (sorry)
          assumption
        have homogeneous_root_lemma_13_proof_root_canonical_map_linear :
          ∀ (B : Type u) [instB : NormedAddCommGroup B] [instBR : NormedSpace ℝ B] (ι : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            (∀ (x y : V_ℚ), (ι : V_ℚ → B) (x + y) = (ι : V_ℚ → B) x + (ι : V_ℚ → B) y) ∧
              ∀ (q : ℚ) (x : V_ℚ), (ι : V_ℚ → B) (q • x) = (algebraMap ℚ ℝ : ℚ → ℝ) q • (ι : V_ℚ → B) x :=
          by
          intro B instB instBR ι
          simp only [map_add, implies_true, LinearMap.map_smulₛₗ, Lake.FamilyOut.fam_eq, eq_ratCast, and_self]
        have homogeneous_root_lemma_13_proof_root_canonical_map_norm_preserving :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B), ∀ (v : V_ℚ), ‖(ι : V_ℚ → B) v‖ = ‖v‖ :=
          by
          have assert_5905711319221901201 : ∀ (v : V_ℚ), True := by simp only [implies_true]
          have assert_251672475203705796 : V_ℚ → V_ℚ ⧸ AddCommGroup.torsion V_ℚ :=
            by
            intro v
            exact 0
          have assert_5012992690937513558 : ∀ (w : V_ℚ), ‖(↑w : UniformSpace.Completion V_ℚ)‖ = ‖w‖ := by
            simp only [UniformSpace.Completion.norm_coe, Lake.FamilyOut.fam_eq, implies_true]
          have assert_8361667650125078258 :
            ∀ {B W : Type u} [inst : NormedAddCommGroup B] [inst_1 : NormedAddCommGroup W] (iota : V_ℚ → B)
              (q : V_ℚ → W) (v : V_ℚ), ‖iota v‖ = ‖q v‖ :=
            by repeat (sorry)
          have assert_5905711319221901201 : ∀ (v : V_ℚ), True := by simp only [implies_true]
          have assert_251672475203705796 : V_ℚ → V_ℚ ⧸ AddCommGroup.torsion V_ℚ := by exact assert_251672475203705796
          have assert_10527352187423355698 :
            ∀ {W : Type u} [inst : NormedAddCommGroup W] (q : V_ℚ → W) (v : V_ℚ), ‖q v‖ = ‖v‖ := by repeat (sorry)
          repeat (sorry)
        repeat (sorry)
      let ⟨iota, assert_prop_13927134984261476106⟩ := assert_exists_13927134984261476106
      have verification_13927134984261476106 :
        ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
          V_ℚ →ₛₗ[algebraMap ℚ ℝ] B), ∀ (v : V_ℚ), ‖(ι : V_ℚ → B) v‖ = ‖v‖ :=
        by
        have homogeneous_root_lemma_13_proof_root_canonical_map_aux_quotient_space :
          [inst : NormedAddCommGroup V_ℚ] →
            [inst_1 : NormedSpace ℚ V_ℚ] → (N : Submodule ℚ V_ℚ) → [IsClosed (↑N : Set V_ℚ)] → Type u :=
          by
          intro inst_17308629945486154144 inst_10430069231356012391 N inst_13678918037758470810
          exact V_ℚ
        have homogeneous_root_lemma_13_proof_root_canonical_map_aux_completion :
          ∀ (W : Type u) [inst : UniformSpace W] (B : Type u), B = UniformSpace.Completion W :=
          by
          intro W inst_17773356146994793904 B
          have assert_14554108557795752586 : B = UniformSpace.Completion W := by repeat (sorry)
          assumption
        have homogeneous_root_lemma_13_proof_root_canonical_map_define_iota :
          ∀ (W : Type u) [inst : NormedAddCommGroup W] [inst_1 : NormedSpace ℝ W] (B : Type u)
            [inst_2 : NormedAddCommGroup B] [inst_3 : NormedSpace ℝ B] [CompleteSpace B]
            (quotientMap : V_ℚ →ₛₗ[algebraMap ℚ ℝ] W) (canonicalEmbedding : W →ₗ[ℝ] B)
            (iota : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            (⇑iota : V_ℚ → B) = (⇑canonicalEmbedding : W → B) ∘ (⇑quotientMap : V_ℚ → W) :=
          by
          intro W inst_17031976107439155838 inst_15711737349135991557 B inst_5765528929934430422
            inst_9743531509386672818 inst_2394858571444162963 quotientMap canonicalEmbedding iota
          have assert_6873130423278852127 : ∀ (v : V_ℚ), ‖(quotientMap : V_ℚ → W) v‖ = ‖v‖ := by repeat (sorry)
          have assert_13054463097146335766 :
            (⇑iota : V_ℚ → B) = (⇑canonicalEmbedding : W → B) ∘ (⇑quotientMap : V_ℚ → W) := by repeat (sorry)
          assumption
        have homogeneous_root_lemma_13_proof_root_canonical_map_linear :
          ∀ (B : Type u) [instB : NormedAddCommGroup B] [instBR : NormedSpace ℝ B] (ι : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            (∀ (x y : V_ℚ), (ι : V_ℚ → B) (x + y) = (ι : V_ℚ → B) x + (ι : V_ℚ → B) y) ∧
              ∀ (q : ℚ) (x : V_ℚ), (ι : V_ℚ → B) (q • x) = (algebraMap ℚ ℝ : ℚ → ℝ) q • (ι : V_ℚ → B) x :=
          by
          intro B instB instBR ι
          simp only [map_add, implies_true, LinearMap.map_smulₛₗ, Lake.FamilyOut.fam_eq, eq_ratCast, and_self]
        have homogeneous_root_lemma_13_proof_root_canonical_map_norm_preserving :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B), ∀ (v : V_ℚ), ‖(ι : V_ℚ → B) v‖ = ‖v‖ :=
          by
          have assert_5905711319221901201 : ∀ (v : V_ℚ), True := by simp only [implies_true]
          have assert_251672475203705796 : V_ℚ → V_ℚ ⧸ AddCommGroup.torsion V_ℚ :=
            by
            intro v
            exact 0
          have assert_5012992690937513558 : ∀ (w : V_ℚ), ‖(↑w : UniformSpace.Completion V_ℚ)‖ = ‖w‖ := by
            simp only [UniformSpace.Completion.norm_coe, Lake.FamilyOut.fam_eq, implies_true]
          have assert_8361667650125078258 :
            ∀ {B W : Type u} [inst : NormedAddCommGroup B] [inst_1 : NormedAddCommGroup W] (iota : V_ℚ → B)
              (q : V_ℚ → W) (v : V_ℚ), ‖iota v‖ = ‖q v‖ :=
            by repeat (sorry)
          have assert_5905711319221901201 : ∀ (v : V_ℚ), True := by simp only [implies_true]
          have assert_251672475203705796 : V_ℚ → V_ℚ ⧸ AddCommGroup.torsion V_ℚ := by exact assert_251672475203705796
          have assert_10527352187423355698 :
            ∀ {W : Type u} [inst : NormedAddCommGroup W] (q : V_ℚ → W) (v : V_ℚ), ‖q v‖ = ‖v‖ := by repeat (sorry)
          repeat (sorry)
        repeat (sorry)
      repeat (sorry)
    let ⟨B, assert_prop_13927134984261476106⟩ := assert_exists_13927134984261476106
    have verification_13927134984261476106 :
      ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (iota :
        V_ℚ →ₛₗ[algebraMap ℚ ℝ] B), ∀ (v : V_ℚ), ‖(iota : V_ℚ → B) v‖ = ‖v‖ :=
      by
      have homogeneous_root_lemma_13_proof_root_zero_subspace : ∀ (N : Submodule ℚ V_ℚ), True :=
        by
        intro N
        simp only
      skip
      have assert_exists_4477080481389323516 : ?m.4415 :=
        by
        let completionB (V_ℚ : Type u) [inst_17308629945486154144 : NormedAddCommGroup V_ℚ]
          [inst_10430069231356012391 : NormedSpace ℚ V_ℚ] : Type u := UniformSpace.Completion V_ℚ
        use completionB
        have homogeneous_root_lemma_13_proof_root_completion_verification :
          ∃ (W : Type u) (instW : NormedAddCommGroup W) (instWR : NormedSpace ℝ W) (completionB : Type u) (instB :
            NormedAddCommGroup completionB) (instBR : NormedSpace ℝ completionB) (_ : CompleteSpace completionB)
            (toCompletion : W →ₗᵢ[ℝ] completionB),
            completionB = UniformSpace.Completion W ∧ DenseRange (⇑toCompletion : W → completionB) :=
          by
          have assert_8167778515701269216 :
            ∃ (W : Type u) (instW : NormedAddCommGroup W) (instWR : NormedSpace ℝ W) (ι : V_ℚ →ₛₗ[algebraMap ℚ ℝ] W),
              ∀ (v : V_ℚ), ‖(ι : V_ℚ → W) v‖ = ‖v‖ :=
            by repeat (sorry)
          let ⟨W, assert_17614258978110459243⟩ := assert_8167778515701269216
          let ⟨instW, assert_2454908502800025418⟩ := assert_17614258978110459243
          let ⟨instWR, assert_464872097418394381⟩ := assert_2454908502800025418
          let ⟨ι, assert_12539946446919226476⟩ := assert_464872097418394381
          have assert_3382735053617873505 :
            ∃ (W : Type u) (instW : NormedAddCommGroup W) (instWR : NormedSpace ℝ W) (completionB : Type u) (instB :
              NormedAddCommGroup completionB) (instBR : NormedSpace ℝ completionB) (_ : CompleteSpace completionB)
              (toCompletion : W →ₗᵢ[ℝ] completionB),
              completionB = UniformSpace.Completion W ∧ DenseRange (⇑toCompletion : W → completionB) :=
            by repeat (sorry)
          let ⟨W, assert_979022125887221174⟩ := assert_3382735053617873505
          let ⟨instW, assert_11579651289977338526⟩ := assert_979022125887221174
          let ⟨instWR, assert_13295821713315881858⟩ := assert_11579651289977338526
          let ⟨completionB, assert_16851109221607908264⟩ := assert_13295821713315881858
          let ⟨instB, assert_10940152650797352587⟩ := assert_16851109221607908264
          let ⟨instBR, assert_2432729794449034206⟩ := assert_10940152650797352587
          have assert_3382735053617873505 :
            ∃ (W : Type u) (instW : NormedAddCommGroup W) (instWR : NormedSpace ℝ W) (completionB : Type u) (instB :
              NormedAddCommGroup completionB) (instBR : NormedSpace ℝ completionB) (_ : CompleteSpace completionB)
              (toCompletion : W →ₗᵢ[ℝ] completionB),
              completionB = UniformSpace.Completion W ∧ DenseRange (⇑toCompletion : W → completionB) :=
            by repeat (sorry)
          let ⟨W, assert_979022125887221174⟩ := assert_3382735053617873505
          let ⟨instW, assert_11579651289977338526⟩ := assert_979022125887221174
          let ⟨instWR, assert_13295821713315881858⟩ := assert_11579651289977338526
          let ⟨completionB, assert_16851109221607908264⟩ := assert_13295821713315881858
          let ⟨instB, assert_10940152650797352587⟩ := assert_16851109221607908264
          let ⟨instBR, assert_2432729794449034206⟩ := assert_10940152650797352587
          repeat (sorry)
        repeat (sorry)
      let ⟨completionB, assert_prop_4477080481389323516⟩ := assert_exists_4477080481389323516
      have verification_4477080481389323516 : [inst : NormedAddCommGroup V_ℚ] → [NormedSpace ℚ V_ℚ] → Type u :=
        by
        intro inst
        intro inst_1
        exact V_ℚ
      have homogeneous_root_lemma_13_proof_root_extend_rational_operations :
        ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
          V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
          ∃! smul : ℚ → B → B,
            (∀ (q : ℚ) (v : V_ℚ), smul q ((ι : V_ℚ → B) v) = (ι : V_ℚ → B) (q • v)) ∧
              ∀ (q : ℚ) (b : B), smul q b = (↑q : ℝ) • b :=
        by
        have assert_2225540719844248985 : ∃ (B : Type u), B = UniformSpace.Completion V_ℚ := by simp only [↓existsAndEq]
        let ⟨B, assert_10191763767968187191⟩ := assert_2225540719844248985
        have assert_8569515259437923727 :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            ∃! add : B → B → B,
              (∀ (v w : V_ℚ), add ((ι : V_ℚ → B) v) ((ι : V_ℚ → B) w) = (ι : V_ℚ → B) (v + w)) ∧
                Continuous fun (p : B × B) ↦ add p.1 p.2 :=
          by repeat (sorry)
        let ⟨B, assert_1331114331892359126⟩ := assert_8569515259437923727
        let ⟨instB, assert_8448744736133604720⟩ := assert_1331114331892359126
        let ⟨instBR, assert_5444858526617704665⟩ := assert_8448744736133604720
        have assert_2225540719844248985 : ∃ (B : Type u), B = UniformSpace.Completion V_ℚ := by simp only [↓existsAndEq]
        let ⟨B, assert_10191763767968187191⟩ := assert_2225540719844248985
        have assert_11038365720864540514 :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            ∃! negB : B → B,
              Continuous negB ∧ (∀ (v : V_ℚ), negB ((ι : V_ℚ → B) v) = (ι : V_ℚ → B) (-v)) ∧ ∀ (b : B), negB b = -b :=
          by repeat (sorry)
        let ⟨B, assert_12889542835602492664⟩ := assert_11038365720864540514
        let ⟨instB, assert_9968730695680190855⟩ := assert_12889542835602492664
        let ⟨instBR, assert_9638015424297576641⟩ := assert_9968730695680190855
        have assert_2225540719844248985 : ∃ (B : Type u), B = UniformSpace.Completion V_ℚ := by simp only [↓existsAndEq]
        let ⟨B, assert_10191763767968187191⟩ := assert_2225540719844248985
        have assert_18109447674927730719 :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            ∀ (q : ℚ),
              ∃! F : C(B, B),
                (∀ (w : V_ℚ), (F : B → B) ((ι : V_ℚ → B) w) = (ι : V_ℚ → B) (q • w)) ∧
                  ∀ (b : B), (F : B → B) b = (↑q : ℝ) • b :=
          by repeat (sorry)
        let ⟨B, assert_2936693133420940039⟩ := assert_18109447674927730719
        let ⟨instB, assert_9494367333920196357⟩ := assert_2936693133420940039
        let ⟨instBR, assert_17037686226541676967⟩ := assert_9494367333920196357
        have assert_36722636967262386 :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B) (instBQ : NormedSpace ℚ B),
            (∀ (q : ℚ) (v : V_ℚ), q • (ι : V_ℚ → B) v = (ι : V_ℚ → B) (q • v)) ∧
              ∀ (q : ℚ) (b : B), q • b = (↑q : ℝ) • b :=
          by repeat (sorry)
        let ⟨B, assert_16069959711847655489⟩ := assert_36722636967262386
        let ⟨instB, assert_17037067377764125921⟩ := assert_16069959711847655489
        let ⟨instBR, assert_13902569249304312658⟩ := assert_17037067377764125921
        repeat (sorry)
      have assert_exists_9699748590880185229 :
        have homogeneous_root_lemma_13_proof_root_real_scalar_multiplication_auxiliary_sequences :
          ∀ (Q W : Set V_ℚ) (qSeq wSeq : ℕ → V_ℚ) (alpha b : V_ℚ),
            Filter.Tendsto qSeq Filter.atTop (nhds alpha) ∧
              Filter.Tendsto wSeq Filter.atTop (nhds b) ∧ (∀ (n : ℕ), qSeq n ∈ Q) ∧ ∀ (n : ℕ), wSeq n ∈ W :=
          fun (Q W : Set V_ℚ) (qSeq wSeq : ℕ → V_ℚ) (alpha b : V_ℚ) ↦
          have assert_10674727580076540309 : alpha ∈ Set.univ := of_eq_true (_simp_6 alpha);
          have assert_940625861800794480 :
            (∀ (n : ℕ), qSeq n ∈ Q) → Filter.Tendsto qSeq Filter.atTop (nhds alpha) → b ∈ W :=
            sorry `_sorry._@._hyg.16745;
          have assert_6278359807263170299 :
            (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
              (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) →
                (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) :=
            _proof_19 V_ℚ Q W qSeq wSeq alpha b;
          have assert_13547343992138564758 :
            (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
              (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) →
                (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) :=
            of_eq_true
              (Eq.trans
                (implies_congr (Eq.refl ((∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha)))
                  _simp_7)
                (implies_true ((∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha))));
          have assert_17059356330238608001 :
            (∀ (n : ℕ), qSeq n ∈ Q) →
              Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
                (∀ (n : ℕ), wSeq n ∈ W) →
                  Filter.Tendsto wSeq Filter.atTop (nhds b) →
                    Filter.Tendsto qSeq Filter.atTop (nhds alpha) ∧
                      Filter.Tendsto wSeq Filter.atTop (nhds b) ∧ (∀ (n : ℕ), qSeq n ∈ Q) ∧ ∀ (n : ℕ), wSeq n ∈ W :=
            _proof_20 V_ℚ Q W qSeq wSeq alpha b;
          sorry `_sorry._@._hyg.17028;
        ?m.4619 :=
        by
        let scalarMul (V_ℚ : Type u) [inst_17308629945486154144 : NormedAddCommGroup V_ℚ]
          [inst_10430069231356012391 : NormedSpace ℚ V_ℚ] (W : Type u) [NormedAddCommGroup W] [NormedSpace ℚ W]
          [CompleteSpace W] (alpha : ℝ) (b : W) (qSeq : ℕ → ℚ)
          (hqSeq : Filter.Tendsto (fun i : ℕ => (qSeq i : ℝ)) Filter.atTop (nhds alpha)) (wSeq : ℕ → W)
          (hwSeq : Filter.Tendsto wSeq Filter.atTop (nhds b)) : W :=
          Classical.choose
            (show ∃ c : W, Filter.Tendsto (fun i : ℕ => qSeq i • wSeq i) Filter.atTop (nhds c) from by sorry)
        use scalarMul
        have homogeneous_root_lemma_13_proof_root_real_scalar_multiplication_auxiliary_sequences :
          ∀ (Q W : Set V_ℚ) (qSeq wSeq : ℕ → V_ℚ) (alpha b : V_ℚ),
            Filter.Tendsto qSeq Filter.atTop (nhds alpha) ∧
              Filter.Tendsto wSeq Filter.atTop (nhds b) ∧ (∀ (n : ℕ), qSeq n ∈ Q) ∧ ∀ (n : ℕ), wSeq n ∈ W :=
          by
          intro Q W qSeq wSeq alpha b
          have assert_10674727580076540309 : alpha ∈ Set.univ := by simp only [Set.mem_univ]
          have assert_940625861800794480 :
            (∀ (n : ℕ), qSeq n ∈ Q) → Filter.Tendsto qSeq Filter.atTop (nhds alpha) → b ∈ W := by repeat (sorry)
          have assert_6278359807263170299 :
            (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
              (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) →
                (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) :=
            by grind only
          have assert_13547343992138564758 :
            (∀ (n : ℕ), qSeq n ∈ Q) ∧ Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
              (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) →
                (∀ (n : ℕ), wSeq n ∈ W) ∧ Filter.Tendsto wSeq Filter.atTop (nhds b) :=
            by simp only [imp_self, implies_true]
          have assert_17059356330238608001 :
            (∀ (n : ℕ), qSeq n ∈ Q) →
              Filter.Tendsto qSeq Filter.atTop (nhds alpha) →
                (∀ (n : ℕ), wSeq n ∈ W) →
                  Filter.Tendsto wSeq Filter.atTop (nhds b) →
                    Filter.Tendsto qSeq Filter.atTop (nhds alpha) ∧
                      Filter.Tendsto wSeq Filter.atTop (nhds b) ∧ (∀ (n : ℕ), qSeq n ∈ Q) ∧ ∀ (n : ℕ), wSeq n ∈ W :=
            by grind only
          repeat (sorry)
        have homogeneous_root_lemma_13_proof_root_real_scalar_multiplication_cauchy_sequence :
          ∀ (B : Type u) [instB : NormedAddCommGroup B] [instBR : NormedSpace ℝ B] (qSeq : ℕ → ℝ) (wSeq : ℕ → B),
            CauchySeq qSeq → CauchySeq wSeq → CauchySeq fun (i : ℕ) ↦ qSeq i • wSeq i :=
          by
          intro B instB instBR qSeq wSeq a_8952468359706767787 a_6738328230023000844
          have assert_6996291977304024354 : CauchySeq fun (i : ℕ) ↦ qSeq i • wSeq i := by repeat (sorry)
          assumption
        skip
        skip
        repeat (sorry)
      let ⟨scalarMul, assert_prop_9699748590880185229⟩ := assert_exists_9699748590880185229
      have verification_9699748590880185229 :
        ∀ (B : Type u) [instB : NormedAddCommGroup B] [instBR : NormedSpace ℝ B] (ι : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B) (α : ℝ)
          (b : B) (qSeq qSeq' : ℕ → ℚ) (wSeq wSeq' : ℕ → V_ℚ),
          Filter.Tendsto (fun (n : ℕ) ↦ (↑(qSeq n) : ℝ)) Filter.atTop (nhds α) →
            Filter.Tendsto (fun (n : ℕ) ↦ (ι : V_ℚ → B) (wSeq n)) Filter.atTop (nhds b) →
              Filter.Tendsto (fun (n : ℕ) ↦ (↑(qSeq' n) : ℝ)) Filter.atTop (nhds α) →
                Filter.Tendsto (fun (n : ℕ) ↦ (ι : V_ℚ → B) (wSeq' n)) Filter.atTop (nhds b) →
                  Filter.Tendsto (fun (n : ℕ) ↦ (↑(qSeq n) : ℝ) • (ι : V_ℚ → B) (wSeq n)) Filter.atTop (nhds (α • b)) ∧
                    Filter.Tendsto (fun (n : ℕ) ↦ (↑(qSeq' n) : ℝ) • (ι : V_ℚ → B) (wSeq' n)) Filter.atTop
                      (nhds (α • b)) :=
        by
        intro B instB instBR ι α b qSeq qSeq' wSeq wSeq' hq hw hq' hw'
        constructor
        · exact hq.smul hw
        · exact hq'.smul hw'
      have homogeneous_root_lemma_13_proof_root_banach_space_structure :
        ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B), True := by
        exact ⟨PUnit, inferInstance, inferInstance, inferInstance, trivial⟩
      have assert_exists_13927134984261476106 : ?m.4785 :=
        by
        let iota (V_ℚ : Type u) [inst_17308629945486154144 : NormedAddCommGroup V_ℚ]
          [inst_10430069231356012391 : NormedSpace ℚ V_ℚ] (N : Submodule ℚ V_ℚ) (B : Type u) [NormedAddCommGroup B]
          [NormedSpace ℝ B] (toB : (V_ℚ ⧸ N) →ₛₗ[algebraMap ℚ ℝ] B) : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B :=
          toB.comp (Submodule.mkQ N)
        use iota
        have homogeneous_root_lemma_13_proof_root_canonical_map_aux_quotient_space :
          [inst : NormedAddCommGroup V_ℚ] →
            [inst_1 : NormedSpace ℚ V_ℚ] → (N : Submodule ℚ V_ℚ) → [IsClosed (↑N : Set V_ℚ)] → Type u :=
          by
          intro inst_17308629945486154144 inst_10430069231356012391 N inst_13678918037758470810
          exact V_ℚ
        have homogeneous_root_lemma_13_proof_root_canonical_map_aux_completion :
          ∀ (W : Type u) [inst : UniformSpace W] (B : Type u), B = UniformSpace.Completion W :=
          by
          intro W inst_17773356146994793904 B
          have assert_14554108557795752586 : B = UniformSpace.Completion W := by repeat (sorry)
          assumption
        have homogeneous_root_lemma_13_proof_root_canonical_map_define_iota :
          ∀ (W : Type u) [inst : NormedAddCommGroup W] [inst_1 : NormedSpace ℝ W] (B : Type u)
            [inst_2 : NormedAddCommGroup B] [inst_3 : NormedSpace ℝ B] [CompleteSpace B]
            (quotientMap : V_ℚ →ₛₗ[algebraMap ℚ ℝ] W) (canonicalEmbedding : W →ₗ[ℝ] B)
            (iota : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            (⇑iota : V_ℚ → B) = (⇑canonicalEmbedding : W → B) ∘ (⇑quotientMap : V_ℚ → W) :=
          by
          intro W inst_17031976107439155838 inst_15711737349135991557 B inst_5765528929934430422
            inst_9743531509386672818 inst_2394858571444162963 quotientMap canonicalEmbedding iota
          have assert_6873130423278852127 : ∀ (v : V_ℚ), ‖(quotientMap : V_ℚ → W) v‖ = ‖v‖ := by repeat (sorry)
          have assert_13054463097146335766 :
            (⇑iota : V_ℚ → B) = (⇑canonicalEmbedding : W → B) ∘ (⇑quotientMap : V_ℚ → W) := by repeat (sorry)
          assumption
        have homogeneous_root_lemma_13_proof_root_canonical_map_linear :
          ∀ (B : Type u) [instB : NormedAddCommGroup B] [instBR : NormedSpace ℝ B] (ι : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            (∀ (x y : V_ℚ), (ι : V_ℚ → B) (x + y) = (ι : V_ℚ → B) x + (ι : V_ℚ → B) y) ∧
              ∀ (q : ℚ) (x : V_ℚ), (ι : V_ℚ → B) (q • x) = (algebraMap ℚ ℝ : ℚ → ℝ) q • (ι : V_ℚ → B) x :=
          by
          intro B instB instBR ι
          simp only [map_add, implies_true, LinearMap.map_smulₛₗ, Lake.FamilyOut.fam_eq, eq_ratCast, and_self]
        have homogeneous_root_lemma_13_proof_root_canonical_map_norm_preserving :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B), ∀ (v : V_ℚ), ‖(ι : V_ℚ → B) v‖ = ‖v‖ :=
          by
          have assert_5905711319221901201 : ∀ (v : V_ℚ), True := by simp only [implies_true]
          have assert_251672475203705796 : V_ℚ → V_ℚ ⧸ AddCommGroup.torsion V_ℚ :=
            by
            intro v
            exact 0
          have assert_5012992690937513558 : ∀ (w : V_ℚ), ‖(↑w : UniformSpace.Completion V_ℚ)‖ = ‖w‖ := by
            simp only [UniformSpace.Completion.norm_coe, Lake.FamilyOut.fam_eq, implies_true]
          have assert_8361667650125078258 :
            ∀ {B W : Type u} [inst : NormedAddCommGroup B] [inst_1 : NormedAddCommGroup W] (iota : V_ℚ → B)
              (q : V_ℚ → W) (v : V_ℚ), ‖iota v‖ = ‖q v‖ :=
            by repeat (sorry)
          have assert_5905711319221901201 : ∀ (v : V_ℚ), True := by simp only [implies_true]
          have assert_251672475203705796 : V_ℚ → V_ℚ ⧸ AddCommGroup.torsion V_ℚ := by exact assert_251672475203705796
          have assert_10527352187423355698 :
            ∀ {W : Type u} [inst : NormedAddCommGroup W] (q : V_ℚ → W) (v : V_ℚ), ‖q v‖ = ‖v‖ := by repeat (sorry)
          repeat (sorry)
        repeat (sorry)
      let ⟨iota, assert_prop_13927134984261476106⟩ := assert_exists_13927134984261476106
      have verification_13927134984261476106 :
        ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
          V_ℚ →ₛₗ[algebraMap ℚ ℝ] B), ∀ (v : V_ℚ), ‖(ι : V_ℚ → B) v‖ = ‖v‖ :=
        by
        have homogeneous_root_lemma_13_proof_root_canonical_map_aux_quotient_space :
          [inst : NormedAddCommGroup V_ℚ] →
            [inst_1 : NormedSpace ℚ V_ℚ] → (N : Submodule ℚ V_ℚ) → [IsClosed (↑N : Set V_ℚ)] → Type u :=
          by
          intro inst_17308629945486154144 inst_10430069231356012391 N inst_13678918037758470810
          exact V_ℚ
        have homogeneous_root_lemma_13_proof_root_canonical_map_aux_completion :
          ∀ (W : Type u) [inst : UniformSpace W] (B : Type u), B = UniformSpace.Completion W :=
          by
          intro W inst_17773356146994793904 B
          have assert_14554108557795752586 : B = UniformSpace.Completion W := by repeat (sorry)
          assumption
        have homogeneous_root_lemma_13_proof_root_canonical_map_define_iota :
          ∀ (W : Type u) [inst : NormedAddCommGroup W] [inst_1 : NormedSpace ℝ W] (B : Type u)
            [inst_2 : NormedAddCommGroup B] [inst_3 : NormedSpace ℝ B] [CompleteSpace B]
            (quotientMap : V_ℚ →ₛₗ[algebraMap ℚ ℝ] W) (canonicalEmbedding : W →ₗ[ℝ] B)
            (iota : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            (⇑iota : V_ℚ → B) = (⇑canonicalEmbedding : W → B) ∘ (⇑quotientMap : V_ℚ → W) :=
          by
          intro W inst_17031976107439155838 inst_15711737349135991557 B inst_5765528929934430422
            inst_9743531509386672818 inst_2394858571444162963 quotientMap canonicalEmbedding iota
          have assert_6873130423278852127 : ∀ (v : V_ℚ), ‖(quotientMap : V_ℚ → W) v‖ = ‖v‖ := by repeat (sorry)
          have assert_13054463097146335766 :
            (⇑iota : V_ℚ → B) = (⇑canonicalEmbedding : W → B) ∘ (⇑quotientMap : V_ℚ → W) := by repeat (sorry)
          assumption
        have homogeneous_root_lemma_13_proof_root_canonical_map_linear :
          ∀ (B : Type u) [instB : NormedAddCommGroup B] [instBR : NormedSpace ℝ B] (ι : V_ℚ →ₛₗ[algebraMap ℚ ℝ] B),
            (∀ (x y : V_ℚ), (ι : V_ℚ → B) (x + y) = (ι : V_ℚ → B) x + (ι : V_ℚ → B) y) ∧
              ∀ (q : ℚ) (x : V_ℚ), (ι : V_ℚ → B) (q • x) = (algebraMap ℚ ℝ : ℚ → ℝ) q • (ι : V_ℚ → B) x :=
          by
          intro B instB instBR ι
          simp only [map_add, implies_true, LinearMap.map_smulₛₗ, Lake.FamilyOut.fam_eq, eq_ratCast, and_self]
        have homogeneous_root_lemma_13_proof_root_canonical_map_norm_preserving :
          ∃ (B : Type u) (instB : NormedAddCommGroup B) (instBR : NormedSpace ℝ B) (_ : CompleteSpace B) (ι :
            V_ℚ →ₛₗ[algebraMap ℚ ℝ] B), ∀ (v : V_ℚ), ‖(ι : V_ℚ → B) v‖ = ‖v‖ :=
          by
          have assert_5905711319221901201 : ∀ (v : V_ℚ), True := by simp only [implies_true]
          have assert_251672475203705796 : V_ℚ → V_ℚ ⧸ AddCommGroup.torsion V_ℚ :=
            by
            intro v
            exact 0
          have assert_5012992690937513558 : ∀ (w : V_ℚ), ‖(↑w : UniformSpace.Completion V_ℚ)‖ = ‖w‖ := by
            simp only [UniformSpace.Completion.norm_coe, Lake.FamilyOut.fam_eq, implies_true]
          have assert_8361667650125078258 :
            ∀ {B W : Type u} [inst : NormedAddCommGroup B] [inst_1 : NormedAddCommGroup W] (iota : V_ℚ → B)
              (q : V_ℚ → W) (v : V_ℚ), ‖iota v‖ = ‖q v‖ :=
            by repeat (sorry)
          have assert_5905711319221901201 : ∀ (v : V_ℚ), True := by simp only [implies_true]
          have assert_251672475203705796 : V_ℚ → V_ℚ ⧸ AddCommGroup.torsion V_ℚ := by exact assert_251672475203705796
          have assert_10527352187423355698 :
            ∀ {W : Type u} [inst : NormedAddCommGroup W] (q : V_ℚ → W) (v : V_ℚ), ‖q v‖ = ‖v‖ := by repeat (sorry)
          repeat (sorry)
        repeat (sorry)
      repeat (sorry)
  #eval "command skipped due to error in processing source"
  #eval "command skipped due to error in processing source"


/-!
## Elaboration results 


Declarations (15): IsPseudoLengthFunction, isLength_of_pos_of_ne_one, is_homogeneous_pseudo_length_sq, AddCommGroup.TorsionFree, lemma_1, lemma_2, lemma_3, lemma_4, lemma_5, lemma_6, proposition_7, lemma_8, lemma_9, lemma_10, lemma_13

Elaboration logs (29):
1. "Obtained definition" : String
2. type of theorem `isLength_of_pos_of_ne_one` is not a proposition
     {G : Type u} → [Group G] → (G → ℝ) → Prop
3. type of theorem `is_homogeneous_pseudo_length_sq` is not a proposition
     {G : Type u} → [Group G] → (G → ℝ) → Prop
4. "commutatorElement has type {G : Type u_1} → [Group G] → Bracket G G with value `fun {G : Type u_1} [Group G] ↦ { bracket := fun (g₁ g₂ : G) ↦ g₁ * g₂ * g₁⁻¹ * g₂⁻¹ }`" : String
5. "commutator has type (G : Type u_1) → [inst : Group G] → Subgroup G with value `fun (G : Type u_1) [Group G] ↦ ⁅⊤, ⊤⁆`" : String
6. "Abelianization has type (G : Type u) → [Group G] → Type u with value `fun (G : Type u) [Group G] ↦ G ⧸ commutator G`" : String
7. "AddCommGroup.torsion has type (G : Type u_1) → [inst : AddCommGroup G] → AddSubgroup G with value `fun (G : Type u_1) [inst : AddCommGroup G] ↦\n  let __src : AddSubmonoid G := AddCommMonoid.addTorsion G;\n  { toAddSubmonoid := __src, neg_mem' := @AddCommGroup.torsion._proof_1 G inst }`" : String
8. "Obtained definition" : String
9. Try `simp at h` instead of `simpa using h`
   
   Note: This linter can be disabled with `set_option linter.unnecessarySimpa false`
10. declaration uses `sorry`
11. Try this: intro inst' l' x' y' n' hn'
12. declaration uses `sorry`
13. declaration uses `sorry`
14. declaration uses `sorry`
15. declaration uses `sorry`
16. Try `simp at h` instead of `simpa using h`
   
   Note: This linter can be disabled with `set_option linter.unnecessarySimpa false`
17. declaration uses `sorry`
18. declaration uses `sorry`
19. declaration uses `sorry`
20. declaration uses `sorry`
21. declaration uses `sorry`
22. "command skipped due to error in processing source"
23. "command skipped due to error in processing source"
24. expected ';' or line break
25. Invalid projection: Type of
     ?m
   is not known; cannot resolve projection `3797`
26. No goals to be solved
27. unsolved goals
   V_ℚ : Type u
   inst_17308629945486154144 : NormedAddCommGroup V_ℚ
   inst_10430069231356012391 : NormedSpace ℚ V_ℚ
   assert_exists_13927134984261476106 :
     have homogeneous_root_lemma_13_proof_root_zero_subspace := ⋯;
     sorry
   ⊢ ∃ B instB instBR, ∃ (_ : CompleteSpace B), ∃ ι, ∀ (v : V_ℚ), ‖ι v‖ = ‖v‖
28. "command skipped due to error in processing source"
29. "command skipped due to error in processing source"

Sorries (31 goals):
1. lemma_1
   ∀ {G : Type u} [inst_14157295161945824867 : Group G] (l : G → ℝ) (x y : G),
     have assert_15969908638720860817 := ⋯;
     ∀ [inst : Group G] (l : G → ℝ) (x y : G) (n : ℤ), 0 < n → ↑n * l (y * x * y⁻¹) = l ((y * x * y⁻¹) ^ n)

2. lemma_1
   ∀ {G : Type u} [inst_14157295161945824867 : Group G] (l : G → ℝ) (x y : G), l (y * x * y⁻¹) ≤ l x

3. lemma_2
   ∀ {G : Type u} [inst_14157295161945824867 : Group G] (l : G → ℝ) (C : ℕ → G) (s t y z : G) (n n : ℕ), n = 0

4. lemma_2
   ∀ {G : Type u} [inst_14157295161945824867 : Group G] (l : G → ℝ) (C : ℕ → G) (s t y z : G) (n n : ℕ),
     l (C n) ≤ l s⁻¹ + l t + ↑n * (l y + l z) →
       have assert_7625206550276090944 := ⋯;
       have assert_3234633238085050664 := @lemma_2._proof_2 G inst_14157295161945824867 C y z;
       have assert_6741213643820078969 := ⋯;
       have assert_5253138843730466092 := ⋯;
       let assert_5253138843730466092 := ⋯;
       have assert_346742309959553248 := ⋯;
       have assert_3730832634776002826 := ⋯;
       l (y * C n * z) ≤ l y + l (C n) + l z

5. lemma_2
   ∀ {G : Type u} [inst_14157295161945824867 : Group G] (l : G → ℝ) (C : ℕ → G) (s t y z : G) (n n : ℕ),
     l (C n) ≤ l s⁻¹ + l t + ↑n * (l y + l z) →
       have assert_7625206550276090944 := ⋯;
       have assert_3234633238085050664 := @lemma_2._proof_2 G inst_14157295161945824867 C y z;
       have assert_6741213643820078969 := ⋯;
       ∀ [inst : Group G] (l : G → ℝ) (C : ℕ → G) (s t y z w : G) (n : ℕ), C (n + 1) = w * (y * C n * z) * w⁻¹

6. lemma_2
   ∀ {G : Type u} [inst_14157295161945824867 : Group G] (l : G → ℝ) (C : ℕ → G) (s t y z : G) (n n : ℕ),
     l (C n) ≤ l s⁻¹ + l t + ↑n * (l y + l z) → ∀ (w : G) (n : ℕ), C (n + 1) = w * y * C n * z * w⁻¹

7. lemma_3
   ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (a y z : G),
     have assert_11071143152619725945 := ⋯;
     have assert_11732381117505769004 := ⋯;
     have assert_14203344460445373524 := ⋯;
     have assert_2134792818996660072 := ⋯;
     let assert_2134792818996660072 := ⋯;
     have assert_15919629309819544986 := ⋯;
     have assert_9141421788251764031 := ⋯;
     have assert_16390130277208744366 := ⋯;
     ∀ (s t w : G) (n : ℕ),
       0 < n →
         l (a ^ (2 * n)) ≤ l s + l ((w * y) ^ n * s⁻¹ * t * (z * w⁻¹) ^ n) + l t⁻¹ ∧
           l s + l ((w * y) ^ n * s⁻¹ * t * (z * w⁻¹) ^ n) + l t⁻¹ ≤ l s + l s⁻¹ + l t + ↑n * (l y + l z) + l t⁻¹

8. lemma_3
   ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (a y z : G),
     have assert_11071143152619725945 := ⋯;
     have assert_11732381117505769004 := ⋯;
     have assert_14203344460445373524 := ⋯;
     have assert_2134792818996660072 := ⋯;
     let assert_2134792818996660072 := ⋯;
     have assert_15919629309819544986 := ⋯;
     ∀ (n : ℕ), 0 < n → ↑(2 * n) * l a = l (a ^ (2 * n))

9. lemma_3
   ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (a y z : G),
     have assert_11071143152619725945 := ⋯;
     have assert_11732381117505769004 := ⋯;
     have assert_14203344460445373524 := ⋯;
     ∀ (t w : G) (n : ℕ), 0 < n → a ^ n = t * (z * w⁻¹) ^ n * t⁻¹

10. lemma_3
   ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (a y z w : G) (n : ℕ),
     0 < n → IsConj a (w * y) → IsConj a (z * w⁻¹) → l a ≤ (l y + l z) / 2

11. lemma_4
   ∀ (f : ℤ → ℤ → ℝ) (m k : ℤ),
     have assert_13400897509976910969 := ⋯;
     have assert_1186231502201441818 := ⋯;
     have assert_15719295443976895812 := ⋯;
     have assert_9605933496017345445 := ⋯;
     have assert_9056652962045054221 := ⋯;
     have assert_562637650220487623 := ⋯;
     have assert_5222210804259102002 := ⋯;
     have assert_5150742391222492188 := ⋯;
     have assert_5067120391774133738 := ⋯;
     have assert_10238420279409073377 := ⋯;
     f m k ≤ (f (m - 1) k + f (m + 1) (k - 1)) / 2

12. lemma_4
   ∀ (f : ℤ → ℤ → ℝ) (m k : ℤ),
     have assert_13400897509976910969 := ⋯;
     have assert_1186231502201441818 := ⋯;
     have assert_15719295443976895812 := ⋯;
     have assert_9605933496017345445 := ⋯;
     have assert_9056652962045054221 := ⋯;
     have assert_562637650220487623 := ⋯;
     ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (f : ℤ → ℤ → ℝ) (x c y : G) (m k : ℤ),
       have a := x ^ m * c ^ k;
       have w := x;
       have u := x ^ (m - 1) * c ^ k;
       have v := y⁻¹ * x ^ m * c ^ (k - 1) * x * y;
       l u = f (m - 1) k

13. lemma_4
   ∀ (f : ℤ → ℤ → ℝ) (m k : ℤ),
     have assert_13400897509976910969 := ⋯;
     have assert_1186231502201441818 := ⋯;
     have assert_15719295443976895812 := ⋯;
     have assert_9605933496017345445 := ⋯;
     ∀ {G : Type u} [inst : Group G] (f : ℤ → ℤ → ℝ) (m k : ℤ) (x c y : G),
       have a := x ^ m * c ^ k;
       have w := x;
       have u := x ^ (m - 1) * c ^ k;
       have v := y⁻¹ * x ^ m * c ^ (k - 1) * x * y;
       a = y * (v * w⁻¹) * y⁻¹

14. lemma_4
   ∀ (f : ℤ → ℤ → ℝ) (m k : ℤ),
     have assert_13400897509976910969 := ⋯;
     have assert_1186231502201441818 := ⋯;
     ∀ {G : Type u} [inst : Group G] (f : ℤ → ℤ → ℝ) (m k : ℤ) (x y c : G), x * y * x⁻¹ = c * y

15. lemma_4
   ∀ (f : ℤ → ℤ → ℝ) (m k : ℤ) {G : Type u} [inst : Group G] (f : ℤ → ℤ → ℝ) (m k : ℤ) (x c y : G),
     have a := x ^ m * c ^ k;
     have w := x;
     have u := x ^ (m - 1) * c ^ k;
     have v := y⁻¹ * x ^ m * c ^ (k - 1) * x * y;
     IsConj a (w * u)

16. lemma_5
   ∀ {Ω : Type u} [inst_14546896174491015166 : MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
     [inst_787293689400509884 : MeasureTheory.IsProbabilityMeasure μ] (f : ℤ → ℤ → ℝ) (S2n : Ω → ℤ) (n : ℕ),
     have assert_4026131150064946709 := ⋯;
     have assert_10442942852797328330 := ⋯;
     f 0 ↑n ≤ ∫ (ω : Ω), f (S2n ω) (-S2n ω / 2) ∂μ

17. lemma_5
   ∀ {Ω : Type u} [inst_14546896174491015166 : MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
     [inst_787293689400509884 : MeasureTheory.IsProbabilityMeasure μ] (f : ℤ → ℤ → ℝ) (S2n : Ω → ℤ) (n : ℕ),
     have assert_4026131150064946709 := ⋯;
     ∀ (eps : Ω → ℤ) (m k : ℤ),
       MeasureTheory.Measure.map eps μ =
           (1 / 2) • MeasureTheory.Measure.dirac (-1) + (1 / 2) • MeasureTheory.Measure.dirac 1 →
         f m k ≤ ∫ (ω : Ω), f (m + eps ω) (k - (1 + eps ω) / 2) ∂μ

18. lemma_5
   ∀ {Ω : Type u} [inst_14546896174491015166 : MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
     [inst_787293689400509884 : MeasureTheory.IsProbabilityMeasure μ] (f : ℤ → ℤ → ℝ) (S2n : Ω → ℤ) (n : ℕ) (m k : ℤ),
     f m k ≤ 1 / 2 * f (m - 1) k + 1 / 2 * f (m + 1) (k - 1)

19. lemma_6
   ∀ {Ω : Type u} [inst : MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
     [inst_787293689400509884 : MeasureTheory.IsProbabilityMeasure μ] (S2n : Ω → ℤ) (n : ℕ),
     have assert_7175087238707096681 := ⋯;
     ∀ (eps : ℕ → Ω → ℤ) (i : ℕ), ∫ (ω : Ω), ↑(eps i ω) ∂μ = 0 ∧ ∫ (ω : Ω), ↑(eps i ω) ^ 2 ∂μ = 1

20. lemma_6
   ∀ {Ω : Type u} [inst : MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
     [inst_787293689400509884 : MeasureTheory.IsProbabilityMeasure μ] (S2n : Ω → ℤ) (n : ℕ),
     ∫ (ω : Ω), |↑(S2n ω)| ∂μ = ∫ (ω : Ω), √(↑(S2n ω) ^ 2) ∂μ ∧
       ∫ (ω : Ω), √(↑(S2n ω) ^ 2) ∂μ ≤ √(∫ (ω : Ω), ↑(S2n ω) ^ 2 ∂μ)

21. proposition_7
   ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (x y : G),
     have assert_15684868734458400226 := ⋯;
     ∀ (n : ℕ),
       0 < n →
         have c := ⁅x, y⁆;
         ↑n * l c = l (c ^ n)

22. proposition_7
   ∀ {G : Type u} [inst : Group G] (l : G → ℝ) (x y c : G) (n : ℕ), 0 < n → c = ⁅x, y⁆ → l c = 0

23. lemma_8
   ∀ {G : Type u} [inst : Group G] (l : G → ℝ), ∀ g ∈ commutator G, l g = 0

24. lemma_9
   ∀ {G : Type u} [inst : Group G] (l : G → ℝ),
     have assert_13477353947708923796 := @lemma_9._proof_1 G inst l;
     have assert_6104951183198706693 := ⋯;
     have assert_3298551401783107782 := @lemma_9._proof_2 G inst l;
     have assert_13534652505183852006 := ⋯;
     let assert_13534652505183852006 := ⋯;
     have assert_4892422993882007748 := ⋯;
     let assert_4892422993882007748 := ⋯;
     have assert_18397124325701840180 := @lemma_9._proof_3 G inst l assert_13534652505183852006;
     have assert_18397124325701840180 := @lemma_9._proof_3 G inst l assert_13534652505183852006;
     have assert_5769985527489238020 := @lemma_9._proof_4 G inst l assert_13534652505183852006;
     have assert_7599503226116730120 := @lemma_9._proof_5 G inst l;
     have assert_98054474247315716 := ⋯;
     have assert_9552741430207369861 := ⋯;
     ∀ (barL : Abelianization G → ℝ)
       (assert_6994046987373620254 :
         (∀ (g : G), barL (Abelianization.of g) = l g) ∧
           ∀ (barL' : Abelianization G → ℝ), (∀ (g : G), barL' (Abelianization.of g) = l g) → barL' = barL),
       have assert_16102250256638150305 := @lemma_9._proof_6 G inst l barL assert_6994046987373620254;
       have assert_12502756021439128837 :=
         @lemma_9._proof_7 G inst l assert_13534652505183852006 barL assert_6994046987373620254;
       have assert_17518225566479460417 := @lemma_9._proof_4 G inst l assert_13534652505183852006 barL;
       (∀ (g : G), barL (Abelianization.of g) = l g) →
         (∀ {g h : G}, Abelianization.of g = Abelianization.of h → l g = l h) →
           (∀ (g h : G), l (g * h) ≤ l g + l h) → ∀ (a b : Abelianization G), barL (a * b) ≤ barL a + barL b

25. lemma_9
   ∀ {G : Type u} [inst : Group G] (l : G → ℝ),
     have assert_13477353947708923796 := @lemma_9._proof_1 G inst l;
     have assert_6104951183198706693 := ⋯;
     have assert_3298551401783107782 := @lemma_9._proof_2 G inst l;
     have assert_13534652505183852006 := ⋯;
     let assert_13534652505183852006 := ⋯;
     have assert_4892422993882007748 := ⋯;
     let assert_4892422993882007748 := ⋯;
     have assert_18397124325701840180 := @lemma_9._proof_3 G inst l assert_13534652505183852006;
     have assert_18397124325701840180 := @lemma_9._proof_3 G inst l assert_13534652505183852006;
     have assert_5769985527489238020 := @lemma_9._proof_4 G inst l assert_13534652505183852006;
     have assert_7599503226116730120 := @lemma_9._proof_5 G inst l;
     have assert_98054474247315716 := ⋯;
     ∃ barL,
       (∀ (g : G), barL (Abelianization.of g) = l g) ∧
         ∀ (barL' : Abelianization G → ℝ), (∀ (g : G), barL' (Abelianization.of g) = l g) → barL' = barL

26. lemma_9
   ∀ {G : Type u} [inst : Group G] (l : G → ℝ),
     have assert_13477353947708923796 := @lemma_9._proof_1 G inst l;
     have assert_6104951183198706693 := ⋯;
     have assert_3298551401783107782 := @lemma_9._proof_2 G inst l;
     ∀ {g h : G}, Abelianization.of g = Abelianization.of h → l h ≤ l g

27. lemma_9
   ∀ {G : Type u} [inst : Group G] (l : G → ℝ),
     have assert_13477353947708923796 := @lemma_9._proof_1 G inst l;
     ∀ (g h : G), Abelianization.of g = Abelianization.of h → l (h⁻¹ * g) = 0 → l g = l h

28. lemma_10
   ∀ {A : Type u} [inst : AddCommGroup A] (p : A → ℝ),
     ∀ a ∈ AddCommGroup.torsion A,
       have assert_896210975015776397 := ⋯;
       let assert_896210975015776397 := ⋯;
       have assert_10202410548581856519 := @lemma_10._proof_1 A inst p a assert_896210975015776397;
       have assert_896210975015776397_1 := @lemma_10._proof_2 A inst p a assert_896210975015776397;
       let assert_896210975015776397 := @lemma_10._proof_2 A inst p a assert_896210975015776397;
       have assert_2651815816338118712 := ⋯;
       p a = 0

29. lemma_10
   ∀ {A : Type u} [inst : AddCommGroup A] (p : A → ℝ), ∀ a ∈ AddCommGroup.torsion A, ∀ (n : ℕ), n ≠ 0 → n • a = 0 → p a = 0

30. lemma_13
   ∀ (V_ℚ : Type u) [inst_17308629945486154144 : NormedAddCommGroup V_ℚ] [inst_10430069231356012391 : NormedSpace ℚ V_ℚ],
     have assert_exists_13927134984261476106 := ⋯;
     ∃ B instB instBR, ∃ (_ : CompleteSpace B), ∃ ι, ∀ (v : V_ℚ), ‖ι v‖ = ‖v‖

31. lemma_13
   ∀ (V_ℚ : Type u) [inst_17308629945486154144 : NormedAddCommGroup V_ℚ] [inst_10430069231356012391 : NormedSpace ℚ V_ℚ],
     have homogeneous_root_lemma_13_proof_root_zero_subspace := ⋯;
     sorry

Sorries after purge: none


-/

