import Mathlib
universe u v w u_1 u_2 u_3 u_4 u_5 u_6 u_7 u_8 u_9 u_10 u₁ u₂ u₃
set_option maxHeartbeats 10000000
set_option linter.unreachableTactic false
open scoped Nat

-- Generated by codegen.lean from mathdoc_agent/examples/context_prelude/local_context_and_prelude.json

  def IsToyPseudoLength {G : Type u} [Group G] (l : G → ℝ) : Prop :=
    l 1 = 0
  def IsToyLength {G : Type u} [Group G] (l : G → ℝ) : Prop :=
    IsToyPseudoLength l ∧ ∀ g : G, l g = 0 → g = 1
  theorem toy_length_zero_at_one :
      ∀ {G : Type u} [inst : Group G] (l : G → ℝ), IsToyLength l → (∀ (g : G), l g = (0 : ℝ)) → l (1 : G) = (0 : ℝ) :=
    by
    intro G inst_14157295161945824867 l a_1246391707853623537 a_2394298732985391523
    grind only [#73ac]


/-!
## Elaboration results 


Declarations (3): IsToyPseudoLength, IsToyLength, toy_length_zero_at_one

Elaboration logs: none

Sorries: none

Sorries after purge: none


-/

