#check ContinuousLinearMap.adjointAux_inner_left
#check LocalizedModule.divBy.proof_3
#check MeasureTheory.withDensitySMulLI.proof_5
#check SignType.instCommGroupWithZeroSignType.proof_13
#check LinearMap.mkContinuousOfExistsBound₂.proof_4
#check isAdjointPair_toLinearMap₂'
#check AlgebraicTopology.DoldKan.Γ₂_map_f_app
#check latToBddLatCatForgetAdjunction.proof_5
#check HomologicalComplex.single.proof_5
#check stereographic.proof_8
#check LinearMap.toMatrix₂_compl₁₂
#check CategoryTheory.Limits.kernelOrderHom.proof_4
#check continuousMultilinearCurryRightEquiv_apply
#check IsAdjoinRoot.lift.proof_4
#check IccRightChart.proof_10
#check ContinuousLinearEquiv.unitsEquivAut.proof_9
#check MeasureTheory.L1.setToL1_nonneg
#check AlgebraicClosure.toStepOfLE.proof_4
#check CategoryTheory.Limits.Types.binaryProductFunctor.proof_5
#check CategoryTheory.Monoidal.functorHasLeftDual.proof_6
#check Cardinal.commSemiring.proof_7
#check CategoryTheory.Limits.combineCones.proof_4
#check SmoothVectorBundle.pullback.proof_1
#check Homotopy.mkInductive.proof_1
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_4
#check SmoothMap.group.proof_7
#check LinearIsometry.map_orthogonalProjection'
#check Subgroup.instMulActionQuotientDiffToMonoidToDivInvMonoid.proof_2
#check Polynomial.derivative.proof_2
#check AffineSubspace.directionOfNonempty.proof_3
#check Function.Injective.orderedSemiring.proof_2
#check ContinuousLinearMap.map_zero₂
#check HilbertBasis.hasSum_orthogonalProjection
#check ContinuousMultilinearMap.alternatization.proof_5
#check Filter.Realizer.bind.proof_5
#check ContinuousLinearEquiv.comp_differentiableWithinAt_iff
#check TopCat.GlueData.ofOpenSubsets.proof_6
#check CochainComplex.fromSingle₀Equiv.proof_3
#check SmoothMap.semiring.proof_18
#check CategoryTheory.Limits.HasLimitOfHasProductsOfHasEqualizers.buildIsLimit.proof_3
#check ModuleCat.monModuleEquivalenceAlgebra.proof_11
#check LocalHomeomorph.MDifferentiable.mfderiv.proof_3
#check GradedRing.projZeroRingHom.proof_4
#check Real.commRing.proof_14
#check CategoryTheory.instFullAlgebraEilenbergMooreToMonadFreeForgetAdjComparison.proof_2
#check Real.commRing.proof_10
#check CategoryTheory.instBicategoryMonoidalSingleObj.proof_4
#check CommRingCat.Colimits.instCommRingColimitType.proof_8
#check LieModule.maxTrivHom.proof_3
#check ContinuousLinearMap.flipMultilinear.proof_6
#check Ideal.Quotient.field.proof_28
#check SimplicialObject.instCategorySplit.proof_5
#check ContinuousLinearMap.analyticAt_bilinear
#check ValuationRing.instLinearOrderValueGroup.proof_6
#check MeasureTheory.condexpInd_smul'
#check IntermediateField.Lifts.upperBoundAlgHom.proof_4
#check Action.leftRegularTensorIso.proof_3
#check ContinuousLinearMap.op_norm_le_of_shell
#check CategoryTheory.instCategoryComonad.proof_8
#check DFinsupp.lsum.proof_7
#check CategoryTheory.functorCategoryPreadditive.proof_19
#check Zsqrtd.commRing.proof_13
#check CategoryTheory.MonoidalFunctor.mapAction.proof_10
#check CategoryTheory.Limits.Cocones.functoriality.proof_3
#check ZMod.instFieldZMod.proof_79
#check CategoryTheory.Comma.coneOfPreservesIsLimit.proof_2
#check IsPrimitiveRoot.zmodEquivZpowers.proof_4
#check iteratedFDeriv_succ_eq_comp_right
#check Types.monoOverEquivalenceSet.proof_11
#check AlgebraicGeometry.sectionInBasicOpen.proof_7
#check CategoryTheory.LaxMonoidalFunctor.mapMon.proof_7
#check LocalHomeomorph.MDifferentiable.range_mfderiv_eq_top
#check CategoryTheory.Discrete.monoidalFunctor.proof_10
#check IntermediateField.Lifts.upperBoundAlgHom.proof_3
#check ContinuousMultilinearMap.compContinuousLinearMapEquivL.proof_6
#check StarAlgEquiv.restrictScalars.proof_9
#check ContinuousLinearEquiv.compContinuousMultilinearMapL.proof_18
#check ContinuousLinearMap.continuous₂
#check CategoryTheory.effectiveEpiFamilyStructOfIsColimit.proof_3
#check StarAlgHom.ext_topologicalClosure
#check CategoryTheory.Functor.flip.proof_5
#check CategoryTheory.Monoidal.CommMonFunctorCategoryEquivalence.counitIso.proof_7
#check CategoryTheory.hasShiftMk.proof_8
#check DoubleQuot.quotQuotEquivCommₐ.proof_1
#check LieAlgebra.coe_rootSpaceWeightSpaceProduct_tmul
#check CategoryTheory.OplaxFunctor.mk.inj
#check TopCat.Presheaf.SheafConditionPairwiseIntersections.isLimitSheafConditionForkOfIsLimitMapCone.proof_3
#check FormalMultilinearSeries.compContinuousLinearMap_applyComposition
#check ContMDiff.clm_postcomp
#check UniqueMDiffOn.image_denseRange'
#check CategoryTheory.Idempotents.instAddCommGroupHom.proof_5
#check FreeAbelianGroup.liftMonoid.proof_6
#check ContMDiffMap.comp_apply
#check CategoryTheory.Triangulated.Octahedron.mk.inj
#check ContinuousLinearEquiv.summable
#check CategoryTheory.Limits.Types.binaryProductFunctor.proof_4
#check ModuleCat.MonModuleEquivalenceAlgebra.Ring_of_Mon_.proof_8
#check Ideal.selfBasis.proof_3
#check ContMDiffWithinAt.change_section_trivialization
#check Trivialization.continuousLinearMap_apply
