import Mathlib
#check mem_smoothFiberwiseLinear_iff
#check DoubleCentralizer.instStarAddMonoid.proof_2
#check LinearMap.smulRightₗ.proof_8
#check HasStrictFDerivAt.mem_implicitToLocalHomeomorphOfComplemented_source
#check CategoryTheory.Endofunctor.Coalgebra.functorOfNatTrans.proof_3
#check StarAlgHom.coe_codRestrict
#check isAdjointPair_toLinearMap₂
#check HasFDerivAt.clm_comp
#check ZMod.commRing.proof_15
#check latToBddLatCatForgetAdjunction.proof_6
#check CochainComplex.augmentTruncate.proof_6
#check SmoothMap.ring.proof_26
#check CategoryTheory.Pretriangulated.invRotCompRot.proof_4
#check orthogonalProjection_map_apply
#check Real.commRing.proof_22
#check ContinuousLinearEquiv.arrowCongrSL_toLinearEquiv_symm_apply
#check ContinuousLinearMap.map_neg₂
#check RingHom.RespectsIso.ofRestrict_morphismRestrict_iff
#check Orthonormal.exists_hilbertBasis_extension
#check LinearMap.quotientInfEquivSupQuotient_symm_apply_eq_zero_iff
#check CategoryTheory.Limits.pullbackDiagonalMapIso.proof_12
#check ValuationSubring.linearOrderOverring.proof_13
#check BddAbove.convolutionExistsAt'
#check CategoryTheory.Idempotents.KaroubiKaroubi.counitIso.proof_7
#check AlgebraicGeometry.LocallyRingedSpace.IsOpenImmersion.pullbackConeOfLeftIsLimit.proof_3
#check CategoryTheory.Adjunction.coconesIso.proof_3
#check Trivialization.apply_eq_prod_continuousLinearEquivAt
#check DoubleCentralizer.coeHom.proof_6
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_congr_measure
#check convolution_precompR_apply
#check Homotopy.mkCoinductiveAux₁.proof_1
#check QuaternionAlgebra.instRing.proof_6
#check MeasureTheory.Lp.compMeasurePreservingₗᵢ_toFun_coe
#check CategoryTheory.Limits.coconeEquivalenceOpConeOp.proof_8
#check CategoryTheory.Comma.coneOfPreservesIsLimit.proof_3
#check ModuleCat.HasColimit.isColimitColimitCocone.proof_2
#check Equiv.optionSubtype.proof_9
#check LinearMap.compAlternatingMap.proof_5
#check ConvolutionExistsAt.integrable
#check ZMod.instFieldZMod.proof_82
#check Diffeomorph.contMDiff_comp_diffeomorph_iff
#check AddMagma.FreeAddSemigroup.lift.proof_2
#check HasStrictFDerivAt.implicitFunctionDataOfComplemented.proof_4
#check homology.map_eq_lift_desc'_right
#check LinearMap.mk₂'ₛₗ_apply
#check CategoryTheory.Limits.IsCokernel.ofIsoComp.proof_4
#check ChainComplex.fromSingle₀Equiv.proof_3
#check GromovHausdorff.instMetricSpaceGHSpace.proof_19
#check CategoryTheory.coalgebraEquivOver.proof_5
#check HilbertBasis.hasSum_repr_symm
#check CategoryTheory.functorCategoryLinear.proof_2
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_mono
#check ContinuousLinearMap.flip.proof_8
#check HasCompactSupport.convolution_integrand_bound_right
#check StarAlgEquiv.ofLeftInverse'.proof_5
#check AlgebraicGeometry.LocallyRingedSpace.IsOpenImmersion.pullbackConeOfLeft.proof_4
#check CategoryTheory.Limits.Cocone.fromStructuredArrow.proof_2
#check Convex.isLittleO_alternate_sum_square
#check CategoryTheory.Limits.Cocones.whiskeringEquivalence.proof_4
#check MeasureTheory.L1.setToL1_simpleFunc_indicatorConst
#check LieModule.coe_linearMap_maxTrivLinearMapEquivLieModuleHom_symm
#check Unitization.starLift.proof_4
#check CochainComplex.shiftFunctor.proof_3
#check inCoordinates_tangent_bundle_core_model_space
#check ContinuousLinearEquiv.hasSum'
#check CategoryTheory.MonoOver.inf.proof_7
#check BiheytingHom.copy.proof_3
#check Module.Baer.extensionOfMaxAdjoin.proof_3
#check MulAut.conj.proof_5
#check TopCat.Presheaf.generateEquivalenceOpensLe.proof_4
#check Fintype.toCompleteDistribLattice.proof_2
#check HomologicalComplex.dgoEquivHomologicalComplexCounitIso.proof_3
#check MeasureTheory.condexpL1Clm_indicatorConst
#check MonoidAlgebra.equivariantOfLinearOfComm.proof_2
#check CategoryTheory.CommSq.leftAdjointLiftStructEquiv.proof_6
#check DenseInducing.extendRingHom.proof_4
#check FreeLieAlgebra.lift.proof_4
#check ModuleCat.kernelIsLimit.proof_2
#check PosNum.linearOrder.proof_7
#check Bundle.ContinuousLinearMap.vectorBundle
#check uniformSpaceOfCompactT2.proof_4
#check ContMDiffAt.clm_apply
#check ContinuousLinearEquiv.preimage_closure
#check CategoryTheory.Comma.coconeOfPreservesIsColimit.proof_2
#check ModuleCat.instModuleαAddCommGroupMkOfSMul'ToSemiringToAddCommMonoidInstAddCommGroupαMkOfSMul'.proof_5
#check ContinuousLinearMap.flipMultilinear.proof_9
#check ContinuousLinearEquiv.comp_contDiffWithinAt_iff
#check ContinuousAlternatingMap.piLinearEquiv_apply
#check MeasureTheory.Measure.MapContinuousLinearEquiv.isAddHaarMeasure
#check LinearEquiv.ofIsUnitDet.proof_6
#check ContinuousMultilinearMap.curryFinFinset_symm_apply_piecewise_const
#check SmoothMap.compLeftAddMonoidHom.proof_3
#check SSet.horn.proof_2
#check Representation.linHom.invariantsEquivRepHom_symm_apply_coe
#check NonUnitalStarSubalgebra.iSupLift.proof_5
#check Field.DirectLimit.field.proof_25
#check CategoryTheory.Ran.equiv.proof_5
#check Finsupp.liftAddHom.proof_5
#check CategoryTheory.CostructuredArrow.quotientEquiv.proof_3
#check ZMod.instFieldZMod.proof_80
