import Mathlib
#check AlgHom.restrictNormalAux.proof_2
#check CategoryTheory.Monoidal.CommMonFunctorCategoryEquivalence.functor.proof_6
#check ContinuousLinearMap.projKerOfRightInverse_apply_idem
#check HomologicalComplex.asFunctor.proof_5
#check dist_convolution_le'
#check FirstOrder.Ring.languageEquivEquivRingEquiv.proof_5
#check SmoothMap.compLeftAddMonoidHom
#check CategoryTheory.LaxBraidedFunctor.mapCommMon.proof_2
#check CategoryTheory.Triangulated.Octahedron.ofIso.proof_14
#check ModuleCat.smul.proof_6
#check CategoryTheory.ActionCategory.curry.proof_3
#check Trivialization.contMDiffAt_iff
#check CategoryTheory.Limits.pullbackDiagonalMapIdIso.proof_14
#check AlgebraCat.HasLimits.limitConeIsLimit.proof_5
#check Module.Baer.ExtensionOf.inhabited.proof_7
#check AddMagma.FreeAddSemigroup.lift.proof_4
#check CategoryTheory.GradedObject.mapBifunctor.proof_3
#check CategoryTheory.Discrete.addMonoidalFunctor.proof_12
#check TopCat.Presheaf.whiskerIsoMapGenerateCocone.proof_6
#check perfectClosure.proof_6
#check CategoryTheory.ShortComplex.SnakeInput.mk.inj
#check AlgebraicGeometry.PresheafedSpace.GlueData.opensImagePreimageMap_app_assoc
#check Matrix.toLin_kronecker
#check LinearIsometryEquiv.coe_trans
#check ModuleCat.smulNatTrans.proof_3
#check unitsCentralizerEquiv.proof_6
#check LinearEquiv.submoduleMap.proof_4
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_4
#check Submodule.basis_of_pid_aux
#check SchwartzMap.bilinLeftCLM.proof_10
#check MonoidAlgebra.liftMagma.proof_6
#check CategoryTheory.yonedaLemma.proof_5
#check LinearEquiv.arrowCongr_trans
#check homology'.map_desc
#check fdifferential_comp
#check CategoryTheory.Limits.isCokernelEpiComp.proof_3
#check Quaternion.instDivisionRingQuaternionToOneToSemiringToStrictOrderedSemiringToLinearOrderedSemiringToLinearOrderedCommSemiringToLinearOrderedSemifieldToNegToRingToStrictOrderedRingToLinearOrderedRingToLinearOrderedCommRing.proof_33
#check ZMod.commRing.proof_10
#check ContinuousLinearMap.monoidWithZero.proof_7
#check Mod_.comap.proof_4
#check CategoryTheory.Limits.MulticospanIndex.ofPiForkFunctor.proof_3
#check CategoryTheory.Limits.Bicones.functoriality.proof_5
#check smoothPresheafCommGroup.proof_3
#check LinearMap.domRestrict₂.proof_2
#check PiTensorProduct.lift.proof_7
#check AddMagma.FreeAddSemigroup.lift.proof_3
#check CategoryTheory.Pi.sum.proof_5
#check Trivialization.pullback.proof_10
#check Function.Injective.divisionRing.proof_13
#check CategoryTheory.Subobject.lowerEquivalence.proof_3
#check SetLike.gmodule.proof_7
#check TopCat.Presheaf.generateEquivalenceOpensLe_inverse'_map
#check CategoryTheory.Subgroupoid.coe.proof_8
#check Complex.commRing.proof_7
#check SmoothWithinAt.coordChange
#check LinearMap.instLieRingModule.proof_4
#check ModuleCat.HasColimit.coconePointSMul.proof_5
#check Bool.linearOrder.proof_7
#check GroupCat.SurjectiveOfEpiAuxs.g.proof_4
#check HasCompactSupport.hasFDerivAt_convolution_left
#check FreeLieAlgebra.lift.proof_3
#check CategoryTheory.Limits.MulticospanIndex.toPiForkFunctor.proof_3
#check LinearMap.mkContinuousOfExistsBound₂.proof_6
#check CochainComplex.mappingCone.ext_cochain_from_iff
#check CategoryTheory.CategoryOfElements.fromCostructuredArrow.proof_2
#check CategoryTheory.functorCategoryLinear.proof_9
#check mfderivWithin_fst
#check CategoryTheory.ComposableArrows.map'_inv_eq_inv_map'
#check CategoryTheory.categoryOfElements.proof_5
#check SimpleGraph.completeAtomicBooleanAlgebra.proof_23
#check Equiv.image.proof_4
#check PerfectClosure.instCommMonoid.proof_6
#check LinearMap.domRestrict₁₂_apply
#check MeasureTheory.integral_divergence_of_hasFDerivWithinAt_off_countable_of_equiv
#check PowerBasis.quotientEquivQuotientMinpolyMap.proof_4
#check LocalizedModule.instMonoidLocalizedModuleToAddCommMonoidToNonUnitalNonAssocSemiringToNonAssocSemiringToModule.proof_2
#check NonUnitalStarSubalgebra.iSupLift.proof_4
#check ImplicitFunctionData.mk.sizeOf_spec
#check Finset.finAntidiagonal.aux.proof_10
#check Action.instPreadditiveActionInstCategoryAction.proof_16
#check CategoryTheory.Functor.mapArrow.proof_3
#check CategoryTheory.ShortComplex.SnakeInput.mk.injEq
#check ContinuousLinearMap.fderiv_of_bilinear
#check TopCat.Sheaf.objSupIsoProdEqLocus_inv_eq_iff
#check Trivialization.smoothOn_iff
#check PosNum.linearOrder.proof_6
#check CategoryTheory.Functor.Final.extendCocone.proof_4
#check Algebra.leftMulMatrix.proof_9
#check CategoryTheory.regularEpiOfEffectiveEpi.proof_2
#check CategoryTheory.MonoidalOpposite.mopBraidedFunctor.proof_8
#check Set.unitEquivUnitsInteger.proof_7
#check CommMon_.EquivLaxBraidedFunctorPUnit.unitIso.proof_5
#check LinearPMap.eqLocus.proof_3
#check CategoryTheory.LaxBraidedFunctor.mapCommMon.proof_3
#check CategoryTheory.GradedObject.mapBifunctorMap.proof_4
#check RatFunc.instCommMonoid.proof_6
#check unitsCentralizerEquiv.proof_5
#check SmoothMap.add_comp
#check CategoryTheory.Limits.Cones.functorialityEquivalence.proof_5
#check CategoryTheory.bifunctorComp₂₃.proof_4
