import Mathlib
#check ContinuousMultilinearMap.currySumEquiv.proof_13
#check FiberBundleCore.trivChange.proof_7
#check CochainComplex.shiftFunctorZero'.proof_3
#check CategoryTheory.bifunctorComp₁₂.proof_4
#check CategoryTheory.Pseudofunctor.comp.proof_5
#check CategoryTheory.Over.iteratedSliceEquiv.proof_6
#check CategoryTheory.ComposableArrows.homMk₅_app_one
#check IsROrC.toStrictOrderedCommRing.proof_5
#check IsDedekindDomain.selmerGroup.proof_4
#check UniformEquiv.changeInv.proof_4
#check StarAlgHomClass.ext_topologicalClosure
#check LinearEquiv.arrowCongr.proof_8
#check ContinuousLinearMap.fderivWithin_of_bilinear
#check LinearPMap.adjointDomain.proof_5
#check SmoothMap.restrictMonoidHom.proof_2
#check SmoothOn.prod_map
#check CliffordAlgebra.even.ι.proof_6
#check PerfectClosure.lift.proof_4
#check Diffeomorph.coe_trans
#check CategoryTheory.Monad.algebraPreadditive.proof_18
#check CategoryTheory.ShortComplex.colimitCocone.proof_4
#check galRestrictHom.proof_6
#check Bimod.whiskerRight.proof_4
#check GradedTensorProduct.instMonoid.proof_3
#check CategoryTheory.ComposableArrows.isoMk₄_inv
#check CategoryTheory.Over.ConstructProducts.conesEquivFunctor.proof_5
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_19
#check smoothOn_continuousLinearMapCoordChange
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_11
#check Submodule.completeLattice.proof_9
#check CategoryTheory.Limits.IsLimit.homIso'.proof_3
#check AlgebraicGeometry.StructureSheaf.sectionsSubring.proof_5
#check AlgebraicGeometry.Scheme.OpenCover.finiteSubcover.proof_3
#check ModuleCat.binaryProductLimitCone.proof_3
#check CategoryTheory.GradedObject.mapTrifunctorMapFunctorObj.proof_4
#check AlgebraicGeometry.PresheafedSpace.componentwiseDiagram.proof_3
#check Mod_.comap.proof_3
#check Complex.commRing.proof_8
#check ContinuousLinearEquiv.arrowCongrSL
#check RatFunc.instAlgebraRatFuncToSemiringToDivisionSemiringToSemifieldInstField.proof_6
#check TopCommRingCat.instCategoryTopCommRingCat.proof_4
#check CategoryTheory.GradedObject.mapBifunctorMap_map_app
#check Localization.orderedCancelCommMonoid.proof_2
#check CategoryTheory.Monad.algebraPreadditive.proof_8
#check GradedTensorProduct.comm.proof_7
#check PartialHomeomorph.MDifferentiable.ker_mfderiv_eq_bot
#check Finsupp.basis.proof_2
#check LeftInvariantDerivation.instSubLeftInvariantDerivation.proof_3
#check Function.Injective.field.proof_19
#check CliffordAlgebra.foldr'Aux.proof_8
#check CategoryTheory.Pi.sum.proof_3
#check CategoryTheory.OplaxFunctor.comp.proof_1
#check Representation.linHom.proof_5
#check CategoryTheory.evaluation.proof_5
#check FirstOrder.Language.DirectLimit.lift.proof_4
#check hfdifferential.proof_4
#check TopCat.Presheaf.SheafConditionPairwiseIntersections.coneEquivCounitIso.proof_4
#check Finsupp.lsum.proof_7
#check RingSubgroupsBasis.toRingFilterBasis.proof_9
#check HasStrictFDerivAt.to_implicitFunction
#check AlgebraicGeometry.ProjIsoSpecTopComponent.ToSpec.MemCarrier.clear_denominator
#check Set.unitEquivUnitsInteger.proof_9
#check CategoryTheory.Functor.mapDifferentialObject_map_f
#check FiberBundleCore.localTriv.proof_6
#check LieAlgebra.coe_rootSpaceProductNegSelf_apply
#check SmoothMap.module'.proof_5
#check Diffeomorph.symm_trans'
#check Function.Injective.field.proof_3
#check ContinuousLinearEquiv.arrowCongrSL.proof_10
#check MvPowerSeries.map.proof_4
#check SmoothMap.smul_comp
#check SmoothFiberwiseLinear.locality_aux₂
#check RatFunc.liftMonoidWithZeroHom.proof_5
#check SmoothBumpCovering.exists_immersion_euclidean
#check CategoryTheory.ShortComplex.FunctorEquivalence.counitIso.proof_4
#check SignType.instCommGroupWithZeroSignType.proof_12
#check IsWellOrder.conditionallyCompleteLinearOrderBot.proof_12
#check CategoryTheory.Limits.HasColimitOfHasCoproductsOfHasCoequalizers.buildIsColimit.proof_2
#check Cardinal.commSemiring.proof_11
#check CliffordAlgebra.gradedAlgebra.proof_2
#check smoothPresheafGroup.proof_3
#check CategoryTheory.constantPresheafAdj.proof_3
#check TopCat.Presheaf.SheafConditionPairwiseIntersections.coneEquivCounitIso.proof_5
#check ContinuousLinearMap.precomp_apply
#check DirectSum.liftRingHom.proof_5
#check Subalgebra.involutiveStar.proof_5
#check AlgebraicGeometry.LocallyRingedSpace.coequalizerCoforkIsColimit.proof_3
#check GradedTensorProduct.liftEquiv.proof_3
#check ModuleCat.HasColimit.coconePointSMul.proof_4
#check SmoothMap.mul_comp
#check NonUnitalSubalgebra.iSupLift.proof_6
#check smoothSheafCommRing.evalHom.proof_2
#check LocalizedModule.divBy.proof_2
#check CategoryTheory.evaluationLeftAdjoint.proof_10
#check NonUnitalStarSubalgebra.iSupLift.proof_7
#check Localization.instCommSemiringLocalizationToCommMonoid.proof_8
#check AlgebraicGeometry.Scheme.empty.proof_3
#check ContinuousLinearMap.hasFDerivWithinAt_of_bilinear
#check ContinuousMultilinearMap.currySumEquiv.proof_12
#check CategoryTheory.functorCategoryPreadditive.proof_5
