import Mathlib
#check SmoothAt.coordChange
#check TopCat.GlueData.MkCore.t'.proof_5
#check Trivialization.symm_apply_eq_mk_continuousLinearEquivAt_symm
#check CategoryTheory.isColimitOfEffectiveEpiFamilyStruct.proof_4
#check fderiv_inv'
#check CategoryTheory.Comma.mapRightComp.proof_5
#check MeasureTheory.set_integral_condexpL1Clm_of_measure_ne_top
#check MultilinearMap.currySum.proof_5
#check CategoryTheory.Quotient.lift.proof_3
#check Submodule.coe_equivMapOfInjective_apply
#check ContMDiffWithinAt.coordChange
#check ContMDiffWithinAt.clm_precomp
#check ContinuousLinearMap.monoidWithZero.proof_6
#check PiCountable.metricSpace.proof_9
#check tangentMap_comp
#check AlgebraicGeometry.Scheme.affineBasisCoverRing.proof_3
#check CategoryTheory.Limits.cokernelImageι.proof_3
#check ContinuousMap.module'.proof_5
#check Localization.instCommSemiringLocalizationToCommMonoid.proof_7
#check AlgHom.restrictNormalAux.proof_3
#check ContinuousLinearEquiv.mfderivWithin_eq
#check MultilinearMap.mkContinuousMultilinear.proof_4
#check WeakDual.gelfandTransform.proof_6
#check TopCat.GlueData.MkCore.t'.proof_4
#check CategoryTheory.Functor.mapAction_map_hom
#check writtenInExtChartAt_comp
#check ZMod.commRing.proof_18
#check LinearEquiv.ofInjective_apply
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_congr_left
#check Submodule.mem_biSup_iff_exists_dfinsupp
#check LinearMap.toMatrix₂'_mul
#check CategoryTheory.functorCategoryLinear.proof_5
#check PiTensorProduct.isEmptyEquiv.proof_5
#check Subgroup.instMulActionQuotientDiffToMonoidToDivInvMonoid.proof_3
#check LinearMap.compDer.proof_10
#check CategoryTheory.Limits.Cones.functoriality.proof_4
#check Num.commSemiring.proof_12
#check Function.Injective.idemSemiring.proof_1
#check DFinsupp.lsum_apply_apply
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_add_left'
#check Function.Injective.field.proof_2
#check FreeLieAlgebra.lift.proof_5
#check HomologicalComplex.dgoToHomologicalComplex.proof_5
#check AlgebraicClosure.toStepOfLE.proof_3
#check AlgebraicGeometry.morphismRestrictRestrictBasicOpen.proof_7
#check TensorProduct.AlgebraTensorModule.lift.equiv.proof_3
#check Perfection.map.proof_5
#check SymAlg.nonAssocSemiring.proof_12
#check DFinsupp.lsum_symm_apply
#check ContinuousLinearMap.hasFPowerSeriesOnBall_bilinear
#check CliffordAlgebra.lift.proof_6
#check Seminorm.instSupSet.proof_4
#check CategoryTheory.Comma.instFullCommaCompCommaCategoryCommaCommaCategoryPreLeft.proof_2
#check CategoryTheory.instFullCoalgebraEilenbergMooreToComonadForgetCofreeAdjComparison.proof_2
#check LinearMap.quotientInfEquivSupQuotient_symm_apply_right
#check ContinuousLinearEquiv.symm_apply_eq
#check MeasureTheory.withDensitySMulLI.proof_4
#check HasCompactSupport.convolution_integrand_bound_right_of_subset
#check CategoryTheory.Limits.cokernelOrderHom.proof_3
#check ContinuousLinearEquiv.symm_map_nhds_eq
#check HahnSeries.SummableFamily.instAddCommGroupSummableFamilyToAddCommMonoid.proof_10
#check Submodule.dualCopairing.proof_3
#check IsIntegralClosure.lift.proof_3
#check DoubleCentralizer.instAlgebra.proof_10
#check ModuleCat.image.lift.proof_3
#check Zsqrtd.lift.proof_4
#check IntermediateField.Lifts.upperBoundIntermediateField.proof_3
#check LinearEquiv.ofLeftInverse_symm_apply
#check MeasureTheory.condexpL1Clm_smul
#check Subalgebra.involutiveStar.proof_6
#check ContinuousLinearMap.flip_apply
#check liftOfDerivationToSquareZero.proof_5
#check DoubleCentralizer.instAlgebra.proof_8
#check CategoryTheory.functorCategoryPreadditive.proof_17
#check CategoryTheory.instFullCoalgebraEilenbergMooreToComonadForgetCofreeAdjComparison.proof_1
#check ContMDiff.clm_precomp
#check LinearEquiv.submoduleMap.proof_5
#check CochainComplex.shiftFunctor.proof_4
#check SimplicialObject.Splitting.toKaroubiNondegComplexIsoN₁.proof_5
#check Metric.metricSpaceSum.proof_8
#check MeasureTheory.L1.setToL1_zero_left'
#check homology.map_eq_desc'_lift_right
#check Submodule.fstEquiv.proof_4
#check LinearMap.coe_toContinuousLinearMap_symm
#check Field.DirectLimit.field.proof_36
#check MeasureTheory.aestronglyMeasurable'_condexpL1Clm
#check Bundle.ContinuousLinearMap.vectorPrebundle.proof_12
#check SimpleGraph.completeAtomicBooleanAlgebra.proof_22
#check MeasureTheory.condexpInd_disjoint_union_apply
#check AlgebraicGeometry.PresheafedSpace.IsOpenImmersion.pullbackConeOfLeftLift.proof_4
#check ModuleCat.monModuleEquivalenceAlgebra.proof_25
#check CategoryTheory.StructuredArrow.subobjectEquiv_apply_coe
#check BoundedContinuousFunction.toLp_inj
#check LinearMap.inverse.proof_2
#check ConditionallyCompleteLattice.copy.proof_13
#check Valuation.extendToLocalization.proof_6
#check HomologicalComplex.flipEquivalenceUnitIso.proof_7
#check IsPrimitiveRoot.embeddingsEquivPrimitiveRoots.proof_4
#check CategoryTheory.coyoneda.proof_5
#check ContMDiffAt.mfderiv
