#check Real.commRing.proof_22
#check ContinuousLinearEquiv.arrowCongrSL_toLinearEquiv_symm_apply
#check ContinuousLinearMap.map_neg₂
#check RingHom.RespectsIso.ofRestrict_morphismRestrict_iff
#check Orthonormal.exists_hilbertBasis_extension
#check LinearMap.quotientInfEquivSupQuotient_symm_apply_eq_zero_iff
#check CategoryTheory.Limits.pullbackDiagonalMapIso.proof_12
#check ValuationSubring.linearOrderOverring.proof_13
#check ModuleCat.Colimits.instAddCommGroupColimitType.proof_9
#check BddAbove.convolutionExistsAt'
#check CategoryTheory.Idempotents.KaroubiKaroubi.counitIso.proof_7
#check AlgebraicGeometry.LocallyRingedSpace.IsOpenImmersion.pullbackConeOfLeftIsLimit.proof_3
#check CategoryTheory.Adjunction.coconesIso.proof_3
#check Trivialization.apply_eq_prod_continuousLinearEquivAt
#check DoubleCentralizer.coeHom.proof_6
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_congr_measure
#check convolution_precompR_apply
#check Homotopy.mkCoinductiveAux₁.proof_1
#check QuaternionAlgebra.instRing.proof_6
#check MeasureTheory.Lp.compMeasurePreservingₗᵢ_toFun_coe
#check CategoryTheory.Limits.coconeEquivalenceOpConeOp.proof_8
#check CategoryTheory.Comma.coneOfPreservesIsLimit.proof_3
#check Equiv.optionSubtype.proof_9
#check LinearMap.compAlternatingMap.proof_5
#check ConvolutionExistsAt.integrable
#check ZMod.instFieldZMod.proof_82
#check Diffeomorph.contMDiff_comp_diffeomorph_iff
#check AddMagma.FreeAddSemigroup.lift.proof_2
#check HasStrictFDerivAt.implicitFunctionDataOfComplemented.proof_4
#check homology.map_eq_lift_desc'_right
#check LinearMap.mk₂'ₛₗ_apply
#check CategoryTheory.Limits.IsCokernel.ofIsoComp.proof_4
#check ChainComplex.fromSingle₀Equiv.proof_3
#check GromovHausdorff.instMetricSpaceGHSpace.proof_19
#check CategoryTheory.coalgebraEquivOver.proof_5
#check HilbertBasis.hasSum_repr_symm
#check CategoryTheory.functorCategoryLinear.proof_2
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_mono
#check ContinuousLinearMap.flip.proof_8
#check HasCompactSupport.convolution_integrand_bound_right
#check AlgebraicGeometry.LocallyRingedSpace.IsOpenImmersion.pullbackConeOfLeft.proof_4
#check CategoryTheory.Limits.Cocone.fromStructuredArrow.proof_2
#check Convex.isLittleO_alternate_sum_square
#check CategoryTheory.Limits.Cocones.whiskeringEquivalence.proof_4
#check MeasureTheory.L1.setToL1_simpleFunc_indicatorConst
#check LieModule.coe_linearMap_maxTrivLinearMapEquivLieModuleHom_symm
#check Unitization.starLift.proof_4
#check inCoordinates_tangent_bundle_core_model_space
#check ContinuousLinearEquiv.hasSum'
#check CategoryTheory.MonoOver.inf.proof_7
#check BiheytingHom.copy.proof_3
#check Module.Baer.extensionOfMaxAdjoin.proof_3
#check MulAut.conj.proof_5
#check TopCat.Presheaf.generateEquivalenceOpensLe.proof_4
#check Fintype.toCompleteDistribLattice.proof_2
#check MeasureTheory.condexpL1Clm_indicatorConst
#check MonoidAlgebra.equivariantOfLinearOfComm.proof_2
#check CategoryTheory.CommSq.leftAdjointLiftStructEquiv.proof_6
#check DenseInducing.extendRingHom.proof_4
#check Game.instAddCommGroupWithOneGame.proof_11
#check FreeLieAlgebra.lift.proof_4
#check ModuleCat.kernelIsLimit.proof_2
#check PosNum.linearOrder.proof_7
#check Bundle.ContinuousLinearMap.vectorBundle
#check uniformSpaceOfCompactT2.proof_4
#check ModuleCat.Colimits.instAddCommGroupColimitType.proof_5
#check ContMDiffAt.clm_apply
#check ContinuousLinearEquiv.preimage_closure
#check CategoryTheory.Comma.coconeOfPreservesIsColimit.proof_2
#check ContinuousLinearMap.flipMultilinear.proof_9
#check ContinuousLinearEquiv.comp_contDiffWithinAt_iff
#check ContinuousAlternatingMap.piLinearEquiv_apply
#check MeasureTheory.Measure.MapContinuousLinearEquiv.isAddHaarMeasure
#check LinearEquiv.ofIsUnitDet.proof_6
#check ContinuousMultilinearMap.curryFinFinset_symm_apply_piecewise_const
#check SmoothMap.compLeftAddMonoidHom.proof_3
#check Representation.linHom.invariantsEquivRepHom_symm_apply_coe
#check NonUnitalStarSubalgebra.iSupLift.proof_5
#check Field.DirectLimit.field.proof_25
#check CategoryTheory.Ran.equiv.proof_5
#check Finsupp.liftAddHom.proof_5
#check CategoryTheory.CostructuredArrow.quotientEquiv.proof_3
#check ZMod.instFieldZMod.proof_80
#check CategoryTheory.Under.pushout.proof_7
#check ContinuousMap.compactConvergenceUniformSpace.proof_4
#check CategoryTheory.Monoidal.CommMonFunctorCategoryEquivalence.unitIso.proof_9
#check contMDiffWithinAt_prod_iff
#check IntermediateField.Lifts.upperBoundIntermediateField.proof_6
#check CategoryTheory.subterminalsEquivMonoOverTerminal.proof_11
#check Submodule.sndEquiv.proof_5
#check Function.Injective.completeAtomicBooleanAlgebra.proof_4
#check ContinuousLinearEquiv.piRing.proof_17
#check CochainComplex.mk
#check CategoryTheory.Limits.PushoutCocone.isColimitOfFactors.proof_3
#check CategoryTheory.ModuleCat.RestrictionCoextensionAdj.counit'.proof_3
#check DistribLattice.copy.proof_10
#check CategoryTheory.currying_functor_map_app
#check SmoothAt.coordChangeL
#check DoubleCentralizer.instAlgebra.proof_12
#check Action.ofMulActionLimitCone.proof_2
