import Mathlib
#check selfAdjointPart.proof_4
#check HasStrictFDerivAt.implicitFunctionDataOfComplemented.proof_6
#check CategoryTheory.yonedaLemma.proof_4
#check Basis.det.proof_3
#check Bundle.ContinuousLinearMap.memTrivializationAtlas
#check Smooth.coordChangeL
#check NonUnitalSubalgebra.iSupLift.proof_3
#check RingQuot.instSemiring.proof_6
#check ContinuousLinearEquiv.comp_right_fderivWithin
#check Algebra.TensorProduct.algHomOfLinearMapTensorProduct.proof_4
#check SchwartzMap.mkLM.proof_3
#check IccLeftChart.proof_11
#check IsOpenMap.adjunctionNhds.proof_6
#check LinearMap.range_toContinuousLinearMap
#check UniqueMDiffWithinAt.image_denseRange
#check ContinuousLinearMap.norm_iteratedFDeriv_le_of_bilinear
#check Function.Injective.linearOrderedSemifield.proof_1
#check LinearMap.toMatrix₂_mul_basis_toMatrix
#check TensorProduct.AlgebraTensorModule.assoc_symm_tmul
#check FreeAbelianGroup.liftMonoid.proof_5
#check Action.forgetMonoidal.proof_8
#check ContMDiffOn.prod_map
#check Diffeomorph.coe_prodCongr
#check Subgroup.instMulActionElemSetLeftTransversalsCoeSubgroupInstSetLikeSubgroupToMonoidToDivInvMonoid.proof_3
#check Localization.r'.proof_2
#check MultilinearMap.mkContinuousLinear.proof_5
#check Subalgebra.toSubmodule.proof_5
#check Finsupp.basis.proof_7
#check PerfectClosure.PerfectClosure.addCommGroup.proof_11
#check Bool.linearOrder.proof_5
#check Diffeomorph.prodCongr.proof_1
#check Finsupp.basis.proof_6
#check Multiset.instOrderedCancelAddCommMonoidMultiset.proof_8
#check Pretrivialization.continuousLinearMap_symm_apply'
#check NonUnitalStarSubalgebra.iSupLift_inclusion
#check ContinuousLinearEquiv.comp_hasFDerivWithinAt_iff
#check TensorProduct.AlgebraTensorModule.rightComm.proof_24
#check Ideal.piQuotEquiv.proof_5
#check ContinuousLinearEquiv.isBigO_sub_rev
#check ValuationRing.linearOrderedCommGroupWithZero.proof_11
#check Poly.instCommRingPoly.proof_25
#check LinearEquiv.ofSubmodule'_apply
#check RingQuot.starRing.proof_3
#check Smooth.prod_map
#check CategoryTheory.StructuredArrow.subobjectEquiv_symm_apply
#check TopCat.Presheaf.generateEquivalenceOpensLe_inverse'.proof_5
#check BilinForm.toMatrix_comp
#check CategoryTheory.Monad.algebraPreadditive.proof_13
#check ContinuousMultilinearMap.currySumEquiv.proof_11
#check CategoryTheory.categoryOfElements.proof_3
#check WithSeminorms.banach_steinhaus
#check DFinsupp.sum_mapRange_index.linearMap
#check ContMDiffWithinAt.coordChangeL
#check Action.actionPunitEquivalence.proof_5
#check ContinuousLinearEquiv.iteratedFDerivWithin_comp_left
#check ZMod.commRing.proof_22
#check CochainComplex.mk_X_1
#check Con.correspondence.proof_8
#check ContMDiffOn.coordChange
#check skewAdjointMatricesLieSubalgebraEquivTranspose_apply
#check ModuleCat.FilteredColimits.colimitSMulWithZero.proof_2
#check Action.actionPunitEquivalence.proof_3
#check CompleteLattice.independent_of_dfinsupp_lsum_injective
#check Basis.restrictScalars_repr_apply
#check LieModule.coe_maxTrivLinearMapEquivLieModuleHom
#check CategoryTheory.Limits.preservesCoequalizersOfPreservesPushoutsAndBinaryCoproducts.proof_3
#check MDifferentiableAt.mfderiv_prod
#check Convex.second_derivative_within_at_symmetric_of_mem_interior
#check CategoryTheory.Limits.pullbackPullbackRightIsPullback.proof_8
#check SetLike.gmodule.proof_6
#check LocalizedModule.instSemiringLocalizedModuleToAddCommMonoidToNonUnitalNonAssocSemiringToNonAssocSemiringToModule.proof_13
#check NonUnitalStarSubalgebra.iSupLift.proof_8
#check QuotientAddGroup.circularOrder.proof_6
#check Mon_.monMonoidal.proof_5
#check normalizedFactorsEquivOfQuotEquiv.proof_6
#check CategoryTheory.subterminalsEquivMonoOverTerminal.proof_10
#check SmoothMap.module'.proof_6
#check ContinuousLinearMap.compL_apply
#check AlgEquiv.aut.proof_12
#check Algebra.TensorProduct.opAlgEquiv.proof_14
#check HasStrictFDerivAt.implicitToLocalHomeomorphOfComplemented_apply
#check AddCircle.equivIccQuot.proof_4
#check ContinuousLinearEquiv.compContinuousMultilinearMapL.proof_21
#check CategoryTheory.functorCategoryLinear.proof_8
#check ChainComplex.single₀.proof_5
#check Representation.linHom.invariantsEquivRepHom.proof_8
#check ContinuousLinearEquiv.comp_contDiffOn_iff
#check SmoothMap.semiring.proof_21
#check Convex.norm_image_sub_le_of_norm_fderivWithin_le'
#check MeasureTheory.condexpL2_ae_eq_zero_of_ae_eq_zero
#check HasFTaylorSeriesUpToOn.eventually_hasFDerivAt
#check StarSubalgebra.inclusion.proof_6
#check CategoryTheory.Limits.baseChange.proof_7
#check Bundle.ContinuousLinearMap.vectorPrebundle.isSmooth.proof_1
#check Real.commRing.proof_15
#check CategoryTheory.Pi.sum.proof_4
#check Matrix.SpecialLinearGroup.toLin'.proof_6
#check ContinuousMultilinearMap.curryFinFinset_apply_const
#check RingSubgroupsBasis.toRingFilterBasis.proof_6
#check CategoryTheory.Limits.colimConstAdj.proof_9
