#check CategoryTheory.Limits.MulticospanIndex.ofPiForkFunctor.proof_3
#check Submodule.biSup_eq_range_dfinsupp_lsum
#check Trivialization.coe_continuousLinearEquivAt_eq
#check LinearMap.domRestrict₂.proof_2
#check StarAlgEquiv.ofLeftInverse'_symm_apply
#check PiTensorProduct.lift.proof_7
#check AddMagma.FreeAddSemigroup.lift.proof_3
#check CategoryTheory.Pi.sum.proof_5
#check Trivialization.pullback.proof_10
#check RatFunc.instAlgebraRatFuncToSemiringToDivisionSemiringToSemifieldInstFieldRatFunc.proof_7
#check exists_hilbertBasis
#check CategoryTheory.Subobject.lowerEquivalence.proof_3
#check SetLike.gmodule.proof_7
#check ContinuousMultilinearMap.curryLeft.proof_6
#check TopCat.Presheaf.generateEquivalenceOpensLe_inverse'_map
#check ContinuousLinearMap.adjointAux_adjointAux
#check CategoryTheory.Subgroupoid.coe.proof_8
#check IntermediateField.instPartialOrderLifts.proof_3
#check SmoothWithinAt.coordChange
#check Bimod.tensorHom.proof_3
#check Bool.linearOrder.proof_7
#check GroupCat.SurjectiveOfEpiAuxs.g.proof_4
#check MeasureTheory.L1.setToL1_lipschitz
#check HasCompactSupport.hasFDerivAt_convolution_left
#check FreeLieAlgebra.lift.proof_3
#check ValuationSubring.principalUnitGroupEquiv.proof_4
#check CategoryTheory.Limits.MulticospanIndex.toPiForkFunctor.proof_3
#check LinearMap.separatingLeft_congr_iff
#check SmoothMap.addGroup.proof_15
#check CategoryTheory.CategoryOfElements.fromCostructuredArrow.proof_2
#check CategoryTheory.functorCategoryLinear.proof_9
#check mfderivWithin_fst
#check LinearEquiv.skewProd.proof_3
#check LinearMap.toMatrix_comp
#check CategoryTheory.categoryOfElements.proof_5
#check SimpleGraph.completeAtomicBooleanAlgebra.proof_23
#check Equiv.image.proof_4
#check LinearMap.domRestrict₁₂_apply
#check LinearIsometryEquiv.norm_iteratedFDerivWithin_comp_right
#check MeasureTheory.integral_divergence_of_hasFDerivWithinAt_off_countable_of_equiv
#check SmoothMap.semiring.proof_16
#check PowerBasis.quotientEquivQuotientMinpolyMap.proof_4
#check ContinuousLinearMap.coeFn_compLpL
#check NonUnitalStarSubalgebra.iSupLift.proof_4
#check ImplicitFunctionData.mk.sizeOf_spec
#check Action.instPreadditiveActionInstCategoryAction.proof_16
#check CategoryTheory.Functor.mapArrow.proof_3
#check CategoryTheory.ModuleCat.RestrictionCoextensionAdj.HomEquiv.fromRestriction.proof_3
#check AddCommGroupCat.Colimits.instAddCommGroupColimitType.proof_14
#check ContinuousLinearMap.fderiv_of_bilinear
#check preordCatToPartOrdCatForgetAdjunction.proof_7
#check Trivialization.smoothOn_iff
#check PosNum.linearOrder.proof_6
#check MeasureTheory.L1.setToL1_mono
#check CategoryTheory.Functor.Final.extendCocone.proof_4
#check Set.unitEquivUnitsInteger.proof_7
#check LinearPMap.eqLocus.proof_3
#check Action.instLinearActionInstCategoryActionInstPreadditiveActionInstCategoryAction.proof_3
#check CategoryTheory.LaxBraidedFunctor.mapCommMon.proof_3
#check Pretrivialization.continuousLinearMap.isLinear.proof_1
#check RatFunc.instCommMonoid.proof_6
#check SmoothMap.add_comp
#check CategoryTheory.Limits.Cones.functorialityEquivalence.proof_5
#check LinearEquiv.toContinuousLinearEquivOfBounds
#check Real.instDistribLatticeReal.proof_10
#check CategoryTheory.Over.ConstructProducts.conesEquivFunctor.proof_4
#check LinearEquiv.arrowCongr_comp
#check ContinuousLinearEquiv.equivOfRightInverse.proof_4
#check TensorAlgebra.lift.proof_4
#check CompleteLattice.lsum_comp_mapRange_toSpanSingleton
#check ContinuousLinearEquiv.equivOfRightInverse_symm_apply
#check ContMDiff.coordChangeL
#check NonUnitalSubalgebra.instInvolutiveStar.proof_5
#check SubmodulesBasis.toModuleFilterBasis.proof_9
#check TopCommRingCat.instCategoryTopCommRingCat.proof_5
#check AlgebraCat.HasLimits.limitConeIsLimit.proof_7
#check ContinuousLinearMap.norm_smulRightL
#check Path.Homotopy.map.proof_4
#check Smooth.coordChange
#check ContinuousLinearMap.adjoint_comp
#check ContMDiffOn.coordChangeL
#check MeasureTheory.lintegral_nnnorm_condexpL2_indicator_le
#check Matrix.toLinearMapₛₗ₂'_toMatrix'
#check MeasureTheory.ContinuousMap.inner_toLp
#check MDifferentiableOn.comp
#check restrictRootsOfUnity.proof_4
#check PerfectClosure.instCommMonoidPerfectClosure.proof_3
#check ContinuousAffineMap.toConstProdContinuousLinearMap.proof_12
#check CategoryTheory.Comonad.coalgebraPreadditive.proof_16
#check TensorProduct.AlgebraTensorModule.assoc.proof_17
#check CategoryTheory.Sites.pullbackCopullbackAdjunction.proof_6
#check ContinuousLinearMap.op_norm_le_bound₂
#check AlgHom.extendScalars.proof_5
#check CategoryTheory.Limits.coneOfConeUncurryIsLimit.proof_3
#check Path.Homotopy.symm₂.proof_4
#check ContinuousMap.hasSum_of_hasSum_Lp
#check AlgebraicGeometry.morphismRestrictOpensRange.proof_10
#check CommMon_.EquivLaxBraidedFunctorPunit.unitIso.proof_5
#check CategoryTheory.Monad.algebraFunctorOfMonadHom.proof_5
#check Ordinal.monoid.proof_4
