import Mathlib
#check CategoryTheory.curryObj.proof_5
#check Rep.homEquiv.proof_5
#check CategoryTheory.LaxMonoidalFunctor.mapMon_map_hom
#check SmoothAt.prod_map
#check LinearMap.BilinForm.tensorDistribEquiv_tmul
#check completeLatticeOfSup.proof_8
#check SmoothMap.compLeftRingHom.proof_8
#check AlgebraicGeometry.morphismRestrictRestrictBasicOpen
#check Perfection.lift.proof_6
#check DoubleCentralizer.coeHom.proof_7
#check Rep.homEquiv.proof_6
#check CategoryTheory.whiskeringLeft.proof_4
#check Subgroup.instMulActionElemSetLeftTransversalsCoeSubgroupInstSetLikeSubgroupToMonoidToDivInvMonoid.proof_2
#check RingSubgroupsBasis.toRingFilterBasis.proof_7
#check LinearMap.lsum.proof_5
#check Zsqrtd.commRing.proof_7
#check SmoothMap.compLeftRingHom.proof_9
#check IsPrimitiveRoot.zmodEquivZPowers.proof_6
#check TrivSqZeroExt.instL1SeminormedRing.proof_21
#check CategoryTheory.CategoryOfElements.fromCostructuredArrow.proof_3
#check CategoryTheory.FreeBicategory.lift.proof_3
#check CategoryTheory.uncurry.proof_3
#check CategoryTheory.Limits.Cocones.functorialityEquivalence.proof_5
#check AlgebraicGeometry.Scheme.restrictRestrictComm.proof_7
#check PerfectClosure.lift.proof_7
#check AffineSubspace.isometryEquivMap.coe_apply
#check Real.commRing.proof_8
#check CategoryTheory.ShortComplex.FunctorEquivalence.inverse.proof_5
#check CategoryTheory.Limits.preservesEqualizersOfPreservesPullbacksAndBinaryProducts.proof_4
#check homology'.map_eq_desc'_lift_left
#check CategoryTheory.ShortComplex.ShortExact.δ_apply
#check CategoryTheory.ShortComplex.ShortExact.δ_eq
#check Mon_.EquivLaxMonoidalFunctorPUnit.monToLaxMonoidal.proof_10
#check HasMFDerivAt.comp
#check HomologicalComplex.isLimitOfEval.proof_2
#check RatFunc.instAddCommGroup.proof_7
#check RingSubgroupsBasis.toRingFilterBasis.proof_8
#check TensorProduct.AlgebraTensorModule.uncurry.proof_3
#check Mod_.comap.proof_5
#check CategoryTheory.Functor.mapAction.proof_3
#check LocalizedModule.instAddCommGroupLocalizedModuleToAddCommMonoid.proof_5
#check CategoryTheory.Triangulated.Octahedron.mk.injEq
#check MeasureTheory.Filtration.instCompleteLattice.proof_14
#check Trivialization.prod_apply
#check Homotopy.equivSubZero.proof_5
#check CochainComplex.mappingCone.d_snd_v'_assoc
#check ContinuousAddMonoidHom.instAddCommGroupContinuousAddMonoidHomToAddMonoidToSubNegAddMonoidToAddGroup.proof_13
#check Mon_.EquivLaxMonoidalFunctorPUnit.counitIso.proof_7
#check NonUnitalAlgHom.toAlgHom.proof_5
#check AlgebraicGeometry.Scheme.OpenCover.gluedCover.proof_10
#check Function.Injective.divisionRing.proof_2
#check CategoryTheory.SimplicialObject.Augmented.whiskering.proof_3
#check LinearEquiv.automorphismGroup.proof_13
#check CategoryTheory.Monoidal.MonFunctorCategoryEquivalence.Functor.obj.proof_7
#check SchwartzMap.mkLM
#check CategoryTheory.OplaxNatTrans.vcomp.proof_3
#check ChainComplex.toSingle₀Equiv.proof_4
#check smoothFiberwiseLinear.proof_9
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_13
#check SemidirectProduct.instGroupSemidirectProduct.proof_12
#check CategoryTheory.preadditiveYoneda.proof_5
#check ContinuousLinearEquiv.arrowCongrSL_symm_apply
#check VectorFourier.integral_bilin_fourierIntegral_eq_flip
#check Function.Injective.field.proof_26
#check fdifferential
#check ContinuousMap.module'.proof_6
#check Representation.dual.proof_6
#check CategoryTheory.Discrete.monoidal.proof_11
#check CategoryTheory.Over.ConstructProducts.conesEquivFunctor_map_hom
#check HomologicalComplex.dgoEquivHomologicalComplexCounitIso.proof_5
#check Real.commRing.proof_7
#check Action.instLinearActionInstCategoryActionInstPreadditiveActionInstCategoryAction.proof_5
#check PEquiv.instSemilatticeInfPEquiv.proof_2
#check CategoryTheory.Cat.HasLimits.instCategoryLimitTypeTypesCompCatCategoryObjectsHasLimitUnivLE_of_maxSmall_self.proof_10
#check Diffeomorph.mk.sizeOf_spec
#check CategoryTheory.ComposableArrows.sc'.proof_7
#check LinearMap.compl₂_apply
#check SmoothOn.coordChangeL
#check SmoothMap.smul_comp'
#check MDifferentiableWithinAt.comp
#check CategoryTheory.Comma.mapLeftComp.proof_5
#check PartialDiffeomorph.mk.sizeOf_spec
#check Ideal.modulePi.proof_4
#check Module.Baer.extensionOfMaxAdjoin.proof_2
#check ContinuousLinearMap.addCommGroup.proof_12
#check FiniteDimensional.basisSingleton.proof_8
#check CategoryTheory.Limits.MulticospanIndex.toPiForkFunctor.proof_2
#check CategoryTheory.instFullAlgebraEilenbergMooreToMonadFreeForgetAdjComparison.proof_1
#check AddAut.group.proof_10
#check ContinuousLinearMap.flip_smul
#check ValuationRing.linearOrderedCommGroupWithZero.proof_13
#check MeasureTheory.set_lintegral_nnnorm_condexpL2_indicator_le
#check ZMod.commRing.proof_11
#check CategoryTheory.Limits.Cone.fromCostructuredArrow.proof_2
#check AlgebraicTopology.DoldKan.Γ₂N₁.natTrans.proof_3
#check Trivialization.smoothAt_iff
#check ZMod.commRing.proof_24
#check ContMDiffAt.clm_precomp
#check SubmodulesBasis.toModuleFilterBasis.proof_4
#check CategoryTheory.Ran.equiv.proof_4
