import Mathlib
#check CochainComplex.HomComplex.Cocycle.instModuleCocycleToSemiringToAddCommMonoidInstAddCommGroupCocycle.proof_5
#check DFinsupp.sumAddHom.proof_2
#check CategoryTheory.regularEpiOfEffectiveEpi.proof_3
#check CategoryTheory.Idempotents.KaroubiKaroubi.counitIso.proof_8
#check AddCommGroupCat.binaryProductLimitCone.proof_3
#check WittVector.lift.proof_3
#check ContinuousLinearEquiv.comp_right_hasFDerivAt_iff'
#check groupCohomology.oneCocyclesLequivOfIsTrivial_apply_apply
#check hfdifferential.proof_5
#check HilbertBasis.coe_mkOfOrthogonalEqBot
#check CategoryTheory.DifferentialObject.shiftFunctor.proof_4
#check Pretrivialization.continuousLinearMap.isLinear
#check IsAdjoinRootMonic.basis.proof_4
#check TensorProduct.Algebra.moduleAux.proof_7
#check VectorPrebundle.IsSmooth.exists_smoothCoordChange
#check MeasureTheory.norm_condexpL2_coe_le
#check LeftInvariantDerivation.mk.injEq
#check SmoothMap.module'.proof_3
#check TensorProduct.gradedMul_def
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_16
#check LinearMap.coe_quotientInfToSupQuotient
#check ContinuousMap.toLp_denseRange
#check DoubleCentralizer.instAlgebra.proof_11
#check Subalgebra.iSupLift.proof_6
#check LocalizedModule.instAddCommGroupLocalizedModuleToAddCommMonoid.proof_4
#check Function.Injective.completeAtomicBooleanAlgebra.proof_3
#check ContinuousLinearEquiv.compContinuousMultilinearMapL.proof_19
#check ContMDiffAt.clm_postcomp
#check IsIntegralClosure.lift.proof_6
#check MonTypeEquivalenceMon.inverse.proof_7
#check CategoryTheory.Monoidal.MonFunctorCategoryEquivalence.Functor.obj.proof_6
#check CategoryTheory.Limits.Cones.whiskeringEquivalence.proof_5
#check Localization.instCommSemiringLocalizationToCommMonoid.proof_3
#check smoothFiberwiseLinear.proof_8
#check CategoryTheory.enrichedNatTransYonedaTypeIsoYonedaNatTrans.proof_5
#check AffineEquiv.trans.proof_3
#check Rep.unitIso.proof_6
#check CategoryTheory.Cat.HasLimits.limitConeLift.proof_7
#check CategoryTheory.preadditiveCoyoneda.proof_5
#check MultilinearMap.curryFinFinset_apply_const
#check CategoryTheory.Limits.Cone.fromCostructuredArrow.proof_3
#check PUnit.biheytingAlgebra.proof_3
#check SmoothMap.addGroup.proof_13
#check Path.Homotopy.reflTransSymm.proof_4
