import Mathlib
#check TopologicalSpace.Opens.mapMapIso.proof_4
#check CategoryTheory.Discrete.addMonoidalFunctor.proof_11
#check CategoryTheory.Comonad.coalgebraPreadditive.proof_4
#check CategoryTheory.Monoidal.functorCategoryMonoidal.proof_12
#check InhomogeneousCochains.d.proof_2
#check UniformSpace.Completion.ring.proof_8
#check LinearMap.quotientInfEquivSupQuotient_symm_apply_left
#check FiberwiseLinear.localHomeomorph.proof_9
#check CochainComplex.single₀IsoSingle.proof_5
#check ContinuousMap.toLp_inj
#check CochainComplex.fromSingle₀Equiv.proof_4
#check LinearEquiv.arrowCongr.proof_7
#check Module.End.divisionRing.proof_37
#check ContinuousLinearEquiv.arrowCongrSL.proof_5
#check LinearMap.ker_toContinuousLinearMap
#check OreLocalization.universalMulHom.proof_2
#check ContinuousLinearEquiv.arrowCongrEquiv.proof_1
#check LinearMap.IsSymmetric.diagonalization_apply_self_apply
#check CategoryTheory.isColimitTautologicalCocone.proof_3
#check CategoryTheory.MonoOver.congr.proof_7
#check ContinuousMap.toLp_comp_toContinuousMap
#check ContinuousLinearMap.norm_compSL_le
#check CategoryTheory.evaluationLeftAdjoint_map_app
#check Gamma0.proof_4
#check LieAlgebra.rootSpaceWeightSpaceProductAux.proof_3
#check DoubleQuot.quotQuotEquivQuotOfLEₐ.proof_1
#check CategoryTheory.coyoneda.proof_4
#check CategoryTheory.Limits.Cocone.category.proof_5
#check TopCat.Presheaf.SheafConditionPairwiseIntersections.coneEquivUnitIsoApp.proof_4
#check TensorProduct.AlgebraTensorModule.homTensorHomMap_apply
#check CategoryTheory.commaCategory.proof_5
#check CategoryTheory.Discrete.monoidalFunctorComp.proof_7
#check LocalHomeomorph.MDifferentiable.mfderiv_surjective
#check WittVector.frobenius.proof_2
#check hasFTaylorSeriesUpToOn_succ_iff_right
#check CochainComplex.single₀IsoSingle.proof_7
#check Mon_.monMonoidal.proof_8
#check Module.endTensorEndAlgHom_apply
#check CategoryTheory.Functor.leftDerivedObjProjectiveZero_inv
#check ContinuousLinearEquiv.fst_equivOfRightInverse
#check LeftInvariantDerivation.hasIntScalar.proof_3
#check Surreal.orderedAddCommGroup.proof_11
#check ContMDiffWithinAt.clm_postcomp
#check Trivialization.continuousLinearEquivAt_apply
#check PerfectClosure.PerfectClosure.addCommGroup.proof_2
#check IccLeftChart.proof_10
#check CategoryTheory.Subobject.subobjectOrderIso.proof_5
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_17
#check CategoryTheory.Comma.mapRightComp.proof_6
#check HasFTaylorSeriesUpToOn.compContinuousLinearMap
#check IsWellOrder.conditionallyCompleteLinearOrderBot.proof_9
#check ContinuousLinearEquiv.isBigO_comp_rev
#check mfderivWithin_comp
#check SubmodulesBasis.toModuleFilterBasis.proof_5
#check NonUnitalStarSubalgebra.iSupLift.proof_6
#check MultilinearMap.domDomCongrLinearEquiv'_symm_apply
#check fderivWithin_inv'
#check IntermediateField.Lifts.upperBoundAlgHom.proof_6
#check IntermediateField.Lifts.eq_of_le
#check ContinuousLinearEquiv.mfderiv_eq
#check MeasureTheory.L1.setToL1_indicatorConstLp
#check SmoothMap.addGroup.proof_14
#check CategoryTheory.CosimplicialObject.Augmented.whiskering.proof_4
#check MeasureTheory.AEStronglyMeasurable.convolution_integrand'
#check Sym2.sym2EquivSym'.proof_4
#check LinearIsometryEquiv.symm_trans
#check FundamentalGroupoid.instGroupoidFundamentalGroupoid.proof_5
#check CliffordAlgebra.GradedAlgebra.lift_ι_eq
#check CategoryTheory.MonoidalFunctor.mapAction.proof_9
#check CategoryTheory.ModuleCat.ExtendRestrictScalarsAdj.HomEquiv.fromExtendScalars.proof_3
#check HasStrictFDerivAt.to_implicitFunctionOfComplemented
#check Function.Injective.orderedSemiring.proof_3
#check CategoryTheory.Monad.MonadicityInternal.comparisonLeftAdjointHomEquiv_symm_apply
#check CategoryTheory.whiskeringLeft.proof_5
#check PerfectClosure.PerfectClosure.addCommGroup.proof_3
#check DFinsupp.lsum_single
#check LieModule.weight_vector_multiplication
#check CategoryTheory.uncurry_map_app
#check CategoryTheory.currying.proof_6
#check CategoryTheory.Comonad.coalgebraPreadditive.proof_11
#check LinearMap.sum_repr_mul_repr_mulₛₗ
#check AlgebraicGeometry.Scheme.Pullback.gluing.proof_9
#check commMonTypeEquivalenceCommMon.proof_15
#check ZMod.commRing.proof_17
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_5
#check TopCat.colimitCoconeIsColimit.proof_3
#check hasFDerivAt_ring_inverse
#check ContinuousLinearMap.apply_apply'
#check RatFunc.instFieldRatFunc.proof_10
#check CommRingCat.Colimits.instCommRingColimitType.proof_7
#check hasFDerivAt_convolution_right_with_param
#check Action.leftRegularTensorIso.proof_4
#check CategoryTheory.CommSq.rightAdjointLiftStructEquiv.proof_5
#check QuaternionGroup.instGroupQuaternionGroup.proof_3
#check SimpleGraph.completeAtomicBooleanAlgebra.proof_21
#check ContinuousLinearMap.postcomp_toFun
#check CategoryTheory.LaxMonoidalFunctor.mapMon.proof_4
#check polarCoord.proof_7
#check ContMDiffOn.contMDiffOn_tangentMapWithin
#check Homotopy.mkCoinductive.proof_2
