import Mathlib
#check ContinuousLinearMap.flip.proof_5
#check LinearMap.SeparatingLeft.congr
#check CategoryTheory.Limits.IsColimit.homIso'.proof_3
#check ContinuousLinearMap.postcomp.proof_7
#check CategoryTheory.categoryOfElements.proof_4
#check QuaternionGroup.instGroupQuaternionGroup.proof_2
#check ValuationRing.linearOrderedCommGroupWithZero.proof_7
#check SetTheory.Game.instAddCommGroupWithOneGame.proof_11
#check BoxIntegral.HasIntegral.of_le_Henstock_of_forall_isLittleO
#check HomologicalComplex.flipEquivalenceCounitIso.proof_6
#check LocalizedModule.instSemiringLocalizedModuleToAddCommMonoidToNonUnitalNonAssocSemiringToNonAssocSemiringToModule.proof_7
#check ContinuousLinearEquiv.ofBijective_apply_symm_apply
#check Set.unitEquivUnitsInteger.proof_8
#check Cardinal.commSemiring.proof_12
#check Action.instPreadditiveActionInstCategoryAction.proof_10
#check SimpleGraph.completeAtomicBooleanAlgebra.proof_24
#check Convex.second_derivative_within_at_symmetric
#check HasMFDerivAt.comp_hasMFDerivWithinAt
#check TopCat.GlueData.ofOpenSubsets_toGlueData_t
#check LinearIsometryEquiv.trans_apply
#check PerfectClosure.lift.proof_6
#check ContinuousLinearMap.precomp_toFun
#check HasStrictFDerivAt.implicitToLocalHomeomorph_self
#check ContinuousLinearMap.adjointAux_inner_left
#check LocalizedModule.divBy.proof_3
#check MeasureTheory.withDensitySMulLI.proof_5
#check SignType.instCommGroupWithZeroSignType.proof_13
#check isAdjointPair_toLinearMap₂'
#check AlgebraicTopology.DoldKan.Γ₂_map_f_app
#check LinearMap.IsSymmetric.diagonalization_symm_apply
#check latToBddLatCatForgetAdjunction.proof_5
#check HomologicalComplex.single.proof_5
#check stereographic.proof_8
#check LinearMap.toMatrix₂_compl₁₂
#check PresheafOfModules.Hom.instAddCommGroupHomPresheafOfModulesToQuiverToCategoryStructInstCategoryPresheafOfModules.proof_10
#check CategoryTheory.Limits.kernelOrderHom.proof_4
#check continuousMultilinearCurryRightEquiv_apply
#check IsAdjoinRoot.lift.proof_4
#check IccRightChart.proof_10
#check ContinuousLinearEquiv.unitsEquivAut.proof_9
#check MeasureTheory.L1.setToL1_nonneg
#check AlgebraicClosure.toStepOfLE.proof_4
#check CategoryTheory.Limits.Types.binaryProductFunctor.proof_5
#check CategoryTheory.Monoidal.functorHasLeftDual.proof_6
#check Cardinal.commSemiring.proof_7
#check CategoryTheory.Limits.combineCones.proof_4
#check SmoothVectorBundle.pullback.proof_1
#check Homotopy.mkInductive.proof_1
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_4
#check SmoothMap.group.proof_7
#check LinearIsometry.map_orthogonalProjection'
#check Subgroup.instMulActionQuotientDiffToMonoidToDivInvMonoid.proof_2
#check Polynomial.derivative.proof_2
#check Algebra.TensorProduct.opAlgEquiv.proof_9
#check AffineSubspace.directionOfNonempty.proof_3
#check Function.Injective.orderedSemiring.proof_2
#check ContinuousLinearMap.map_zero₂
#check HilbertBasis.hasSum_orthogonalProjection
#check ContinuousMultilinearMap.alternatization.proof_5
#check Filter.Realizer.bind.proof_5
#check ContinuousLinearEquiv.comp_differentiableWithinAt_iff
#check TopCat.GlueData.ofOpenSubsets.proof_6
#check CochainComplex.fromSingle₀Equiv.proof_3
#check SmoothMap.semiring.proof_18
#check CategoryTheory.Limits.HasLimitOfHasProductsOfHasEqualizers.buildIsLimit.proof_3
#check ModuleCat.monModuleEquivalenceAlgebra.proof_11
#check LocalHomeomorph.MDifferentiable.mfderiv.proof_3
#check GradedRing.projZeroRingHom.proof_4
#check Real.commRing.proof_14
#check CategoryTheory.instFullAlgebraEilenbergMooreToMonadFreeForgetAdjComparison.proof_2
#check Real.commRing.proof_10
#check CategoryTheory.instBicategoryMonoidalSingleObj.proof_4
#check CommRingCat.Colimits.instCommRingColimitType.proof_8
#check LieModule.maxTrivHom.proof_3
#check ContinuousLinearMap.flipMultilinear.proof_6
#check Ideal.Quotient.field.proof_28
#check SimplicialObject.instCategorySplit.proof_5
#check ContinuousLinearMap.analyticAt_bilinear
#check NormedSpace.equicontinuous_TFAE
#check ValuationRing.instLinearOrderValueGroup.proof_6
#check MeasureTheory.condexpInd_smul'
#check IntermediateField.Lifts.upperBoundAlgHom.proof_4
#check Action.leftRegularTensorIso.proof_3
#check ContinuousLinearMap.op_norm_le_of_shell
#check IsAlgClosed.lift.SubfieldWithHom.instPreorderSubfieldWithHom.proof_3
#check CategoryTheory.ShortComplex.FunctorEquivalence.functor_map_app
#check CategoryTheory.instCategoryComonad.proof_8
#check DFinsupp.lsum.proof_7
#check CategoryTheory.functorCategoryPreadditive.proof_19
#check Zsqrtd.commRing.proof_13
#check CategoryTheory.MonoidalFunctor.mapAction.proof_10
#check CategoryTheory.Limits.Cocones.functoriality.proof_3
#check ZMod.instFieldZMod.proof_79
#check CategoryTheory.Comma.coneOfPreservesIsLimit.proof_2
#check IsPrimitiveRoot.zmodEquivZpowers.proof_4
#check iteratedFDeriv_succ_eq_comp_right
#check Types.monoOverEquivalenceSet.proof_11
#check AlgebraicGeometry.sectionInBasicOpen.proof_7
#check CategoryTheory.LaxMonoidalFunctor.mapMon.proof_7
#check LocalHomeomorph.MDifferentiable.range_mfderiv_eq_top
