import Mathlib
#check Rep.ihom.proof_7
#check CategoryTheory.functorCategoryLinear.proof_7
#check HasCompactSupport.hasFDerivAt_convolution_right
#check ContinuousLinearEquiv.image_symm_eq_preimage
#check Algebra.pushoutDesc.proof_4
#check CategoryTheory.FreeMonoidalCategory.project.proof_8
#check AddCircle.liftIco_eq_lift_Icc
#check CategoryTheory.discreteCategory.proof_13
#check Polynomial.degreeLTEquiv.proof_4
#check CategoryTheory.GradedObject.mapTrifunctor.proof_3
#check CategoryTheory.symmetricOfHasFiniteCoproducts.proof_5
#check CategoryTheory.ComposableArrows.homMk
#check SmoothMap.compLeftMonoidHom.proof_1
#check NonUnitalAlgHom.equalizer.proof_4
#check CochainComplex.mk.proof_1
#check ContinuousLinearMap.extend.proof_3
#check ValuationSubring.linearOrderOverring.proof_14
#check ContMDiffAt.coordChange
#check Bool.linearOrder.proof_6
#check ContinuousLinearMap.norm_iteratedFDerivWithin_le_of_bilinear
#check HomologicalComplex.homologicalComplexToDGO.proof_3
#check CategoryTheory.CommSq.leftAdjointLiftStructEquiv.proof_5
#check CategoryTheory.preadditiveCoyoneda.proof_4
#check ContinuousLinearMap.compContinuousMultilinearMapL.proof_8
#check CategoryTheory.Center.ofBraided.proof_8
#check PerfectClosure.lift.proof_5
#check ConditionallyCompleteLattice.copy.proof_12
#check CategoryTheory.GradedObject.isColimitCofan₃MapBifunctor₁₂BifunctorMapObj.proof_8
#check ContinuousLinearEquiv.symm_image_image
#check SmoothMap.ring.proof_24
#check HilbertBasis.hasSum_repr
#check LinearMap.exists_map_addHaar_eq_smul_addHaar'
#check CochainComplex.mappingCone.ext_from_iff
#check CategoryTheory.Limits.coneOfConeUncurry.proof_2
#check SmoothMap.semiring.proof_20
#check ContMDiffWithinAt.prod_mk
#check ContinuousLinearMap.mulLeftRight_isBoundedBilinear
#check FormalMultilinearSeries.compContinuousLinearMap_apply
#check CategoryTheory.curry_obj_map_app
#check CategoryTheory.Functor.mapDifferentialObject.proof_4
#check CategoryTheory.functorCategoryLinear.proof_6
#check CategoryTheory.evaluationRightAdjoint_map_app
#check MeasureTheory.LpToLpRestrictCLM_coeFn
#check ConditionallyCompleteLattice.copy.proof_11
#check Matrix.toLin_mul
#check ZMod.commRing.proof_23
#check WittVector.IsocrystalEquiv.mk.sizeOf_spec
#check fderiv_iteratedFDeriv
#check PEquiv.instSemilatticeInfPEquiv.proof_4
#check norm_iteratedFDerivWithin_clm_apply_const
#check LeftInvariantDerivation.left_invariant''
#check Real.commRing.proof_12
#check ZMod.commRing.proof_7
#check Submodule.Quotient.equiv.proof_9
#check Module.Baer.ExtensionOfMaxAdjoin.idealTo.proof_3
#check Zsqrtd.lift.proof_7
#check CategoryTheory.Idempotents.FunctorExtension₁.obj.proof_4
#check Perfection.map.proof_3
#check LinearPMap.instSubtractionCommMonoid.proof_6
#check SSet.Augmented.standardSimplex.proof_5
#check CategoryTheory.Pseudofunctor.comp.proof_3
#check AlgebraicGeometry.StructureSheaf.comap.proof_4
#check HomologicalComplex₂.flipFunctor.proof_3
#check ContinuousLinearEquiv.arrowCongrSL.proof_7
#check ContMDiffAt.prod_map
#check TensorProduct.AlgebraTensorModule.assoc.proof_24
#check LinearIsometryEquiv.norm_iteratedFDerivWithin_comp_left
#check CategoryTheory.sheafEquivSheafOfTypes.proof_9
#check AddMagma.FreeAddSemigroup.instAddSemigroupAssocQuotient.proof_3
#check ContinuousLinearEquiv.symm_trans_apply
#check ContinuousLinearEquiv.automorphismGroup.proof_7
#check Matrix.toLinOfInv.proof_7
#check AlgebraicGeometry.StructureSheaf.sectionsSubring.proof_3
#check HasStrictFDerivAt.implicitFunctionDataOfComplemented.proof_5
#check ModuleCat.semilinearMapAddEquiv.proof_6
#check SmoothMap.restrictAddMonoidHom.proof_2
#check Action.instPreadditiveActionInstCategoryAction.proof_14
#check GradedTensorProduct.mulHom_apply
#check ContDiffWithinAt.fderivWithin_apply
#check LinearIsometryEquiv.toLinearEquiv_trans
#check ConjAct.instMulDistribMulActionConjActToMonoidInstDivInvMonoidConjActToDivInvMonoid.proof_3
#check ContinuousLinearMap.extend.proof_4
#check ContinuousLinearMap.tendsto_birkhoffAverage_orthogonalProjection
#check LinearMap.toMatrix₂Aux_eq
#check DFinsupp.subtypeSupportEqEquiv.proof_4
#check AlgebraicGeometry.StructureSheaf.toOpen.proof_2
#check CategoryTheory.LaxBraidedFunctor.mapCommMonFunctor.proof_4
#check orthogonalProjection_tendsto_self
#check MeasureTheory.L1.setToL1_smul_left
#check CochainComplex.mappingCone.liftCochain_v_fst_v_assoc
#check Diffeomorph.contMDiffOn_diffeomorph_comp_iff
#check CategoryTheory.Functor.mapAction.proof_4
#check HilbertBasis.repr_self
#check AlgebraicGeometry.Scheme.affineCover.proof_8
#check TensorProduct.dualDistribEquivOfBasis_apply_apply
#check Magma.AssocQuotient.lift.proof_4
#check SchwartzMap.bilinLeftCLM.proof_9
#check Action.instPreadditiveActionInstCategoryAction.proof_3
#check ContinuousLinearEquiv.unitsEquivAut.proof_8
#check Zsqrtd.addCommGroup.proof_11
