#check LinearMap.coe_quotientInfToSupQuotient
#check ContinuousMap.toLp_denseRange
#check DoubleCentralizer.instAlgebra.proof_11
#check Subalgebra.iSupLift.proof_6
#check LocalizedModule.instAddCommGroupLocalizedModuleToAddCommMonoid.proof_4
#check Function.Injective.completeAtomicBooleanAlgebra.proof_3
#check ContinuousLinearEquiv.compContinuousMultilinearMapL.proof_19
#check ContMDiffAt.clm_postcomp
#check LieSubmodule.Quotient.actionAsEndoMap.proof_5
#check IsIntegralClosure.lift.proof_6
#check MonTypeEquivalenceMon.inverse.proof_7
#check CategoryTheory.Monoidal.MonFunctorCategoryEquivalence.Functor.obj.proof_6
#check CategoryTheory.Limits.Cones.whiskeringEquivalence.proof_5
#check Localization.instCommSemiringLocalizationToCommMonoid.proof_3
#check smoothFiberwiseLinear.proof_8
#check CategoryTheory.enrichedNatTransYonedaTypeIsoYonedaNatTrans.proof_5
#check AffineEquiv.trans.proof_3
#check MeasureTheory.condexp_ae_eq_condexpL1Clm
#check Rep.unitIso.proof_6
#check CategoryTheory.Cat.HasLimits.limitConeLift.proof_7
#check CategoryTheory.preadditiveCoyoneda.proof_5
#check MultilinearMap.curryFinFinset_apply_const
#check CategoryTheory.Limits.Cone.fromCostructuredArrow.proof_3
#check SmoothMap.addGroup.proof_13
#check Path.Homotopy.reflTransSymm.proof_4
