import Mathlib
#check SmoothMonoidMorphism.mk.sizeOf_spec
#check CategoryTheory.evaluationAdjunctionLeft.proof_7
#check ModuleCat.normalMono.proof_6
#check HomologicalComplex.singleMapHomologicalComplex.proof_7
#check CategoryTheory.Limits.pushoutPushoutRightIsPushout.proof_5
#check LinearMap.lsum.proof_4
#check ContinuousLinearMap.map_smul₂
#check CochainComplex.single₀IsoSingle.proof_6
#check CategoryTheory.Monad.algebraPreadditive.proof_14
#check CategoryTheory.Center.ofBraided.proof_7
#check HomologicalComplex.asFunctor.proof_4
#check ContinuousLinearMap.prodₗ_apply
#check Multiset.toFinsupp.proof_4
#check ZNum.linearOrderedCommRing.proof_18
#check CategoryTheory.transferNatTrans.proof_3
#check Trivialization.smoothWithinAt_iff
#check CategoryTheory.Pseudofunctor.mkOfOplax'.proof_5
#check Bundle.ContinuousLinearMap.vectorPrebundle.proof_11
#check Finsupp.lsum.proof_4
#check CompleteLattice.independent_iff_dfinsupp_lsum_injective
#check IsAdjoinRootMonic.basis.proof_5
#check CategoryTheory.Functor.Initial.extendCone.proof_4
#check CategoryTheory.LiftAdjoint.constructLeftAdjointEquiv_symm_apply
#check CategoryTheory.curryObj.proof_5
#check CategoryTheory.Limits.pushoutPushoutLeftIsPushout.proof_8
#check BoundedContinuousFunction.semilatticeInf.proof_6
#check CategoryTheory.LaxMonoidalFunctor.mapMon_map_hom
#check VectorBundleCore.mk.inj
#check MeasureTheory.condexpL1Clm_indicatorConstLp
#check SmoothAt.prod_map
#check DoubleCentralizer.instAlgebra.proof_7
#check completeLatticeOfSup.proof_8
#check Mon_.monMonoidal.proof_9
#check SmoothMap.compLeftRingHom.proof_8
#check AlgebraicGeometry.morphismRestrictRestrictBasicOpen
#check BoundedContinuousFunction.toLp_denseRange
#check FiberwiseLinear.localHomeomorph.proof_8
#check Perfection.lift.proof_6
#check DoubleCentralizer.coeHom.proof_7
#check Rep.homEquiv.proof_6
#check StarAlgHom.injective_codRestrict
#check MultilinearMap.curryFinFinset_symm_apply_piecewise_const
#check CategoryTheory.whiskeringLeft.proof_4
#check gelfandStarTransform_symm_apply
#check LinearIsometryEquiv.mk.sizeOf_spec
#check Subgroup.instMulActionElemSetLeftTransversalsCoeSubgroupInstSetLikeSubgroupToMonoidToDivInvMonoid.proof_2
#check RingSubgroupsBasis.toRingFilterBasis.proof_7
#check LinearMap.lsum.proof_5
#check SmoothMap.compLeftRingHom.proof_9
#check ChainComplex.fromSingle₀Equiv.proof_2
#check preordCatToPartOrdCatForgetAdjunction.proof_6
#check CategoryTheory.CategoryOfElements.fromCostructuredArrow.proof_3
#check CategoryTheory.FreeBicategory.lift.proof_3
#check CategoryTheory.uncurry.proof_3
#check CategoryTheory.Limits.Cocones.functorialityEquivalence.proof_5
#check Bundle.ContinuousLinearMap.memTrivializationAtlas.proof_1
#check PerfectClosure.lift.proof_7
#check StarAlgEquiv.ofInjective_symm_apply
#check NonUnitalStarSubalgebra.iSupLift_of_mem
#check AffineSubspace.isometryEquivMap.coe_apply
#check MeasureTheory.condexpL2_indicator_eq_toSpanSingleton_comp
#check Real.commRing.proof_8
#check CategoryTheory.ShortComplex.FunctorEquivalence.inverse.proof_5
#check CategoryTheory.Limits.preservesEqualizersOfPreservesPullbacksAndBinaryProducts.proof_4
#check SmoothMap.ring.proof_22
#check Trivialization.continuousLinearEquivAt_symm_apply
#check Equiv.Set.rangeSplittingImageEquiv.proof_5
#check ZMod.instFieldZMod.proof_83
#check HasMFDerivAt.comp
#check CategoryTheory.Functor.Final.extendCocone_map_Hom
#check RatFunc.instFieldRatFunc.proof_9
#check CategoryTheory.ModuleCat.RestrictionCoextensionAdj.HomEquiv.fromRestriction.proof_4
#check RatFunc.instAddCommGroup.proof_7
#check RingSubgroupsBasis.toRingFilterBasis.proof_8
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_nonneg
#check TensorProduct.AlgebraTensorModule.uncurry.proof_3
#check Mod_.comap.proof_5
#check CategoryTheory.Functor.mapAction.proof_3
#check LocalizedModule.instAddCommGroupLocalizedModuleToAddCommMonoid.proof_5
#check CategoryTheory.Triangulated.Octahedron.mk.injEq
#check MeasureTheory.Filtration.instCompleteLattice.proof_14
#check LocalizedModule.instSemiringLocalizedModuleToAddCommMonoidToNonUnitalNonAssocSemiringToNonAssocSemiringToModule.proof_5
#check Trivialization.prod_apply
#check Homotopy.equivSubZero.proof_5
#check fderivWithin_fderivWithin
#check ContinuousAddMonoidHom.instAddCommGroupContinuousAddMonoidHomToAddMonoidToSubNegAddMonoidToAddGroup.proof_13
#check Perfection.lift.proof_4
#check ContinuousLinearEquiv.map_smulₛₗ
#check ContinuousMultilinearMap.curryFinFinset_symm_apply
#check Mon_.EquivLaxMonoidalFunctorPUnit.counitIso.proof_7
#check ContinuousLinearMap.apply_norm_eq_sqrt_inner_adjoint_left
#check NonUnitalAlgHom.toAlgHom.proof_5
#check AlgebraicGeometry.Scheme.OpenCover.gluedCover.proof_10
#check Function.Injective.divisionRing.proof_2
#check CategoryTheory.SimplicialObject.Augmented.whiskering.proof_3
#check TensorProduct.AlgebraTensorModule.leftComm_tmul
#check ValuationRing.linearOrderedCommGroupWithZero.proof_9
#check LinearEquiv.automorphismGroup.proof_13
#check CategoryTheory.Monoidal.MonFunctorCategoryEquivalence.Functor.obj.proof_7
#check SchwartzMap.mkLM
