#check HasStrictFDerivAt.implicitToLocalHomeomorph_apply_ker
#check Submodule.iSup_eq_range_dfinsupp_lsum
#check ContinuousLinearMap.adjointAux_apply
#check ContinuousLinearMap.postcomp_apply
#check ContinuousLinearEquiv.image_symm_image
#check Function.Injective.kleeneAlgebra.proof_4
#check CategoryTheory.Pseudofunctor.mk.inj
#check CategoryTheory.SimplicialObject.Augmented.whiskering.proof_4
#check ContinuousLinearMap.prodₗᵢ.proof_9
#check MeasureTheory.L1.setToL1_congr_left'
#check Matrix.kroneckerTMul_assoc'
#check CategoryTheory.linearYoneda.proof_5
#check BoundedContinuousFunction.semilatticeSup.proof_6
#check ContinuousLinearEquiv.arrowCongrSL.proof_6
#check CategoryTheory.Pi.sum_map_app
#check homology.map_eq_desc'_lift_left
#check MeasureTheory.setToFun_eq
#check Perfection.lift.proof_7
#check mkFactorOrderIsoOfFactorDvdEquiv.proof_6
#check Field.DirectLimit.field.proof_41
#check Ordinal.monoid.proof_3
#check CategoryTheory.functorCategoryPreadditive.proof_18
#check CategoryTheory.Pseudofunctor.mkOfOplax'.proof_3
#check LeftInvariantDerivation.instZeroLeftInvariantDerivation.proof_2
#check HasStrictFDerivAt.clm_comp
#check Homotopy.mkInductive.proof_2
#check Ring.DirectLimit.of.zero_exact_aux2
#check PerfectClosure.PerfectClosure.addCommGroup.proof_10
#check LinearMap.toMatrix_reindexRange
#check OreLocalization.universalMulHom.proof_3
#check MeasureTheory.lpMeasToLpTrimLie_symm_indicator
#check CategoryTheory.LiftAdjoint.counitCoequalises.proof_3
#check MeasureTheory.lintegral_nnnorm_condexpL2_le
#check CategoryTheory.equivEssImageOfReflective.proof_4
#check ZMod.instFieldZMod.proof_90
#check ChainComplex.single₀IsoSingle.proof_5
#check TensorProduct.AlgebraTensorModule.assoc.proof_18
#check ModuleCat.HasLimits.limitConeIsLimit.proof_4
#check MeasureTheory.Lp.simpleFunc.module.proof_6
#check BoxIntegral.HasIntegral.mcShane_of_forall_isLittleO
#check MeasureTheory.AEStronglyMeasurable.convolution_integrand_snd
#check Cardinal.commSemiring.proof_10
#check LinearIsometry.norm_iteratedFDerivWithin_comp_left
#check CategoryTheory.algebraEquivUnder.proof_5
#check CategoryTheory.Monad.MonadicityInternal.comparisonAdjunction_counit
#check AlgebraicGeometry.structurePresheafInCommRing.proof_5
#check ContinuousLinearMap.coe_restrict_scalarsL'
#check AffineIsometryEquiv.mk.sizeOf_spec
#check LinearMap.mul_toMatrix₂_mul
#check ContinuousLinearEquiv.automorphismGroup.proof_11
#check ValuationRing.linearOrderedCommGroupWithZero.proof_17
#check AlgebraicGeometry.ProjectiveSpectrum.StructureSheaf.structurePresheafInCommRing.proof_5
#check Lattice.copy.proof_10
#check CategoryTheory.ModuleCat.ExtendRestrictScalarsAdj.HomEquiv.toRestrictScalars.proof_2
#check AlgHom.restrictNormalAux.proof_5
#check CategoryTheory.Discrete.monoidalFunctorComp.proof_8
#check SmoothMap.group.proof_14
#check TensorProduct.LieModule.coe_liftLie_eq_lift_coe
#check CategoryTheory.whiskeringRight₂_obj_map_app_app
#check Num.commSemiring.proof_7
#check StructureGroupoid.LocalInvariantProp.localPredicate.proof_2
#check mfderiv_comp
#check CategoryTheory.Idempotents.KaroubiUniversal₁.counitIso.proof_9
#check DirectSum.IsInternal.isometryL2OfOrthogonalFamily.proof_5
#check ModuleCat.Colimits.instAddCommGroupColimitType.proof_14
#check CategoryTheory.functorCategoryLinear.proof_4
#check MeasureTheory.aeStronglyMeasurable'_condexpL2
#check SmoothMap.group.proof_15
#check Ideal.quotientRangePowQuotSuccInclusionEquiv
#check LinearMap.prodEquiv_symm_apply
#check CategoryTheory.Comma.mapLeftComp.proof_6
#check Basis.algebraMapCoeffs_repr_apply_support_val
#check HasStrictFDerivAt.mem_implicitToLocalHomeomorphOfComplemented_target
#check ContinuousLinearMap.adjoint_inner_right
#check ContinuousLinearEquiv.skewProd.proof_4
#check CategoryTheory.Limits.cokernelImageι.proof_4
#check iteratedFDerivWithin_succ_eq_comp_right
#check Trivialization.contMDiffWithinAt_iff
#check CategoryTheory.Limits.coconeEquivalenceOpConeOp.proof_11
#check Real.commRing.proof_11
#check CategoryTheory.Monad.comparison.proof_5
#check HasStrictFDerivAt.map_implicitFunctionOfComplemented_eq
#check ContinuousLinearMap.inCoordinates_eq
#check CategoryTheory.linearYoneda.proof_4
#check CategoryTheory.Cat.HasLimits.instCategoryLimitTypeTypesCompCatCategoryObjectsHasLimitSmall_self.proof_8
#check ContMDiff.cle_arrowCongr
#check DoubleCentralizer.instAlgebra.proof_9
#check MonoidAlgebra.liftMagma.proof_5
#check Field.DirectLimit.field.proof_14
#check ContinuousLinearEquiv.comp_right_differentiableAt_iff
#check ContinuousMultilinearMap.piLinearEquiv_symm_apply
#check CommRingCat.Colimits.instCommRingColimitType.proof_10
#check Submodule.equivSubtypeMap.proof_6
#check Action.ofMulActionLimitCone.proof_3
#check CategoryTheory.Functor.mapHomologicalComplex.proof_5
#check SmoothAt.coordChange
#check TopCat.GlueData.MkCore.t'.proof_5
#check Trivialization.symm_apply_eq_mk_continuousLinearEquivAt_symm
#check CategoryTheory.isColimitOfEffectiveEpiFamilyStruct.proof_4
#check fderiv_inv'
