import Mathlib
#check Submodule.Quotient.equiv.proof_9
#check MvPFunctor.M.corecContents.proof_3
#check Module.Baer.ExtensionOfMaxAdjoin.idealTo.proof_3
#check Zsqrtd.lift.proof_7
#check CategoryTheory.Idempotents.FunctorExtension₁.obj.proof_4
#check CategoryTheory.instBicategoryMonoidalSingleObj.proof_11
#check Mon_.monMonoidal.proof_3
#check Perfection.map.proof_3
#check LinearPMap.instSubtractionCommMonoid.proof_6
#check CategoryTheory.Pseudofunctor.comp.proof_3
#check AlgebraicGeometry.StructureSheaf.comap.proof_4
#check ContinuousLinearEquiv.arrowCongrSL.proof_7
#check ContMDiffAt.prod_map
#check MultilinearMap.curryFinFinset_symm_apply_const
#check LinearIsometryEquiv.norm_iteratedFDerivWithin_comp_left
#check CategoryTheory.sheafEquivSheafOfTypes.proof_9
#check AddMagma.FreeAddSemigroup.instAddSemigroupAssocQuotient.proof_3
#check ContinuousLinearEquiv.symm_trans_apply
#check CategoryTheory.functorCategoryPreadditive.proof_11
#check ContinuousLinearEquiv.automorphismGroup.proof_7
#check Matrix.toLinOfInv.proof_7
#check AlgebraicGeometry.StructureSheaf.sectionsSubring.proof_3
#check LocalHomeomorph.MDifferentiable.ker_mfderiv_eq_bot
#check HasStrictFDerivAt.implicitFunctionDataOfComplemented.proof_5
#check ChainComplex.single₀.proof_4
#check ContinuousMultilinearMap.currySumEquiv.proof_14
#check SmoothMap.restrictAddMonoidHom.proof_2
#check Action.instPreadditiveActionInstCategoryAction.proof_14
#check ContDiffWithinAt.fderivWithin_apply
#check LinearIsometryEquiv.toLinearEquiv_trans
#check ConjAct.instMulDistribMulActionConjActToMonoidInstDivInvMonoidConjActToDivInvMonoid.proof_3
#check LinearMap.toMatrix₂Aux_eq
#check DFinsupp.subtypeSupportEqEquiv.proof_4
#check AlgebraicGeometry.StructureSheaf.toOpen.proof_2
#check CategoryTheory.LaxBraidedFunctor.mapCommMonFunctor.proof_4
#check orthogonalProjection_tendsto_self
#check MeasureTheory.L1.setToL1_smul_left
#check Diffeomorph.contMDiffOn_diffeomorph_comp_iff
#check CategoryTheory.Functor.mapAction.proof_4
#check HilbertBasis.repr_self
#check AlgebraicGeometry.Scheme.affineCover.proof_8
#check TensorProduct.dualDistribEquivOfBasis_apply_apply
#check MultilinearMap.curryLeft.proof_4
#check Magma.AssocQuotient.lift.proof_4
#check SchwartzMap.bilinLeftCLM.proof_9
#check Action.instPreadditiveActionInstCategoryAction.proof_3
#check ContinuousLinearEquiv.unitsEquivAut.proof_8
#check DFinsupp.sumAddHom.proof_2
#check CategoryTheory.Idempotents.KaroubiKaroubi.counitIso.proof_8
#check AddCommGroupCat.binaryProductLimitCone.proof_3
#check WittVector.lift.proof_3
#check ContinuousLinearEquiv.comp_right_hasFDerivAt_iff'
#check CategoryTheory.hasShiftMk.proof_7
#check hfdifferential.proof_5
#check HilbertBasis.coe_mkOfOrthogonalEqBot
#check CategoryTheory.DifferentialObject.shiftFunctor.proof_4
#check Pretrivialization.continuousLinearMap.isLinear
#check IsAdjoinRootMonic.basis.proof_4
#check TensorProduct.Algebra.moduleAux.proof_7
#check VectorPrebundle.IsSmooth.exists_smoothCoordChange
#check MeasureTheory.norm_condexpL2_coe_le
#check CategoryTheory.ModuleCat.CoextendScalars.hasSMul.proof_2
#check LeftInvariantDerivation.mk.injEq
#check SmoothMap.module'.proof_3
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_16
#check LinearMap.coe_quotientInfToSupQuotient
#check ContinuousMap.toLp_denseRange
#check DoubleCentralizer.instAlgebra.proof_11
#check Subalgebra.iSupLift.proof_6
#check LocalizedModule.instAddCommGroupLocalizedModuleToAddCommMonoid.proof_4
#check Function.Injective.completeAtomicBooleanAlgebra.proof_3
#check ContinuousLinearEquiv.compContinuousMultilinearMapL.proof_19
#check ContMDiffAt.clm_postcomp
#check IsIntegralClosure.lift.proof_6
#check MonTypeEquivalenceMon.inverse.proof_7
#check CategoryTheory.Monoidal.MonFunctorCategoryEquivalence.Functor.obj.proof_6
#check CategoryTheory.Limits.Cones.whiskeringEquivalence.proof_5
#check Localization.instCommSemiringLocalizationToCommMonoid.proof_3
#check smoothFiberwiseLinear.proof_8
#check CategoryTheory.enrichedNatTransYonedaTypeIsoYonedaNatTrans.proof_5
#check AffineEquiv.trans.proof_3
#check MeasureTheory.condexp_ae_eq_condexpL1Clm
#check Rep.unitIso.proof_6
#check CategoryTheory.Cat.HasLimits.limitConeLift.proof_7
#check CategoryTheory.preadditiveCoyoneda.proof_5
#check MultilinearMap.curryFinFinset_apply_const
#check CategoryTheory.Limits.Cone.fromCostructuredArrow.proof_3
#check SmoothMap.addGroup.proof_13
#check Path.Homotopy.reflTransSymm.proof_4
