#check MeasureTheory.set_lintegral_nnnorm_condexpL2_indicator_le
#check ZMod.commRing.proof_11
#check CategoryTheory.Limits.Cone.fromCostructuredArrow.proof_2
#check AlgebraicTopology.DoldKan.Γ₂N₁.natTrans.proof_3
#check CategoryTheory.Functor.Initial.extendCone_map_Hom
#check Trivialization.smoothAt_iff
#check WittVector.IsocrystalEquiv.mk.injEq
#check ZMod.commRing.proof_24
#check SchwartzMap.evalCLM.proof_8
#check ContMDiffAt.clm_precomp
#check CategoryTheory.Center.ofBraided.proof_6
#check SubmodulesBasis.toModuleFilterBasis.proof_4
#check CategoryTheory.Ran.equiv.proof_4
#check FiberBundleCore.trivChange.proof_7
#check LinearMap.toMatrix₂_compl₂
#check RingQuot.starRing.proof_2
#check LinearEquiv.ofSubmodule'_symm_apply
#check CategoryTheory.Pseudofunctor.comp.proof_5
#check CategoryTheory.Over.iteratedSliceEquiv.proof_6
#check VectorPrebundle.coordChange.proof_2
#check IsDedekindDomain.selmerGroup.proof_4
#check StarAlgHomClass.ext_topologicalClosure
#check Trivialization.coordChangeL_apply'
#check StarAlgEquiv.ofLeftInverse'_apply
#check LinearEquiv.arrowCongr.proof_8
#check ContinuousLinearMap.fderivWithin_of_bilinear
#check LinearPMap.adjointDomain.proof_5
#check SmoothMap.restrictMonoidHom.proof_2
#check SmoothOn.prod_map
#check CliffordAlgebra.even.ι.proof_6
#check Diffeomorph.coe_trans
#check CategoryTheory.Monad.algebraPreadditive.proof_18
#check TensorProduct.tensorTensorTensorAssoc_symm_tmul
#check homology.map_eq_lift_desc'_left
#check ContinuousLinearEquiv.map_tsum
#check CategoryTheory.Over.ConstructProducts.conesEquivFunctor.proof_5
#check HomologicalComplex.flip.proof_4
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_19
#check smoothOn_continuousLinearMapCoordChange
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_11
#check Submodule.completeLattice.proof_9
#check CategoryTheory.Limits.IsLimit.homIso'.proof_3
#check iteratedFDerivWithin_succ_eq_comp_left
#check AlgebraicGeometry.StructureSheaf.sectionsSubring.proof_5
#check ModuleCat.binaryProductLimitCone.proof_3
#check AlgebraicGeometry.PresheafedSpace.componentwiseDiagram.proof_3
#check Mod_.comap.proof_3
#check CategoryTheory.coyonedaPreservesLimits.proof_2
#check ContinuousLinearEquiv.arrowCongrSL
#check Complex.integral_boundary_rect_of_differentiableOn_real
#check Matrix.toLinearMap₂_apply
#check IntermediateField.Lifts.upperBoundAlgHom.proof_7
#check TopCommRingCat.instCategoryTopCommRingCat.proof_4
#check HilbertBasis.coe_mk
#check CategoryTheory.Monad.algebraPreadditive.proof_8
#check RingQuot.liftAlgHom_mkAlgHom_apply
#check LieModule.coe_maxTrivLinearMapEquivLieModuleHom_symm
#check SymplecticGroup.instGroupSubtypeMatrixSumMemSubmonoidToMulOneClassToMulZeroOneClassNonAssocSemiringToNonAssocSemiringToSemiringToCommSemiringInstFintypeSumInstDecidableEqSumInstMembershipInstSetLikeSubmonoidSymplecticGroup.proof_19
#check Finsupp.basis.proof_2
#check MultilinearMap.domDomCongrLinearEquiv'.proof_6
#check LeftInvariantDerivation.instSubLeftInvariantDerivation.proof_3
#check ContinuousLinearMap.aestronglyMeasurable_comp₂
#check Subspace.coe_prodEquivOfClosedCompl
#check CategoryTheory.Pi.sum.proof_3
#check ContinuousMultilinearMap.curryFinFinset_apply
#check ZNum.addCommGroup.proof_8
#check ContinuousLinearMap.flipMultilinear_apply_apply
#check MeasureTheory.Measure.MapLinearEquiv.isAddHaarMeasure.proof_1
#check VectorPrebundle.mk_smoothCoordChange
#check CategoryTheory.yonedaPreservesLimits.proof_2
#check CategoryTheory.OplaxFunctor.comp.proof_1
#check Representation.linHom.proof_5
#check CategoryTheory.evaluation.proof_5
#check FirstOrder.Language.DirectLimit.lift.proof_4
#check ContMDiffWithinAt.clm_apply
#check hfdifferential.proof_4
#check TopCat.Presheaf.SheafConditionPairwiseIntersections.coneEquivCounitIso.proof_4
#check Finsupp.lsum.proof_7
#check RingSubgroupsBasis.toRingFilterBasis.proof_9
#check IsDedekindDomain.HeightOneSpectrum.instAlgebraSubtypeAdicCompletionMemValuationSubringInstFieldAdicCompletionInstMembershipInstSetLikeValuationSubringAdicCompletionIntegersToCommSemiringToSemiringToSemiringToRingToDivisionRingToSubsemiringToSubring.proof_4
#check HasStrictFDerivAt.to_implicitFunction
#check AlgebraicGeometry.ProjIsoSpecTopComponent.ToSpec.MemCarrier.clear_denominator
#check Set.unitEquivUnitsInteger.proof_9
#check CategoryTheory.Functor.mapDifferentialObject_map_f
#check FiberBundleCore.localTriv.proof_6
#check SmoothMap.module'.proof_5
#check Diffeomorph.symm_trans'
#check Function.Injective.field.proof_3
#check ContinuousLinearEquiv.arrowCongrSL.proof_10
#check elementalStarAlgebra.starAlgHomClass_ext
#check MvPowerSeries.map.proof_4
#check CategoryTheory.ModuleCat.ExtendRestrictScalarsAdj.Counit.map.proof_5
#check SmoothMap.smul_comp
#check SmoothFiberwiseLinear.locality_aux₂
#check ChainComplex.mk_d_1_0
#check Submodule.fstEquiv.proof_5
#check HomologicalComplex.flipObj.proof_5
#check SmoothBumpCovering.exists_immersion_euclidean
#check WeakDual.gelfandTransform_apply_apply
#check Trivialization.coordChangeL_apply
