#check CategoryTheory.ModuleCat.restrictCoextendScalarsAdj.proof_4
#check MeasureTheory.L1.setToL1_mono_left'
#check CliffordAlgebra.lift.proof_4
#check homTensorHomEquiv_apply
#check CategoryTheory.CosimplicialObject.equivalenceRightToLeft.proof_4
#check Module.End.divisionRing.proof_30
#check apply_fdifferential
#check MvPowerSeries.map.proof_3
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_congr_left'
#check AlgebraicGeometry.scheme_restrict_basicOpen_of_localizationPreserves
#check Trivialization.continuousLinearEquivAt_apply'
#check CochainComplex.single₀.proof_5
#check Algebra.leftMulMatrix.proof_4
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_8
#check homology.mapIso.proof_4
#check IntermediateField.instPartialOrderLifts.proof_4
#check Submodule.equivSubtypeMap.proof_5
#check CategoryTheory.Monad.algebraPreadditive.proof_4
#check CategoryTheory.effectiveEpiFamilyStructOfIsColimit.proof_4
#check CategoryTheory.Comonad.coalgebraPreadditive.proof_17
#check UniversalEnvelopingAlgebra.lift.proof_3
#check CategoryTheory.effectiveEpiStructOfIsColimit.proof_3
#check ContinuousLinearMap.IsPositive.conj_adjoint
#check CategoryTheory.Over.ConstructProducts.conesEquivCounitIso.proof_5
#check Matrix.toLin_mul_apply
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_17
#check CategoryTheory.Limits.IsColimit.homIso'.proof_4
#check Poly.instAddCommGroupPoly.proof_10
#check ContinuousLinearEquiv.symm_preimage_preimage
#check CategoryTheory.FreeMonoidalCategory.project.proof_7
#check adicCompletion.proof_2
#check CategoryTheory.Cat.HasLimits.instCategoryLimitTypeTypesCompCatCategoryObjectsHasLimitSmall_self.proof_10
#check GromovHausdorff.instMetricSpaceGHSpace.proof_22
#check norm_iteratedFDeriv_clm_apply
#check AddSubmonoid.LocalizationMap.lift.proof_3
#check SchwartzMap.bilinLeftCLM.proof_7
#check CategoryTheory.SimplicialObject.equivalenceLeftToRight.proof_4
#check AffineMap.instAddTorsorAffineMapAddGroupIsAddTorsorToAddGroupAffineMapToAddGroupInstAddCommGroupAffineMapAddGroupIsAddTorsorToAddGroup.proof_6
#check ValuationSubring.decompositionSubgroupMulSemiringAction.proof_5
#check Ordinal.partialOrder.proof_6
#check SmoothMap.restrictAddMonoidHom.proof_3
#check ContinuousLinearMap.map_add_add
#check Function.Injective.kleeneAlgebra.proof_3
#check Ideal.quotientToQuotientRangePowQuotSucc_surjective
#check SmoothMap.addGroup.proof_12
#check CategoryTheory.Subgroupoid.coe.proof_7
#check CategoryTheory.LaxMonoidalFunctor.mapMon.proof_5
#check ValuationRing.linearOrderedCommGroupWithZero.proof_6
#check tendsto_integral_exp_smul_cocompact
#check CategoryTheory.StructuredArrow.post.proof_3
#check TopCat.Presheaf.SheafConditionPairwiseIntersections.coneEquivInverse.proof_2
#check GromovHausdorff.instMetricSpaceGHSpace.proof_21
#check CategoryTheory.CechNerveTerminalFrom.wideCospan.limitCone.proof_4
#check StarAlgEquiv.ofLeftInverse'.proof_4
#check ContinuousMonoidHom.instCommGroupContinuousMonoidHomToMonoidToDivInvMonoidToGroup.proof_13
#check ContinuousLinearEquiv.compContinuousMultilinearMapL_apply
#check fderiv_clm_apply
#check CategoryTheory.evaluationLeftAdjoint.proof_9
#check MeasureTheory.L1.setToL1_smul_left'
#check HeytingHom.copy.proof_4
#check Function.Injective.orderedRing.proof_1
#check continuousMultilinearCurryRightEquiv.proof_17
#check LinearMap.flip.proof_5
#check SmoothMonoidMorphism.mk.sizeOf_spec
#check CategoryTheory.evaluationAdjunctionLeft.proof_7
#check ModuleCat.normalMono.proof_6
#check HomologicalComplex.singleMapHomologicalComplex.proof_7
#check CategoryTheory.Limits.pushoutPushoutRightIsPushout.proof_5
#check LinearMap.lsum.proof_4
#check ContinuousLinearMap.map_smul₂
#check CochainComplex.single₀IsoSingle.proof_6
#check CategoryTheory.Monad.algebraPreadditive.proof_14
#check CategoryTheory.Center.ofBraided.proof_7
#check HomologicalComplex.asFunctor.proof_4
#check ContinuousLinearMap.prodₗ_apply
#check ZNum.linearOrderedCommRing.proof_18
#check CategoryTheory.transferNatTrans.proof_3
#check Trivialization.smoothWithinAt_iff
#check CategoryTheory.Pseudofunctor.mkOfOplax'.proof_5
#check Bundle.ContinuousLinearMap.vectorPrebundle.proof_11
#check Finsupp.lsum.proof_4
#check CompleteLattice.independent_iff_dfinsupp_lsum_injective
#check IsAdjoinRootMonic.basis.proof_5
#check CategoryTheory.Functor.Initial.extendCone.proof_4
#check CategoryTheory.LiftAdjoint.constructLeftAdjointEquiv_symm_apply
#check CategoryTheory.curryObj.proof_5
#check CategoryTheory.Limits.pushoutPushoutLeftIsPushout.proof_8
#check BoundedContinuousFunction.semilatticeInf.proof_6
#check CategoryTheory.LaxMonoidalFunctor.mapMon_map_hom
#check VectorBundleCore.mk.inj
#check MeasureTheory.condexpL1Clm_indicatorConstLp
#check SmoothAt.prod_map
#check DoubleCentralizer.instAlgebra.proof_7
#check completeLatticeOfSup.proof_8
#check Mon_.monMonoidal.proof_9
#check SmoothMap.compLeftRingHom.proof_8
#check AlgebraicGeometry.morphismRestrictRestrictBasicOpen
#check BoundedContinuousFunction.toLp_denseRange
#check LieAlgebra.rootSpaceWeightSpaceProduct.proof_3
#check FiberwiseLinear.localHomeomorph.proof_8
