import Mathlib
#check ContinuousMultilinearMap.alternatization.proof_6
#check UniformSpace.separationSetoid.uniformSpace.proof_4
#check TopCat.GlueData.ofOpenSubsets_toGlueData_f
#check SemiRingCat.HasLimits.limitConeIsLimit.proof_6
#check CategoryTheory.TwoSquare.EquivalenceJ.functor_map
#check HasFDerivWithinAt.clm_comp
#check Surreal.orderedAddCommGroup.proof_6
#check smoothPresheafAddGroup.proof_3
#check CategoryTheory.Limits.IsColimit.homIso'.proof_3
#check ContinuousLinearMap.postcomp.proof_7
#check CategoryTheory.categoryOfElements.proof_4
#check QuaternionGroup.instGroupQuaternionGroup.proof_2
#check ValuationRing.linearOrderedCommGroupWithZero.proof_7
#check SetTheory.Game.instAddCommGroupWithOneGame.proof_11
#check CategoryTheory.ComposableArrows.homMkSucc.proof_10
#check BoxIntegral.HasIntegral.of_le_Henstock_of_forall_isLittleO
#check NumberField.mixedEmbedding.fractionalIdealLatticeBasis.proof_8
#check CategoryTheory.Discrete.monoidalFunctor.proof_12
#check Set.unitEquivUnitsInteger.proof_8
#check Cardinal.commSemiring.proof_12
#check CategoryTheory.hasShiftMk.proof_6
#check CategoryTheory.GradedObject.ι_mapBifunctorComp₁₂MapObjIso_hom
#check SimpleGraph.completeAtomicBooleanAlgebra.proof_24
#check HasMFDerivAt.comp_hasMFDerivWithinAt
#check TopCat.GlueData.ofOpenSubsets_toGlueData_t
#check LinearIsometryEquiv.trans_apply
#check PerfectClosure.lift.proof_6
#check CochainComplex.mappingCone.liftCochain_v_fst_v
#check ContinuousLinearMap.precomp_toFun
#check LocalizedModule.divBy.proof_3
#check MeasureTheory.withDensitySMulLI.proof_5
#check SignType.instCommGroupWithZeroSignType.proof_13
#check AlgebraicTopology.DoldKan.Γ₂_map_f_app
#check HomologicalComplex.isLimitOfEval.proof_3
#check FiniteDimensional.basisSingleton.proof_7
#check CategoryTheory.Idempotents.functorExtension₂CompWhiskeringLeftToKaroubiIso.proof_6
#check HomologicalComplex.single.proof_5
#check AddMonoidAlgebra.decomposeAux.proof_4
#check LinearMap.toMatrix₂_compl₁₂
#check PresheafOfModules.Hom.instAddCommGroupHomPresheafOfModulesToQuiverToCategoryStructInstCategoryPresheafOfModules.proof_10
#check QuotientAddGroup.circularOrder.proof_2
#check CategoryTheory.Limits.kernelOrderHom.proof_4
#check CharacterModule.curry.proof_5
#check IccRightChart.proof_10
#check CategoryTheory.MonoidalOpposite.unmopBraidedFunctor.proof_8
#check ModuleCat.ExtendRestrictScalarsAdj.HomEquiv.fromExtendScalars.proof_5
#check AlgebraicClosure.toStepOfLE.proof_4
#check CategoryTheory.Limits.Types.binaryProductFunctor.proof_5
#check CategoryTheory.Monoidal.functorHasLeftDual.proof_6
#check Cardinal.commSemiring.proof_7
#check CategoryTheory.ComposableArrows.isoMk₄.proof_38
#check CategoryTheory.Limits.combineCones.proof_4
#check Homotopy.mkInductive.proof_1
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_4
#check SmoothMap.group.proof_7
#check LinearIsometry.map_orthogonalProjection'
#check Function.Injective.field.proof_14
#check Algebra.TensorProduct.opAlgEquiv.proof_9
#check AffineSubspace.directionOfNonempty.proof_3
#check CategoryTheory.ComposableArrows.homMkSucc
#check CategoryTheory.subterminalsEquivMonoOverTerminal.proof_9
#check CategoryTheory.Pretriangulated.TriangleOpEquivalence.inverse.proof_5
#check Filter.Realizer.bind.proof_5
#check CategoryTheory.ComposableArrows.homMk_app
#check TopCat.GlueData.ofOpenSubsets.proof_6
#check CategoryTheory.Limits.HasLimitOfHasProductsOfHasEqualizers.buildIsLimit.proof_3
#check ModuleCat.monModuleEquivalenceAlgebra.proof_11
#check CategoryTheory.TwoSquare.EquivalenceJ.functor.proof_2
#check GradedRing.projZeroRingHom.proof_4
#check Real.commRing.proof_14
#check CategoryTheory.instFullAlgebraEilenbergMooreToMonadFreeForgetAdjComparison.proof_2
#check CategoryTheory.Monoidal.fromInduced.proof_6
#check CategoryTheory.MonoOver.imageForgetAdj.proof_8
#check ContinuousLinearMap.prodMapL.proof_33
#check Real.commRing.proof_10
#check CommRingCat.Colimits.instCommRingColimitType.proof_8
#check LieModule.maxTrivHom.proof_3
#check CategoryTheory.Triangulated.Octahedron.ofIso.proof_5
#check SimplicialObject.instCategorySplit.proof_5
#check CategoryTheory.bifunctorComp₂₃.proof_3
#check CategoryTheory.ShortComplex.FunctorEquivalence.functor_map_app
#check DFinsupp.lsum.proof_7
#check CategoryTheory.Limits.Cocones.functoriality.proof_3
#check CategoryTheory.Comma.coneOfPreservesIsLimit.proof_2
#check AlgebraicGeometry.morphismRestrictRestrict.proof_11
#check Function.Injective.field.proof_23
#check CategoryTheory.constantPresheafAdj.proof_4
#check PartialHomeomorph.MDifferentiable.range_mfderiv_eq_top
#check Types.monoOverEquivalenceSet.proof_11
#check CategoryTheory.GradedObject.ι_mapBifunctorComp₁₂MapObjIso_inv_assoc
#check AlgebraicGeometry.sectionInBasicOpen.proof_7
#check CategoryTheory.LaxMonoidalFunctor.mapMon.proof_7
#check homology'.map_comp
#check CategoryTheory.effectiveEpiFamilyStructOfIsColimit.proof_3
#check CategoryTheory.Functor.flip.proof_5
#check CategoryTheory.Monoidal.CommMonFunctorCategoryEquivalence.counitIso.proof_7
#check LieAlgebra.coe_rootSpaceWeightSpaceProduct_tmul
#check CategoryTheory.OplaxFunctor.mk.inj
#check TopCat.Presheaf.SheafConditionPairwiseIntersections.isLimitSheafConditionForkOfIsLimitMapCone.proof_3
#check ContMDiff.clm_postcomp
