import Mathlib
#check ModuleCat.ExtendRestrictScalarsAdj.HomEquiv.fromExtendScalars.proof_4
#check CategoryTheory.Limits.Cones.functoriality.proof_4
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_add_left'
#check Function.Injective.field.proof_2
#check FreeLieAlgebra.lift.proof_5
#check GradedTensorProduct.auxEquiv_mul
#check HomologicalComplex.dgoToHomologicalComplex.proof_5
#check AlgebraicClosure.toStepOfLE.proof_3
#check AlgebraicGeometry.morphismRestrictRestrictBasicOpen.proof_7
#check CategoryTheory.discreteCategory.proof_11
#check TensorProduct.AlgebraTensorModule.lift.equiv.proof_3
#check Perfection.map.proof_5
#check CategoryTheory.TwoSquare.equivalenceJ.proof_1
#check CategoryTheory.GradedObject.ι_mapBifunctorComp₁₂MapObjIso_hom_assoc
#check CommMon_.EquivLaxBraidedFunctorPUnit.commMonToLaxBraided.proof_9
#check CochainComplex.mappingCone.δ_descCochain
#check CliffordAlgebra.lift.proof_6
#check Seminorm.instSupSet.proof_4
#check CategoryTheory.Bicategory.LeftExtension.isKanOfWhiskerLeftAdjoint.proof_2
#check CategoryTheory.instFullCoalgebraEilenbergMooreToComonadForgetCofreeAdjComparison.proof_2
#check MeasureTheory.withDensitySMulLI.proof_4
#check HasCompactSupport.convolution_integrand_bound_right_of_subset
#check CategoryTheory.Limits.cokernelOrderHom.proof_3
#check CategoryTheory.FreeMonoidalCategory.project.proof_9
#check HahnSeries.SummableFamily.instAddCommGroupSummableFamilyToAddCommMonoid.proof_10
#check CategoryTheory.ShortComplex.RightHomologyData.ofAbelian.proof_14
#check IsIntegralClosure.lift.proof_3
#check CategoryTheory.Bicategory.Adjunction.isAbsoluteLeftKanLift.proof_2
#check DoubleCentralizer.instAlgebra.proof_10
#check LieAlgebra.IsKilling.ker_weight_inf_rootSpaceProductNegSelf_eq_bot
#check Subalgebra.involutiveStar.proof_6
#check liftOfDerivationToSquareZero.proof_5
#check DoubleCentralizer.instAlgebra.proof_8
#check Action.forgetMonoidal.proof_6
#check CategoryTheory.functorCategoryPreadditive.proof_17
#check CategoryTheory.instFullCoalgebraEilenbergMooreToComonadForgetCofreeAdjComparison.proof_1
#check ContMDiff.clm_precomp
#check CategoryTheory.ComposableArrows.isoMkSucc_hom
#check CochainComplex.shiftFunctor.proof_4
#check SimplicialObject.Splitting.toKaroubiNondegComplexIsoN₁.proof_5
#check Metric.metricSpaceSum.proof_8
#check Bundle.ContinuousLinearMap.vectorPrebundle.proof_12
#check SimpleGraph.completeAtomicBooleanAlgebra.proof_22
#check HomologicalComplex.coconeOfHasColimitEval.proof_5
#check AlgebraicGeometry.PresheafedSpace.IsOpenImmersion.pullbackConeOfLeftLift.proof_4
#check ModuleCat.monModuleEquivalenceAlgebra.proof_25
#check LinearMap.inverse.proof_2
#check ConditionallyCompleteLattice.copy.proof_13
#check Valuation.extendToLocalization.proof_6
#check smoothPresheafAddGroup.proof_2
#check IsPrimitiveRoot.embeddingsEquivPrimitiveRoots.proof_4
#check CategoryTheory.coyoneda.proof_5
#check ContMDiffAt.mfderiv
#check DoubleCentralizer.coeHom.proof_5
#check SmoothMap.module'.proof_4
#check Ordinal.monoid.proof_8
#check preordToPartOrdForgetAdjunction.proof_7
#check ImplicitFunctionData.mk.inj
#check TensorProduct.LieModule.map_tmul
#check PadicInt.toZModHom.proof_4
#check CategoryTheory.Limits.Cocones.functoriality.proof_4
#check Magma.AssocQuotient.lift.proof_3
#check CliffordAlgebra.contractLeft.proof_4
#check Real.commRing.proof_25
#check LinearPMap.adjointAux.proof_6
#check CategoryTheory.ComposableArrows.isoMk₃.proof_27
#check CategoryTheory.Functor.instFullTriangleTriangleCategoryTriangleTriangleCategoryMapTriangle.proof_4
#check CategoryTheory.Quotient.preadditive.proof_6
#check ValuationRing.linearOrderedCommGroupWithZero.proof_21
#check CommRingCat.Colimits.instCommRingColimitType.proof_6
#check ContinuousLinearMap.smul_compLpL
#check Unitization.starLift.proof_3
#check Magma.AssocQuotient.lift.proof_2
#check CategoryTheory.Comonad.comparison.proof_5
#check CategoryTheory.Triangulated.Octahedron.mk.sizeOf_spec
#check ZMod.commRing.proof_19
#check ModuleCat.monModuleEquivalenceAlgebra.proof_24
#check Module.Baer.extensionOfMaxAdjoin.proof_4
#check Ring.DirectLimit.of.zero_exact_aux
#check Representation.linHom.proof_6
#check CategoryTheory.Limits.PullbackCone.isLimitOfFactors.proof_4
#check Homotopy.mkInductiveAux₁.proof_2
#check PosNum.linearOrder.proof_8
#check preordToPartOrdForgetAdjunction.proof_6
#check ContMDiffMap.prodMk.proof_1
#check SchwartzMap.mkLM.proof_2
#check ModuleCat.restrictScalarsIsEquivalenceOfRingEquiv.proof_14
#check MeasureTheory.condexpIndSMul_ae_eq_smul
#check ZMod.commRing.proof_9
#check CategoryTheory.Monoidal.CommMonFunctorCategoryEquivalence.unitIso.proof_7
#check hom_trivializationAt_target
#check CategoryTheory.Limits.pushoutAssocSymmIsPushout.proof_4
#check ContinuousMap.compStarAlgHom.proof_6
#check AlgebraicGeometry.ProjIsoSpecTopComponent.ToSpec.MemCarrier.clear_denominator'
#check CategoryTheory.transferNatTrans.proof_4
#check LieAlgebra.rootSpaceWeightSpaceProductAux.proof_6
#check Function.Injective.field.proof_22
#check AlgebraicGeometry.PresheafedSpace.GlueData.vPullbackConeIsLimit.proof_3
#check LieModule.maxTrivLinearMapEquivLieModuleHom.proof_5
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_18
