import Mathlib
#check Submodule.adjoint_orthogonalProjection
#check dist_convolution_le'
#check MeasureTheory.condexpL2_indicator_of_measurable
#check exists_embedding_euclidean_of_compact
#check MeasureTheory.set_integral_condexpL1Clm
#check IsAlgClosed.lift.SubfieldWithHom.compat
#check SmoothMap.compLeftAddMonoidHom
#check CategoryTheory.LaxBraidedFunctor.mapCommMon.proof_2
#check LinearMap.toMatrix'_toLinearMapₛₗ₂'
#check LinearEquiv.coe_toContinuousLinearEquiv'
#check ModuleCat.smul.proof_6
#check Trivialization.contMDiffAt_iff
#check CategoryTheory.Limits.pullbackDiagonalMapIdIso.proof_14
#check Submodule.comapSubtypeEquivOfLe_symm_apply
#check AlgebraCat.HasLimits.limitConeIsLimit.proof_5
#check CategoryTheory.ModuleCat.RestrictionCoextensionAdj.app'.proof_4
#check AddMagma.FreeAddSemigroup.lift.proof_4
#check TopCat.Presheaf.whiskerIsoMapGenerateCocone.proof_6
#check AlgebraicGeometry.PresheafedSpace.GlueData.opensImagePreimageMap_app_assoc
#check Matrix.toLin_kronecker
#check LinearIsometryEquiv.coe_trans
#check ModuleCat.smulNatTrans.proof_3
#check Bimod.tensorHom.proof_4
#check unitsCentralizerEquiv.proof_6
#check LinearEquiv.submoduleMap.proof_4
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_4
#check Basis.constrL_apply
#check Submodule.basis_of_pid_aux
#check SchwartzMap.bilinLeftCLM.proof_10
#check MonoidAlgebra.liftMagma.proof_6
#check CategoryTheory.yonedaLemma.proof_5
#check LinearEquiv.arrowCongr_trans
#check fdifferential_comp
#check CategoryTheory.Limits.isCokernelEpiComp.proof_3
#check ContinuousLinearEquiv.isBigO_sub
#check orderIsoRangeOfLinearSuccPredArch.proof_4
#check DihedralGroup.instGroupDihedralGroup.proof_2
#check CategoryTheory.Functor.leftDerivedObjProjectiveSucc_inv
#check LinearIsometry.equivRange_apply_coe
#check SmoothMap.addGroup.proof_10
#check ZMod.commRing.proof_10
#check ContinuousLinearMap.monoidWithZero.proof_7
#check Mod_.comap.proof_4
#check gelfandStarTransform_apply_apply
#check CategoryTheory.Limits.MulticospanIndex.ofPiForkFunctor.proof_3
#check Submodule.biSup_eq_range_dfinsupp_lsum
#check Trivialization.coe_continuousLinearEquivAt_eq
#check LinearMap.domRestrict₂.proof_2
#check StarAlgEquiv.ofLeftInverse'_symm_apply
#check PiTensorProduct.lift.proof_7
#check AddMagma.FreeAddSemigroup.lift.proof_3
#check CategoryTheory.Pi.sum.proof_5
#check Trivialization.pullback.proof_10
#check RatFunc.instAlgebraRatFuncToSemiringToDivisionSemiringToSemifieldInstFieldRatFunc.proof_7
#check exists_hilbertBasis
#check CategoryTheory.Subobject.lowerEquivalence.proof_3
#check SetLike.gmodule.proof_7
#check TopCat.Presheaf.generateEquivalenceOpensLe_inverse'_map
#check ContinuousLinearMap.adjointAux_adjointAux
#check CategoryTheory.Subgroupoid.coe.proof_8
#check ModuleCat.HasColimit.isColimitColimitCocone.proof_3
#check IntermediateField.instPartialOrderLifts.proof_3
#check SmoothWithinAt.coordChange
#check Bimod.tensorHom.proof_3
#check ModuleCat.HasColimit.coconePointSMul.proof_5
#check Bool.linearOrder.proof_7
#check GroupCat.SurjectiveOfEpiAuxs.g.proof_4
#check MeasureTheory.L1.setToL1_lipschitz
#check HasCompactSupport.hasFDerivAt_convolution_left
#check FreeLieAlgebra.lift.proof_3
#check ValuationSubring.principalUnitGroupEquiv.proof_4
#check CategoryTheory.Limits.MulticospanIndex.toPiForkFunctor.proof_3
#check LinearMap.mkContinuousOfExistsBound₂.proof_6
#check LinearMap.separatingLeft_congr_iff
#check SmoothMap.addGroup.proof_15
#check CategoryTheory.CategoryOfElements.fromCostructuredArrow.proof_2
#check CategoryTheory.functorCategoryLinear.proof_9
#check mfderivWithin_fst
#check LinearEquiv.skewProd.proof_3
#check LinearMap.toMatrix_comp
#check CategoryTheory.categoryOfElements.proof_5
#check SimpleGraph.completeAtomicBooleanAlgebra.proof_23
#check Equiv.image.proof_4
#check LinearMap.domRestrict₁₂_apply
#check LinearIsometryEquiv.norm_iteratedFDerivWithin_comp_right
#check fderivWithin_iteratedFDerivWithin
#check MeasureTheory.integral_divergence_of_hasFDerivWithinAt_off_countable_of_equiv
#check SmoothMap.semiring.proof_16
#check PowerBasis.quotientEquivQuotientMinpolyMap.proof_4
#check ContinuousLinearMap.coeFn_compLpL
#check NonUnitalStarSubalgebra.iSupLift.proof_4
#check ImplicitFunctionData.mk.sizeOf_spec
#check Action.instPreadditiveActionInstCategoryAction.proof_16
#check CategoryTheory.Functor.mapArrow.proof_3
#check CategoryTheory.ModuleCat.RestrictionCoextensionAdj.HomEquiv.fromRestriction.proof_3
#check ContinuousLinearMap.fderiv_of_bilinear
#check preordCatToPartOrdCatForgetAdjunction.proof_7
#check Trivialization.smoothOn_iff
#check PosNum.linearOrder.proof_6
#check MeasureTheory.L1.setToL1_mono
