import Mathlib
#check CategoryTheory.OplaxNatTrans.vcomp.proof_3
#check ChainComplex.toSingle₀Equiv.proof_4
#check Field.DirectLimit.field.proof_35
#check LocalizedModule.instSemiringLocalizedModuleToAddCommMonoidToNonUnitalNonAssocSemiringToNonAssocSemiringToModule.proof_12
#check smoothFiberwiseLinear.proof_9
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_13
#check LinearMap.compDer.proof_9
#check SemidirectProduct.instGroupSemidirectProduct.proof_12
#check CategoryTheory.preadditiveYoneda.proof_5
#check CategoryTheory.Abelian.BiproductToPushoutIsCokernel.isColimitBiproductToPushout.proof_4
#check ContinuousLinearEquiv.arrowCongrSL_symm_apply
#check fdifferential
#check MultilinearMap.alternatization.proof_5
#check ContinuousMap.module'.proof_6
#check rootsOfUnityEquivNthRoots.proof_5
#check Representation.dual.proof_6
#check unitsCentralizerEquiv.proof_3
#check LocalizedModule.instSMulLocalizationToCommMonoidLocalizedModule.proof_2
#check HomologicalComplex.dgoEquivHomologicalComplexCounitIso.proof_5
#check Real.commRing.proof_7
#check Action.instLinearActionInstCategoryActionInstPreadditiveActionInstCategoryAction.proof_5
#check Diffeomorph.mk.sizeOf_spec
#check LinearMap.compl₂_apply
#check SmoothOn.coordChangeL
#check CompHaus.EffectiveEpiFamily.structAux.proof_3
#check SmoothMap.smul_comp'
#check MDifferentiableWithinAt.comp
#check CategoryTheory.Comma.mapLeftComp.proof_5
#check Ideal.modulePi.proof_4
#check CategoryTheory.ModuleCat.restrictCoextendScalarsAdj.proof_3
#check Module.Baer.extensionOfMaxAdjoin.proof_2
#check LinearEquiv.ofIsUnitDet.proof_7
#check CategoryTheory.Discrete.addMonoidalFunctor.proof_10
#check TensorProduct.AlgebraTensorModule.tensorTensorTensorComm_symm_tmul
#check ContinuousLinearEquiv.comp_right_fderiv
#check Polynomial.algebraPi.proof_3
#check StarModule.decomposeProdAdjointL_symm_apply
#check TensorProduct.AlgebraTensorModule.assoc.proof_22
#check CategoryTheory.Limits.MulticospanIndex.toPiForkFunctor.proof_2
#check CategoryTheory.instFullAlgebraEilenbergMooreToMonadFreeForgetAdjComparison.proof_1
#check AddAut.group.proof_10
#check ContinuousLinearMap.flip_smul
#check MeasureTheory.set_lintegral_nnnorm_condexpL2_indicator_le
#check ZMod.commRing.proof_11
#check CategoryTheory.Limits.Cone.fromCostructuredArrow.proof_2
#check AlgebraicTopology.DoldKan.Γ₂N₁.natTrans.proof_3
#check CategoryTheory.Functor.Initial.extendCone_map_Hom
#check Trivialization.smoothAt_iff
#check WittVector.IsocrystalEquiv.mk.injEq
#check ZMod.commRing.proof_24
#check SchwartzMap.evalCLM.proof_8
#check ContMDiffAt.clm_precomp
#check CategoryTheory.Center.ofBraided.proof_6
#check SubmodulesBasis.toModuleFilterBasis.proof_4
#check CategoryTheory.Ran.equiv.proof_4
#check FiberBundleCore.trivChange.proof_7
#check LinearMap.toMatrix₂_compl₂
#check RingQuot.starRing.proof_2
#check LinearEquiv.ofSubmodule'_symm_apply
#check CategoryTheory.Pseudofunctor.comp.proof_5
#check CategoryTheory.Over.iteratedSliceEquiv.proof_6
#check VectorPrebundle.coordChange.proof_2
#check Profinite.EffectiveEpiFamily.structAux.proof_4
#check IsROrC.toStrictOrderedCommRing.proof_5
#check IsDedekindDomain.selmerGroup.proof_4
#check StarAlgHomClass.ext_topologicalClosure
#check Trivialization.coordChangeL_apply'
#check StarAlgEquiv.ofLeftInverse'_apply
#check LinearEquiv.arrowCongr.proof_8
#check ContinuousLinearMap.fderivWithin_of_bilinear
#check LinearPMap.adjointDomain.proof_5
#check SmoothMap.restrictMonoidHom.proof_2
#check SmoothOn.prod_map
#check CliffordAlgebra.even.ι.proof_6
#check Diffeomorph.coe_trans
#check CategoryTheory.Monad.algebraPreadditive.proof_18
#check CategoryTheory.ShortComplex.colimitCocone.proof_4
#check TensorProduct.tensorTensorTensorAssoc_symm_tmul
#check homology.map_eq_lift_desc'_left
#check ContinuousLinearEquiv.map_tsum
#check CategoryTheory.Over.ConstructProducts.conesEquivFunctor.proof_5
#check HomologicalComplex.flip.proof_4
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_19
#check smoothOn_continuousLinearMapCoordChange
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_11
#check Submodule.completeLattice.proof_9
#check CategoryTheory.Arrow.cechConerve.proof_6
#check CategoryTheory.Limits.IsLimit.homIso'.proof_3
#check iteratedFDerivWithin_succ_eq_comp_left
#check AlgebraicGeometry.StructureSheaf.sectionsSubring.proof_5
#check ModuleCat.binaryProductLimitCone.proof_3
#check AlgebraicGeometry.PresheafedSpace.componentwiseDiagram.proof_3
#check Mod_.comap.proof_3
#check CategoryTheory.coyonedaPreservesLimits.proof_2
#check ContinuousLinearEquiv.arrowCongrSL
#check Complex.integral_boundary_rect_of_differentiableOn_real
#check Matrix.toLinearMap₂_apply
#check IntermediateField.Lifts.upperBoundAlgHom.proof_7
#check TopCommRingCat.instCategoryTopCommRingCat.proof_4
#check HilbertBasis.coe_mk
