import Mathlib
#check CategoryTheory.Limits.constLimAdj.proof_9
#check Finsupp.lsum.proof_3
#check orthogonalProjection.proof_3
#check smoothAt_hom_bundle
#check SmoothAddMonoidMorphism.mk.sizeOf_spec
#check PresheafOfModules.Hom.instAddCommGroupHomPresheafOfModulesToQuiverToCategoryStructInstCategoryPresheafOfModules.proof_2
#check Derivation.evalAt_apply
#check continuousMultilinearCurryRightEquiv.proof_16
#check Localization.instCommSemiringLocalizationToCommMonoid.proof_6
#check CategoryTheory.CostructuredArrow.quotientEquiv.proof_5
#check Field.DirectLimit.field.proof_19
#check BoundedContinuousFunction.toLp_injective
#check Submodule.mapQLinear.proof_5
#check RatFunc.instAddCommGroup.proof_6
#check SmoothMap.ring.proof_25
#check DenseInducing.extendRingHom.proof_5
#check Finsupp.lsum.proof_6
#check ContinuousMultilinearMap.compContinuousLinearMapL_apply
#check AlgebraicGeometry.StructureSheaf.toOpen.proof_5
#check TensorProduct.dualDistribEquivOfBasis_symm_apply
#check Field.DirectLimit.field.proof_31
#check HasStrictFDerivAt.mem_implicitToLocalHomeomorph_source
#check CategoryTheory.Comonad.coalgebraPreadditive.proof_18
#check ContinuousLinearMap.mulLeftRight_apply
#check LinearMap.domRestrict₂_apply
#check LinearIsometryEquiv.prodAssoc.proof_5
#check CategoryTheory.Cat.HasLimits.limitConeLift.proof_8
#check CategoryTheory.instBicategoryMonoidalSingleObj.proof_7
#check CategoryTheory.Over.mapPullbackAdj.proof_7
#check TensorProduct.AlgebraTensorModule.tensorTensorTensorComm_tmul
#check Subfield.closure.proof_5
#check Real.commRing.proof_9
#check Cardinal.commSemiring.proof_13
#check MeasureTheory.condexpL2_const_inner
#check LinearMap.toMatrix₂_comp
#check CategoryTheory.yonedaPreservesLimits.proof_3
#check Perfection.lift.proof_3
#check WeakDual.gelfandTransform.proof_8
#check ConditionallyCompleteLattice.copy.proof_14
#check BoundedContinuousFunction.semilatticeSup.proof_4
#check CategoryTheory.Limits.preservesEqualizersOfPreservesPullbacksAndBinaryProducts.proof_3
#check Basis.toMatrixEquiv.proof_5
#check SmoothMap.coeFnAlgHom_apply
#check CategoryTheory.instBicategoryMonoidalSingleObj.proof_8
#check continuousMultilinearCurryLeftEquiv_apply
#check CategoryTheory.Triangulated.Octahedron.comm₃_assoc
#check ContinuousMap.toLp_def
#check CommMon_.EquivLaxBraidedFunctorPunit.commMonToLaxBraided.proof_11
#check Monoid.CoprodI.lift.proof_2
#check ValuationSubring.principalUnitGroupEquiv.proof_6
#check ProperCone.hyperplane_separation
#check Pretrivialization.continuousLinearMap.proof_5
#check LinearIsometryEquiv.trans.proof_1
#check AddCommGroupCat.kernelIsoKer.proof_7
#check CategoryTheory.Over.ConstructProducts.conesEquivFunctor_map_Hom
#check StarAlgEquiv.ofInjective.proof_5
#check Rep.ihom.proof_9
#check FormalMultilinearSeries.changeOriginSeries_summable_aux₁
#check ContMDiff.clm_apply
#check hasFDerivAt_inv'
#check ChainComplex.single₀MapHomologicalComplex.proof_5
#check HasStrictFDerivAt.map_implicitFunction_eq
#check ContinuousLinearMap.flip.proof_7
#check CommRingCat.Colimits.ColimitType.AddGroup.proof_15
#check ContinuousLinearMap.flipMultilinear.proof_8
#check CategoryTheory.whiskeringLeft.proof_6
#check CategoryTheory.Endofunctor.algebraPreadditive.proof_18
#check HasFDerivAt.clm_apply
#check ConvexCone.instCompleteLatticeConvexCone.proof_12
#check CategoryTheory.Presheaf.conesEquivSieveCompatibleFamily.proof_4
#check LinearMap.toMatrix_transpose
#check ContinuousMap.toLp_injective
#check CategoryTheory.Over.mapPullbackAdj.proof_6
#check LinearMap.mkContinuous₂_apply
#check Submodule.equivSubtypeMap_symm_apply
#check AlgebraicGeometry.PresheafedSpace.IsOpenImmersion.pullbackConeOfLeftFst.proof_6
#check CategoryTheory.MonoOver.inf.proof_6
#check TopCat.GlueData.ofOpenSubsets.proof_5
#check NonUnitalSubalgebra.iSupLift.proof_4
#check CategoryTheory.Limits.evaluationJointlyReflectsColimits.proof_2
#check CategoryTheory.Limits.MultispanIndex.ofSigmaCoforkFunctor.proof_3
#check AlgebraicGeometry.StructureSheaf.comap.proof_5
#check CategoryTheory.effectiveEpiStructOfIsColimit.proof_2
#check CommRingCat.Colimits.instCommRingColimitType.proof_20
#check Finset.disjiUnion_disjiUnion
#check ContinuousLinearMap.comp_assoc
#check Field.DirectLimit.field.proof_33
#check AlgebraCat.HasLimits.limitConeIsLimit.proof_6
#check CompHaus.limitCone.proof_3
#check Int.euclideanDomain.proof_28
#check CategoryTheory.Monoidal.functorHasRightDual.proof_5
#check Trivialization.pullback.proof_12
#check CategoryTheory.Idempotents.instAddCommGroupHom.proof_15
#check LocalizedModule.instAddCommGroupLocalizedModuleToAddCommMonoid.proof_3
#check CategoryTheory.HomOrthogonal.matrixDecomposition.proof_8
#check CategoryTheory.Monad.algebraPreadditive.proof_16
#check AddLocalization.r'.proof_2
#check SmoothBumpCovering.embeddingPiTangent_injective_mfderiv
#check mfderivWithin_snd
#check HasMFDerivWithinAt.comp
