#check Mon_.monMonoidal.proof_6
#check AlgebraicGeometry.morphismRestrictRestrictBasicOpen.proof_5
#check CompleteLattice.Independent.dfinsupp_lsum_injective
#check MultilinearMap.currySumEquiv.proof_6
#check RatFunc.liftMonoidWithZeroHom.proof_3
#check ContinuousLinearMap.integral_comp_comm'
#check CategoryTheory.evaluationRightAdjoint.proof_9
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_13
#check MeasureTheory.AEStronglyMeasurable.convolution_integrand_swap_snd'
#check IntermediateField.instPartialOrderLifts.proof_1
#check PiTensorProduct.lift.proof_8
#check CategoryTheory.Comonad.coalgebraPreadditive.proof_5
#check LinearEquiv.submoduleMap_symm_apply
#check CategoryTheory.functorCategoryPreadditive.proof_16
#check TensorProduct.toMatrix_assoc
#check CategoryTheory.InjectiveResolution.ofCocomplex_d
#check CategoryTheory.ModuleCat.ExtendRestrictScalarsAdj.HomEquiv.evalAt.proof_2
#check AlgebraicTopology.DoldKan.Γ₂N₁.natTrans.proof_2
#check Homeomorph.changeInv.proof_3
#check ContinuousLinearMap.flipMultilinear.proof_11
#check CategoryTheory.Pseudofunctor.mkOfOplax'.proof_4
#check Surreal.orderedAddCommGroup.proof_16
#check ContinuousLinearMap.coprodSubtypeLEquivOfIsCompl.proof_5
#check SchwartzMap.mkCLM
#check CategoryTheory.Presheaf.isSheafForIsSheafFor'.proof_9
#check ContinuousLinearMap.le_op_norm₂
#check LinearEquiv.trans_apply
#check CategoryTheory.ModuleCat.ExtendRestrictScalarsAdj.Counit.map.proof_6
#check MultilinearMap.curryLeft.proof_5
#check SSet.horn.proof_3
#check CategoryTheory.Idempotents.KaroubiHomologicalComplexEquivalence.unitIso.proof_8
#check MultilinearMap.currySumEquiv.proof_7
#check Homotopy.mkCoinductive.proof_1
#check SchwartzMap.fderivCLM_apply
#check hfdifferential.proof_8
#check Module.End.divisionRing.proof_32
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_smul_left'
#check MulAut.instGroupMulAut.proof_10
#check Equiv.Set.rangeSplittingImageEquiv.proof_4
#check ContinuousLinearEquiv.piRing.proof_18
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_zero_left
#check CategoryTheory.evaluationRightAdjoint.proof_8
#check ContinuousLinearEquiv.comp_differentiableOn_iff
#check CategoryTheory.Limits.preservesLimitOfPreservesEqualizersAndProduct.proof_12
#check Ideal.cotangentEquivIdeal_symm_apply
#check KaehlerDifferential.quotientCotangentIdeal.proof_4
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_zero_left'
#check LinearEquiv.arrowCongr.proof_6
#check Matrix.toLinearMapₛₗ₂'_stdBasis
#check SmoothMap.compLeftMonoidHom
#check Submodule.dualQuotEquivDualAnnihilator_symm_apply_mk
#check CategoryTheory.Limits.coconeEquivalenceOpConeOp.proof_10
#check Ideal.quotientToQuotientRangePowQuotSucc_mk
#check AlgHom.restrictNormalAux.proof_2
#check CategoryTheory.Monoidal.CommMonFunctorCategoryEquivalence.functor.proof_6
#check ContinuousLinearMap.projKerOfRightInverse_apply_idem
#check HomologicalComplex.asFunctor.proof_5
#check Submodule.adjoint_orthogonalProjection
#check dist_convolution_le'
#check MeasureTheory.condexpL2_indicator_of_measurable
#check exists_embedding_euclidean_of_compact
#check MeasureTheory.set_integral_condexpL1Clm
#check SmoothMap.compLeftAddMonoidHom
#check CategoryTheory.LaxBraidedFunctor.mapCommMon.proof_2
#check LinearMap.toMatrix'_toLinearMapₛₗ₂'
#check LinearEquiv.coe_toContinuousLinearEquiv'
#check Trivialization.contMDiffAt_iff
#check CategoryTheory.Limits.pullbackDiagonalMapIdIso.proof_14
#check Submodule.comapSubtypeEquivOfLe_symm_apply
#check AlgebraCat.HasLimits.limitConeIsLimit.proof_5
#check Game.instAddCommGroupWithOneGame.proof_12
#check CategoryTheory.ModuleCat.RestrictionCoextensionAdj.app'.proof_4
#check AddMagma.FreeAddSemigroup.lift.proof_4
#check TopCat.Presheaf.whiskerIsoMapGenerateCocone.proof_6
#check AlgebraicGeometry.PresheafedSpace.GlueData.opensImagePreimageMap_app_assoc
#check Game.instAddCommGroupWithOneGame.proof_7
#check Matrix.toLin_kronecker
#check LinearIsometryEquiv.coe_trans
#check Bimod.tensorHom.proof_4
#check LinearEquiv.submoduleMap.proof_4
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_4
#check Basis.constrL_apply
#check Submodule.basis_of_pid_aux
#check SchwartzMap.bilinLeftCLM.proof_10
#check MonoidAlgebra.liftMagma.proof_6
#check homeomorphUnitBall.proof_3
#check CategoryTheory.yonedaLemma.proof_5
#check LinearEquiv.arrowCongr_trans
#check fdifferential_comp
#check CategoryTheory.Limits.isCokernelEpiComp.proof_3
#check ContinuousLinearEquiv.isBigO_sub
#check orderIsoRangeOfLinearSuccPredArch.proof_4
#check DihedralGroup.instGroupDihedralGroup.proof_2
#check CategoryTheory.Functor.leftDerivedObjProjectiveSucc_inv
#check LinearIsometry.equivRange_apply_coe
#check SmoothMap.addGroup.proof_10
#check ZMod.commRing.proof_10
#check ContinuousLinearMap.monoidWithZero.proof_7
#check Mod_.comap.proof_4
#check gelfandStarTransform_apply_apply
