import Mathlib
#check IsPrimitiveRoot.embeddingsEquivPrimitiveRoots.proof_3
#check AlgebraCat.HasLimits.limitConeIsLimit.proof_8
#check Polynomial.algebraPi.proof_4
#check Function.Injective.divisionRing.proof_1
#check LieSubmodule.Quotient.actionAsEndoMap.proof_7
#check CategoryTheory.CommSq.rightAdjointLiftStructEquiv.proof_6
#check CategoryTheory.Functor.mapHomotopy.proof_2
#check LieHom.quotKerEquivRange.proof_5
#check LinearMap.lsum_symm_apply
#check PerfectClosure.lift.proof_3
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_mono_left'
#check AlgebraicGeometry.Scheme.Spec_map_presheaf_map_eqToHom
#check ChainComplex.single₀IsoSingle.proof_6
#check CategoryTheory.Limits.preservesCoequalizersOfPreservesPushoutsAndBinaryCoproducts.proof_4
#check MeasureTheory.integral_condexpL2_eq
#check MeasureTheory.integral_condexpL2_eq_of_fin_meas_real
#check Trivialization.baseSet_continuousLinearMap
#check HasFPowerSeriesOnBall.hasFDerivAt
#check LinearMap.mkContinuousOfExistsBound₂.proof_7
#check Ideal.modulePi.proof_7
#check Rack.instDivInvMonoidEnvelGroup.proof_13
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_19
#check Convex.taylor_approx_two_segment
#check SimplicialObject.Splitting.toKaroubiNondegComplexIsoN₁.proof_6
#check PiLp.pseudoEmetricAux.proof_4
#check VectorPrebundle.mk.injEq
#check Zsqrtd.lift.proof_6
#check ZMod.commRing.proof_12
#check Polynomial.algebraPi.proof_5
#check Ideal.quotientToQuotientRangePowQuotSucc.proof_3
#check HasMFDerivWithinAt.mul'
#check ContinuousLinearEquiv.hasSum
#check Module.End.divisionRing.proof_39
#check OrthogonalFamily.linearIsometry.proof_5
#check Basis.constr.proof_3
#check Rep.ofModuleMonoidAlgebra.proof_4
#check Real.commRing.proof_24
#check SmoothBumpCovering.embeddingPiTangent_ker_mfderiv
#check Diffeomorph.trans.proof_2
#check ZMod.commRing.proof_20
#check CategoryTheory.isColimitOfEffectiveEpiStruct.proof_3
#check SmoothMap.compLeftRingHom.proof_5
#check ChainComplex.mk
#check CategoryTheory.Endofunctor.coalgebraPreadditive.proof_16
#check CategoryTheory.OplaxFunctor.comp.proof_6
#check CategoryTheory.Monad.algebraPreadditive.proof_5
#check MeasureTheory.set_integral_condexpInd
#check ContinuousLinearEquiv.image_eq_preimage
#check MulChar.commGroup.proof_8
#check Perfection.map.proof_4
#check CategoryTheory.Over.pullback.proof_7
#check CategoryTheory.LaxMonoidalFunctor.mapMonFunctor.proof_4
#check ContinuousLinearMap.iteratedFDerivWithin_comp_right
#check MeasureTheory.L1.setToL1_add_left
#check CategoryTheory.CosimplicialObject.Augmented.whiskering.proof_3
#check ContMDiffMap.comp.proof_1
#check StarSubalgebra.subtype.proof_6
#check BiheytingHom.copy.proof_4
#check AffineMap.instAddTorsorAffineMapAddGroupIsAddTorsorToAddGroupAffineMapToAddGroupInstAddCommGroupAffineMapAddGroupIsAddTorsorToAddGroup.proof_2
#check AlgebraicGeometry.Scheme.affineBasisCoverRing.proof_4
#check CategoryTheory.Endofunctor.Adjunction.AlgCoalgEquiv.unitIso.proof_5
#check SimplicialObject.Split.nondegComplexFunctor.proof_3
#check LeftInvariantDerivation.mk.inj
#check CategoryTheory.Triangulated.Octahedron.comm₂_assoc
#check IsLocalExtrOn.exists_linear_map_of_hasStrictFDerivAt
#check CategoryTheory.Presheaf.conesEquivSieveCompatibleFamily.proof_5
#check ContMDiffAt.cle_arrowCongr
#check ZMod.instFieldZMod.proof_85
#check Poly.instCommRingPoly.proof_13
#check ContinuousLinearMap.bilinearComp_apply
#check Module.End.divisionRing.proof_43
#check CategoryTheory.evaluationLeftAdjoint.proof_8
#check DoubleQuot.coe_quotQuotEquivQuotOfLEₐ
#check AddCommGroupCat.kernelIsoKer.proof_6
#check CategoryTheory.Under.pushout.proof_6
#check Pretrivialization.continuousLinearMap.proof_6
#check MeasureTheory.L1.SimpleFunc.setToL1SCLM_smul_left
#check TensorProduct.AlgebraTensorModule.leftComm_symm_tmul
#check CategoryTheory.MonoOver.supLe.proof_4
#check CategoryTheory.Limits.preservesColimitOfPreservesCoequalizersAndCoproduct.proof_11
#check MeasureTheory.L1.setToL1_congr_left
#check Continuous.convolution_integrand_fst
#check polarCoord.proof_8
#check CategoryTheory.ShortComplex.isColimitOfIsColimitπ.proof_3
#check AddSubgroup.instAddActionElemSetLeftTransversalsCoeAddSubgroupInstSetLikeAddSubgroupToAddMonoidToSubNegAddMonoid.proof_2
#check homology.map_desc_assoc
#check ContinuousLinearEquiv.tsum_eq_iff
#check MeasureTheory.set_integral_condexpL2_indicator
#check ContinuousLinearMap.extend.proof_1
#check CategoryTheory.evaluationRightAdjoint.proof_10
#check MultilinearMap.domDomCongrLinearEquiv'.proof_5
#check CochainComplex.mkAux.proof_1
#check convolution_eq_right'
#check FiberwiseLinear.trans_localHomeomorph_apply
#check CategoryTheory.OplaxFunctor.comp.proof_2
#check Field.DirectLimit.field.proof_22
#check Trivialization.continuousLinearMap
#check AddMonoidHom.addCommMonoid.proof_8
#check Complex.commRing.proof_12
#check FiniteDimensional.basisSingleton.proof_6
