from __future__ import annotations

from enum import Enum


class NodeStatus(str, Enum):
    raw = "raw"
    classified = "classified"
    decomposed = "decomposed"
    locally_refined = "locally_refined"
    validated = "validated"
    resolved = "resolved"
    opaque = "opaque"


class DocumentKind(str, Enum):
    unknown = "unknown"
    document = "document"
    section = "section"
    subsection = "subsection"
    paragraph = "paragraph"
    definition = "definition"
    structure_definition = "structure-definition"
    instance_definition = "instance-definition"
    inductive_type_definition = "inductive-type-definition"
    theorem = "theorem"
    lemma = "lemma"
    proposition = "proposition"
    corollary = "corollary"
    example = "example"
    remark = "remark"
    proof = "proof"
    local_claim = "local_claim"
    calculation_block = "calculation_block"
    opaque = "opaque"


class ProofKind(str, Enum):
    unknown = "unknown"
    logical_sequence = "logical_sequence"
    simple = "simple"
    calculation = "calculation"
    cases = "cases"
    induction = "induction"
    contradiction = "contradiction"
    contrapositive = "contrapositive"
    extensionality = "extensionality"
    existence = "existence"
    uniqueness = "uniqueness"
    equivalence = "equivalence"
    construction = "construction"
    minimal_counterexample = "minimal_counterexample"
    infinite_descent = "infinite_descent"
    exhaustion = "exhaustion"
    counting = "counting"
    pigeonhole = "pigeonhole"
    invariant = "invariant"
    monotonicity_bounding = "monotonicity_bounding"
    reduction = "reduction"
    diagram_chase = "diagram_chase"
    epsilon_delta = "epsilon_delta"
    generic_element = "generic_element"
    local_to_global = "local_to_global"
    maximal_minimal = "maximal_minimal"
    compactness = "compactness"
    density = "density"
    approximation = "approximation"
    universal_property = "universal_property"
    algorithmic = "algorithmic"
    probabilistic = "probabilistic"
    genericity_ae = "genericity_ae"
    diagrammatic_geometric = "diagrammatic_geometric"
    local_claim = "local_claim"
    theorem_application = "theorem_application"
    definition_unfolding = "definition_unfolding"
    specialize = "specialize"
    opaque = "opaque"
