from __future__ import annotations

import asyncio
from pathlib import Path

from mathdoc_agent.export.json import to_json
from mathdoc_agent.models.base import DocumentKind
from mathdoc_agent.models.payloads import (
    ConstructorArgumentData,
    InductiveConstructorData,
    InstanceGiveData,
    ParameterData,
    StructureFieldData,
)
from mathdoc_agent.models.refinement_specs import DocumentChildSpec, DocumentRefinementSpec
from mathdoc_agent.orchestration.document_orchestrator import document_from_text, refine_math_document
from mathdoc_agent.plugins.document_types import default_document_handler_registry
from mathdoc_agent.plugins.proof_types import default_proof_handler_registry


SOURCE_TEXT = """Definition. A sorted list over a type alpha with an order relation consists
of a list xs : List alpha together with a proof that xs is sorted.

Class. A magma consists of a type carrier and a binary operation mul on carrier.
The operation is part of the data of the class.

Instance. The natural numbers form a magma using Nat as the carrier and addition
as the binary operation.

Inductive proposition. Even is the proposition on natural numbers generated by
zero_even, saying that zero is even, and step_even, saying that if n is even then
n+2 is even.

Inductive type. A binary tree with labels in alpha has constructors leaf with no
arguments and node with a left tree, a label, and a right tree.

Definition. A bounded natural number consists of a value n : Nat together with a
proof that n is at most a fixed bound b."""


class DocumentParserAgent:
    def __call__(self, payload):
        return DocumentRefinementSpec(
            children=[
                DocumentChildSpec(
                    id_suffix="sorted_list",
                    kind=DocumentKind.structure_definition,
                    label="def:sorted_list",
                    text=(
                        "A sorted list over a type alpha with an order relation consists "
                        "of a list xs : List alpha together with a proof that xs is sorted."
                    ),
                    name="SortedList",
                    is_class=False,
                    is_prop=False,
                    parameters=[
                        ParameterData(name="α", type="Type", binder="implicit"),
                        ParameterData(name="le", type="α → α → Prop"),
                    ],
                    fields=[
                        StructureFieldData(name="xs", type="List α"),
                        StructureFieldData(name="sorted", type="List.Pairwise le xs"),
                    ],
                ),
                DocumentChildSpec(
                    id_suffix="magma",
                    kind=DocumentKind.structure_definition,
                    label="class:magma",
                    text=(
                        "A magma consists of a type carrier and a binary operation mul on carrier. "
                        "The operation is part of the data of the class."
                    ),
                    name="Magma",
                    is_class=True,
                    is_prop=False,
                    fields=[
                        StructureFieldData(name="carrier", type="Type"),
                        StructureFieldData(name="mul", type="carrier → carrier → carrier"),
                    ],
                ),
                DocumentChildSpec(
                    id_suffix="nat_magma",
                    kind=DocumentKind.instance_definition,
                    label="inst:nat_magma",
                    text="The natural numbers form a magma using Nat as the carrier and addition as the binary operation.",
                    name="natAddMagma",
                    class_name="Magma",
                    target="Nat",
                    gives=[
                        InstanceGiveData(name="carrier", value="Nat"),
                        InstanceGiveData(name="mul", value="Nat.add"),
                    ],
                ),
                DocumentChildSpec(
                    id_suffix="even",
                    kind=DocumentKind.inductive_type_definition,
                    label="ind:even",
                    text=(
                        "Even is the proposition on natural numbers generated by zero_even, "
                        "saying that zero is even, and step_even, saying that if n is even "
                        "then n+2 is even."
                    ),
                    name="Even",
                    is_prop=True,
                    indices=[ParameterData(name="n", type="Nat")],
                    constructors=[
                        InductiveConstructorData(name="zero_even", arguments=[]),
                        InductiveConstructorData(
                            name="step_even",
                            arguments=[
                                ConstructorArgumentData(name="n", type="Nat"),
                                ConstructorArgumentData(name="h", type="Even n"),
                            ],
                            index_args=["n + 2"],
                        ),
                    ],
                ),
                DocumentChildSpec(
                    id_suffix="binary_tree",
                    kind=DocumentKind.inductive_type_definition,
                    label="ind:binary_tree",
                    text=(
                        "A binary tree with labels in alpha has constructors leaf with no "
                        "arguments and node with a left tree, a label, and a right tree."
                    ),
                    name="BinaryTree",
                    is_prop=False,
                    parameters=[ParameterData(name="α", type="Type", binder="implicit")],
                    constructors=[
                        InductiveConstructorData(name="leaf", arguments=[]),
                        InductiveConstructorData(
                            name="node",
                            arguments=[
                                ConstructorArgumentData(name="left", type="BinaryTree α"),
                                ConstructorArgumentData(name="label", type="α"),
                                ConstructorArgumentData(name="right", type="BinaryTree α"),
                            ],
                        ),
                    ],
                ),
                DocumentChildSpec(
                    id_suffix="bounded_nat",
                    kind=DocumentKind.structure_definition,
                    label="def:bounded_nat",
                    text=(
                        "A bounded natural number consists of a value n : Nat together "
                        "with a proof that n is at most a fixed bound b."
                    ),
                    name="BoundedNat",
                    is_class=False,
                    is_prop=False,
                    parameters=[ParameterData(name="b", type="Nat")],
                    fields=[
                        StructureFieldData(name="n", type="Nat"),
                        StructureFieldData(name="bound", type="n ≤ b"),
                    ],
                ),
            ]
        )


def build_registries():
    document_registry = default_document_handler_registry(parser_agent=DocumentParserAgent())
    proof_registry = default_proof_handler_registry()
    return document_registry, proof_registry


async def build_document_json() -> str:
    document_registry, proof_registry = build_registries()
    document = document_from_text(
        SOURCE_TEXT,
        id="lean_definition_examples",
        title="Lean Definition Examples",
    )
    refined = await refine_math_document(
        document,
        document_registry,
        proof_registry,
        document_iterations=5,
        proof_iterations=5,
    )
    return to_json(refined, indent=2)


async def write_example(output_dir: Path | None = None) -> list[Path]:
    target_dir = output_dir or Path(__file__).parent
    source_path = target_dir / "lean_definition_examples.md"
    json_path = target_dir / "lean_definition_examples.json"
    source_path.write_text(SOURCE_TEXT + "\n", encoding="utf-8")
    json_path.write_text(await build_document_json(), encoding="utf-8")
    return [source_path, json_path]


def main() -> None:
    for path in asyncio.run(write_example()):
        print(path)


if __name__ == "__main__":
    main()
