import Mathbin.Tactic.Alias
import Mathbin.Tactic.Clear
import Mathbin.Tactic.Choose
import Mathbin.Tactic.Converter.ApplyCongr
import Mathbin.Tactic.Congr
import Mathbin.Tactic.DecTrivial
import Mathbin.Tactic.DeltaInstance
import Mathbin.Tactic.Dependencies
import Mathbin.Tactic.Elide
import Mathbin.Tactic.Explode
import Mathbin.Tactic.Find
import Mathbin.Tactic.Finish
import Mathbin.Tactic.Generalizes
import Mathbin.Tactic.GeneralizeProofs
import Mathbin.Tactic.Itauto
import Mathbin.Tactic.Lift
import Mathbin.Tactic.Lint.Default
import Mathbin.Tactic.Localized
import Mathbin.Tactic.MkIffOfInductiveProp
import Mathbin.Tactic.NormCast
import Mathbin.Tactic.Obviously
import Mathbin.Tactic.PrettyCases
import Mathbin.Tactic.Protected
import Mathbin.Tactic.PushNeg
import Mathbin.Tactic.Replacer
import Mathbin.Tactic.RenameVar
import Mathbin.Tactic.RestateAxiom
import Mathbin.Tactic.Rewrite
import Mathbin.Tactic.ShowTerm
import Mathbin.Tactic.SimpRw
import Mathbin.Tactic.SimpCommand
import Mathbin.Tactic.SimpResult
import Mathbin.Tactic.Simps
import Mathbin.Tactic.SplitIfs
import Mathbin.Tactic.Squeeze
import Mathbin.Tactic.Suggest
import Mathbin.Tactic.Tauto
import Mathbin.Tactic.TruncCases
import Mathbin.Tactic.UnifyEquations
import Mathbin.Tactic.Where

